// 자동 생성 데이터 — 성인 영어회화 표현 묶음.
// 실전 회화 2000 — 주제 11~20 (주제당 100개)

import 'conversation_data.dart';

/// 실전 회화 2000 — 주제 11~20
const List<List<ConvExpr>> convTier2 = [
  // 11번 주제
  [
    ConvExpr("boarding pass", "탑승권"),
    ConvExpr("passport", "여권"),
    ConvExpr("gate", "탑승구"),
    ConvExpr("aisle seat", "통로 쪽 자리"),
    ConvExpr("window seat", "창가 쪽 자리"),
    ConvExpr("carry-on", "기내 수하물"),
    ConvExpr("checked bag", "부치는 짐"),
    ConvExpr("departure", "출발"),
    ConvExpr("arrival", "도착"),
    ConvExpr("layover", "경유 대기"),
    ConvExpr("customs", "세관"),
    ConvExpr("baggage claim", "수하물 찾는 곳"),
    ConvExpr("security check", "보안 검색"),
    ConvExpr("delayed flight", "지연된 항공편"),
    ConvExpr("one way", "편도"),
    ConvExpr("connecting flight", "연결 항공편"),
    ConvExpr("overhead bin", "머리 위 짐칸"),
    ConvExpr("seat belt", "안전벨트"),
    ConvExpr("tray table", "접이식 테이블"),
    ConvExpr("I'd like to check in.", "체크인하려고 해요"),
    ConvExpr("Where is the check-in counter?", "체크인 카운터가 어디예요?"),
    ConvExpr("Can I check this bag?", "이 가방 부칠 수 있어요?"),
    ConvExpr("How many bags can I check?", "짐 몇 개까지 부쳐요?"),
    ConvExpr("Is my bag too heavy?", "제 짐이 너무 무거워요?"),
    ConvExpr("I only have carry-on.", "기내용 짐만 있어요"),
    ConvExpr("Aisle seat, please.", "통로 쪽으로 주세요"),
    ConvExpr("Can I get a window seat?", "창가 자리 받을 수 있어요?"),
    ConvExpr("Which gate is it?", "몇 번 게이트예요?"),
    ConvExpr("What time is boarding?", "탑승은 몇 시예요?"),
    ConvExpr("My flight is at three.", "제 비행기는 세 시예요"),
    ConvExpr("Is the flight on time?", "항공편 제시간에 가나요?"),
    ConvExpr("The flight is delayed.", "항공편이 지연됐어요"),
    ConvExpr("How long is the delay?", "얼마나 지연되나요?"),
    ConvExpr("Where is gate twelve?", "12번 게이트가 어디예요?"),
    ConvExpr("Is this the right gate?", "여기가 맞는 게이트예요?"),
    ConvExpr("I'm in the wrong line.", "줄을 잘못 섰어요"),
    ConvExpr("Where is the restroom?", "화장실이 어디예요?"),
    ConvExpr("Do I take off my shoes?", "신발 벗어야 하나요?"),
    ConvExpr("Please open your bag.", "가방 열어 주세요"),
    ConvExpr("I have a laptop inside.", "안에 노트북이 있어요"),
    ConvExpr("Nothing to declare.", "신고할 물건 없어요"),
    ConvExpr("I'm here on vacation.", "휴가로 왔어요"),
    ConvExpr("I'm here for business.", "출장으로 왔어요"),
    ConvExpr("Where are you staying?", "어디에 묵으세요?"),
    ConvExpr("At a hotel downtown.", "시내 호텔에요"),
    ConvExpr("This is my return ticket.", "이게 제 돌아가는 표예요"),
    ConvExpr("May I see your passport?", "여권 좀 보여 주시겠어요?"),
    ConvExpr("Please fill out this form.", "이 양식을 작성해 주세요"),
    ConvExpr("Can I have a window seat?", "창가 자리로 바꿔 줄 수 있어요?"),
    ConvExpr("Is there an earlier flight?", "더 이른 항공편 있어요?"),
    ConvExpr("I missed my connection.", "연결 항공편을 놓쳤어요"),
    ConvExpr("Can you rebook me?", "다시 예약해 줄 수 있어요?"),
    ConvExpr("Where do I pick up bags?", "짐은 어디서 찾아요?"),
    ConvExpr("My luggage didn't arrive.", "제 짐이 안 나왔어요"),
    ConvExpr("I'd like to report it.", "분실 신고하고 싶어요"),
    ConvExpr("Here is my baggage tag.", "여기 수하물 표예요"),
    ConvExpr("Could I have some water?", "물 좀 주시겠어요?"),
    ConvExpr("Chicken or beef, please?", "닭고기랑 소고기 중에 뭐예요?"),
    ConvExpr("I'll have the chicken.", "닭고기로 할게요"),
    ConvExpr("Could you help me with this?", "이것 좀 도와주시겠어요?"),
    ConvExpr("May I recline my seat?", "의자 뒤로 젖혀도 될까요?"),
    ConvExpr("Could I get a blanket?", "담요 하나 주시겠어요?"),
    ConvExpr("Excuse me, that's my seat.", "실례지만 제 자리예요"),
    ConvExpr("Do you mind switching seats?", "자리 바꿔도 괜찮을까요?"),
    ConvExpr("How long is the flight?", "비행시간이 얼마나 되나요?"),
    ConvExpr("We land in two hours.", "두 시간 뒤에 도착해요"),
    ConvExpr("Is there WiFi on board?", "기내에 와이파이 있어요?"),
    ConvExpr("The overhead bin is full.", "짐칸이 꽉 찼어요"),
    ConvExpr("Could you watch my bag?", "제 가방 좀 봐 주시겠어요?"),
    ConvExpr("I need to charge my phone.", "폰을 충전해야 해요"),
    ConvExpr("Where can I exchange money?", "환전은 어디서 하나요?"),
    ConvExpr("Is there a shuttle bus?", "셔틀버스 있어요?"),
    ConvExpr("How do I get downtown?", "시내까지 어떻게 가요?"),
    ConvExpr("The flight was canceled.", "항공편이 취소됐어요"),
    ConvExpr("What are my options now?", "이제 어떻게 해야 하죠?"),
    ConvExpr("Is there a hotel voucher?", "호텔 바우처 나오나요?"),
    ConvExpr("I'd like to change my seat.", "자리를 바꾸고 싶어요"),
    ConvExpr("Do you have any upgrades?", "업그레이드 자리 있어요?"),
    ConvExpr("How much is the fee?", "수수료가 얼마예요?"),
    ConvExpr("My seat doesn't recline.", "제 자리가 안 젖혀져요"),
    ConvExpr("The screen isn't working.", "화면이 안 나와요"),
    ConvExpr("Could you move my bag?", "제 가방 좀 옮겨 주시겠어요?"),
    ConvExpr("Please fasten your seat belt.", "안전벨트를 매 주세요"),
    ConvExpr("We are about to land.", "곧 착륙합니다"),
    ConvExpr("Please stay seated.", "자리에 앉아 계세요"),
    ConvExpr("Boarding begins in ten minutes.", "10분 뒤에 탑승 시작해요"),
    ConvExpr("This is the final call.", "마지막 탑승 안내예요"),
    ConvExpr("Your flight is now boarding.", "지금 탑승 중이에요"),
    ConvExpr("I'd like an aisle seat instead.", "대신 통로 자리 주세요"),
    ConvExpr("Could you print my ticket?", "표 좀 출력해 주시겠어요?"),
    ConvExpr("I lost my boarding pass.", "탑승권을 잃어버렸어요"),
    ConvExpr("Where is the transfer desk?", "환승 데스크가 어디예요?"),
    ConvExpr("Do I need to recheck bags?", "짐을 다시 부쳐야 하나요?"),
    ConvExpr("How long is the layover?", "경유 대기가 얼마나 돼요?"),
    ConvExpr("Is there time to eat?", "밥 먹을 시간 있어요?"),
    ConvExpr("I have a tight connection.", "환승 시간이 빠듯해요"),
    ConvExpr("Can I take this through security?", "이거 보안 검색 통과되나요?"),
    ConvExpr("Liquids must be under three ounces.", "액체는 소량만 가능해요"),
    ConvExpr("Please remove your laptop.", "노트북을 꺼내 주세요"),
    ConvExpr("Step through, please.", "통과해 주세요"),
  ],
  // 12번 주제
  [
    ConvExpr("front desk", "프런트"),
    ConvExpr("lobby", "로비"),
    ConvExpr("reservation", "예약"),
    ConvExpr("room key", "방 키"),
    ConvExpr("single room", "싱글룸"),
    ConvExpr("double room", "더블룸"),
    ConvExpr("suite", "스위트룸"),
    ConvExpr("housekeeping", "객실 청소"),
    ConvExpr("room service", "룸서비스"),
    ConvExpr("wake-up call", "모닝콜"),
    ConvExpr("extra towel", "여분 수건"),
    ConvExpr("air conditioning", "에어컨"),
    ConvExpr("elevator", "엘리베이터"),
    ConvExpr("breakfast buffet", "조식 뷔페"),
    ConvExpr("late checkout", "늦은 체크아웃"),
    ConvExpr("deposit", "보증금"),
    ConvExpr("vacancy", "빈 방"),
    ConvExpr("guest", "투숙객"),
    ConvExpr("I have a reservation.", "예약했어요"),
    ConvExpr("The name is Kim.", "이름은 김이에요"),
    ConvExpr("Do you have any rooms?", "빈 방 있어요?"),
    ConvExpr("I'd like a room for two.", "두 명 방으로 주세요"),
    ConvExpr("For two nights, please.", "2박으로 부탁해요"),
    ConvExpr("How much per night?", "1박에 얼마예요?"),
    ConvExpr("Is breakfast included?", "조식 포함인가요?"),
    ConvExpr("What time is breakfast?", "조식은 몇 시예요?"),
    ConvExpr("Where is the restaurant?", "식당이 어디예요?"),
    ConvExpr("What floor is my room?", "제 방이 몇 층이에요?"),
    ConvExpr("Can I see the room first?", "방을 먼저 봐도 될까요?"),
    ConvExpr("I'd like a quieter room.", "더 조용한 방으로 주세요"),
    ConvExpr("Do you have a higher floor?", "더 높은 층 있어요?"),
    ConvExpr("What time is check-in?", "체크인은 몇 시예요?"),
    ConvExpr("What time is checkout?", "체크아웃은 몇 시예요?"),
    ConvExpr("Can I check in early?", "일찍 체크인해도 되나요?"),
    ConvExpr("Can I check out later?", "늦게 체크아웃해도 되나요?"),
    ConvExpr("Could I leave my luggage?", "짐을 맡겨도 될까요?"),
    ConvExpr("I'll pick it up later.", "나중에 찾아갈게요"),
    ConvExpr("Is there free WiFi?", "무료 와이파이 있어요?"),
    ConvExpr("What is the WiFi password?", "와이파이 비밀번호가 뭐예요?"),
    ConvExpr("Could I get the password?", "비밀번호 알려 주시겠어요?"),
    ConvExpr("Is parking free here?", "여기 주차 무료인가요?"),
    ConvExpr("Where can I park?", "어디에 주차하나요?"),
    ConvExpr("Is there a gym?", "헬스장 있어요?"),
    ConvExpr("Is there a pool?", "수영장 있어요?"),
    ConvExpr("What time does it close?", "몇 시에 닫아요?"),
    ConvExpr("Could I have extra towels?", "수건 좀 더 주시겠어요?"),
    ConvExpr("Could I get another pillow?", "베개 하나 더 주시겠어요?"),
    ConvExpr("The room is too cold.", "방이 너무 추워요"),
    ConvExpr("The heater isn't working.", "난방이 안 돼요"),
    ConvExpr("The shower has no hot water.", "샤워기에 뜨거운 물이 안 나와요"),
    ConvExpr("The sink is clogged.", "세면대가 막혔어요"),
    ConvExpr("The toilet won't flush.", "변기 물이 안 내려가요"),
    ConvExpr("The light is broken.", "전등이 고장 났어요"),
    ConvExpr("The TV doesn't turn on.", "텔레비전이 안 켜져요"),
    ConvExpr("My key card doesn't work.", "카드 키가 안 돼요"),
    ConvExpr("Could you send someone up?", "사람 좀 올려 보내 주시겠어요?"),
    ConvExpr("It's very noisy next door.", "옆방이 너무 시끄러워요"),
    ConvExpr("Could I change rooms?", "방을 바꿔도 될까요?"),
    ConvExpr("The room wasn't cleaned.", "방이 청소가 안 됐어요"),
    ConvExpr("Please clean my room.", "방 청소해 주세요"),
    ConvExpr("Please don't disturb.", "방해하지 말아 주세요"),
    ConvExpr("Come back later, please.", "나중에 다시 와 주세요"),
    ConvExpr("I'd like room service.", "룸서비스 부탁해요"),
    ConvExpr("Could I order breakfast?", "아침 주문할 수 있을까요?"),
    ConvExpr("Please bring it at eight.", "여덟 시에 갖다주세요"),
    ConvExpr("Could I get a wake-up call?", "모닝콜 부탁드려도 될까요?"),
    ConvExpr("At six in the morning.", "아침 여섯 시에요"),
    ConvExpr("I locked myself out.", "방에 못 들어가요"),
    ConvExpr("Could you open my door?", "문 좀 열어 주시겠어요?"),
    ConvExpr("I left my key inside.", "키를 안에 두고 나왔어요"),
    ConvExpr("Where is the ice machine?", "제빙기가 어디에 있어요?"),
    ConvExpr("Is there a laundry service?", "세탁 서비스 있어요?"),
    ConvExpr("Could I get an iron?", "다리미 빌릴 수 있을까요?"),
    ConvExpr("Do you have an adapter?", "어댑터 있어요?"),
    ConvExpr("Could you call a taxi?", "택시 좀 불러 주시겠어요?"),
    ConvExpr("What's a good restaurant nearby?", "근처에 괜찮은 식당 있어요?"),
    ConvExpr("Could you recommend something?", "추천해 주실 수 있어요?"),
    ConvExpr("How far is downtown?", "시내까지 얼마나 멀어요?"),
    ConvExpr("Is it safe to walk?", "걸어가도 안전해요?"),
    ConvExpr("Do you have a map?", "지도 있어요?"),
    ConvExpr("Could you mark it here?", "여기에 표시해 주시겠어요?"),
    ConvExpr("I'd like to extend my stay.", "숙박을 연장하고 싶어요"),
    ConvExpr("One more night, please.", "하룻밤 더 부탁해요"),
    ConvExpr("Is that room still available?", "그 방 아직 가능한가요?"),
    ConvExpr("I'd like to check out now.", "지금 체크아웃할게요"),
    ConvExpr("Could I have the bill?", "계산서 주시겠어요?"),
    ConvExpr("What is this charge for?", "이 요금은 뭐예요?"),
    ConvExpr("I didn't use the minibar.", "미니바는 안 썼어요"),
    ConvExpr("There must be a mistake.", "뭔가 잘못된 것 같아요"),
    ConvExpr("Could you check again?", "다시 확인해 주시겠어요?"),
    ConvExpr("Can I pay by card?", "카드로 결제되나요?"),
    ConvExpr("Could I get a receipt?", "영수증 주시겠어요?"),
    ConvExpr("The stay was wonderful.", "잘 묵고 갑니다"),
    ConvExpr("Thank you for everything.", "여러모로 감사했어요"),
    ConvExpr("Could you keep my bags?", "가방 좀 맡아 주시겠어요?"),
    ConvExpr("I'll be back at five.", "다섯 시에 돌아올게요"),
    ConvExpr("My flight is this evening.", "제 비행기가 오늘 저녁이에요"),
    ConvExpr("What time does it leave?", "몇 시에 출발해요?"),
    ConvExpr("Could I book it now?", "지금 예약할 수 있을까요?"),
    ConvExpr("I booked through a website.", "사이트로 예약했어요"),
  ],
  // 13번 주제
  [
    ConvExpr("coworker", "동료"),
    ConvExpr("manager", "관리자"),
    ConvExpr("deadline", "마감일"),
    ConvExpr("meeting room", "회의실"),
    ConvExpr("overtime", "야근"),
    ConvExpr("day off", "휴무"),
    ConvExpr("project", "프로젝트"),
    ConvExpr("report", "보고서"),
    ConvExpr("schedule", "일정"),
    ConvExpr("task", "업무"),
    ConvExpr("budget", "예산"),
    ConvExpr("client", "고객사"),
    ConvExpr("team leader", "팀장"),
    ConvExpr("business trip", "출장"),
    ConvExpr("raise", "임금 인상"),
    ConvExpr("promotion", "승진"),
    ConvExpr("resume", "이력서"),
    ConvExpr("interview", "면접"),
    ConvExpr("contract", "계약"),
    ConvExpr("paycheck", "급여"),
    ConvExpr("Nice to work with you.", "같이 일하게 되어 반가워요"),
    ConvExpr("What do you do exactly?", "정확히 무슨 일 하세요?"),
    ConvExpr("I work in marketing.", "마케팅 일 해요"),
    ConvExpr("I've been here two years.", "여기서 2년 일했어요"),
    ConvExpr("Which team are you on?", "어느 팀이세요?"),
    ConvExpr("Who is your manager?", "팀장님이 누구세요?"),
    ConvExpr("Welcome to the team.", "팀에 오신 걸 환영해요"),
    ConvExpr("How was your weekend?", "주말 어떻게 보냈어요?"),
    ConvExpr("Busy morning today?", "오늘 아침 바빴어요?"),
    ConvExpr("Do you have a minute?", "잠깐 시간 있으세요?"),
    ConvExpr("Can we talk later?", "나중에 얘기할 수 있을까요?"),
    ConvExpr("I'm swamped right now.", "지금 너무 바빠요"),
    ConvExpr("I'll get back to you.", "다시 연락드릴게요"),
    ConvExpr("Let me check my calendar.", "일정 좀 확인해 볼게요"),
    ConvExpr("Are you free at two?", "두 시에 시간 되세요?"),
    ConvExpr("Let's set up a meeting.", "회의 잡읍시다"),
    ConvExpr("Can we push it back?", "좀 미룰 수 있을까요?"),
    ConvExpr("Does Tuesday work for you?", "화요일 괜찮으세요?"),
    ConvExpr("I'll send an invite.", "초대 보낼게요"),
    ConvExpr("The meeting starts soon.", "회의 곧 시작해요"),
    ConvExpr("I'll be five minutes late.", "5분 정도 늦어요"),
    ConvExpr("Can you join the call?", "회의 참석할 수 있어요?"),
    ConvExpr("Let's get started.", "시작합시다"),
    ConvExpr("Could you share your screen?", "화면 공유해 주시겠어요?"),
    ConvExpr("I can't hear you well.", "잘 안 들려요"),
    ConvExpr("You're on mute.", "음소거 되어 있어요"),
    ConvExpr("Let me take some notes.", "메모 좀 할게요"),
    ConvExpr("Any questions so far?", "여기까지 질문 있으세요?"),
    ConvExpr("What's the deadline?", "마감이 언제예요?"),
    ConvExpr("When is this due?", "이거 언제까지예요?"),
    ConvExpr("It's due on Friday.", "금요일까지예요"),
    ConvExpr("Can we extend the deadline?", "마감을 연장할 수 있을까요?"),
    ConvExpr("I need more time.", "시간이 더 필요해요"),
    ConvExpr("I'll have it by tomorrow.", "내일까지 드릴게요"),
    ConvExpr("It's almost finished.", "거의 다 됐어요"),
    ConvExpr("I'm still working on it.", "아직 작업 중이에요"),
    ConvExpr("I'll prioritize this.", "이걸 먼저 할게요"),
    ConvExpr("Sorry for the delay.", "늦어서 죄송해요"),
    ConvExpr("Could you take a look?", "한번 봐 주시겠어요?"),
    ConvExpr("I'd like your feedback.", "의견을 듣고 싶어요"),
    ConvExpr("Looks good to me.", "제가 보기엔 괜찮아요"),
    ConvExpr("A few small changes.", "작은 수정 몇 개요"),
    ConvExpr("Could you fix this part?", "이 부분 고쳐 주시겠어요?"),
    ConvExpr("I'll revise it today.", "오늘 수정할게요"),
    ConvExpr("Please review the draft.", "초안을 검토해 주세요"),
    ConvExpr("I've attached the file.", "파일을 첨부했어요"),
    ConvExpr("Did you get my email?", "제 메일 받으셨어요?"),
    ConvExpr("I'll forward it to you.", "전달해 드릴게요"),
    ConvExpr("Could you cc me?", "참조로 넣어 주시겠어요?"),
    ConvExpr("Let's split the work.", "일을 나눠서 해요"),
    ConvExpr("I'll handle that part.", "그 부분은 제가 할게요"),
    ConvExpr("Can you cover for me?", "저 대신 좀 맡아 주실래요?"),
    ConvExpr("I'll back you up.", "제가 도와드릴게요"),
    ConvExpr("Thanks for the help.", "도와줘서 고마워요"),
    ConvExpr("I owe you one.", "신세 졌어요"),
    ConvExpr("Who is in charge here?", "여기 담당이 누구예요?"),
    ConvExpr("I'll ask my manager.", "팀장님께 여쭤볼게요"),
    ConvExpr("Let me double-check that.", "다시 한번 확인해 볼게요"),
    ConvExpr("That's not my call.", "제가 정할 일은 아니에요"),
    ConvExpr("We need to decide today.", "오늘 결정해야 해요"),
    ConvExpr("Let's keep it simple.", "간단하게 갑시다"),
    ConvExpr("I'm taking a day off.", "하루 휴가 내요"),
    ConvExpr("I'll be out next week.", "다음 주에 자리 비워요"),
    ConvExpr("I'm working from home.", "재택근무 중이에요"),
    ConvExpr("I'm on a business trip.", "출장 중이에요"),
    ConvExpr("Back in the office Monday.", "월요일에 사무실로 돌아와요"),
    ConvExpr("I'm heading out now.", "지금 나갈게요"),
    ConvExpr("See you tomorrow morning.", "내일 아침에 봬요"),
    ConvExpr("Have a good evening.", "좋은 저녁 보내세요"),
    ConvExpr("I have to work late.", "늦게까지 일해야 해요"),
    ConvExpr("The deadline got moved up.", "마감이 앞당겨졌어요"),
    ConvExpr("We're behind schedule.", "일정이 밀렸어요"),
    ConvExpr("Let's catch up quickly.", "간단히 상황 공유해요"),
    ConvExpr("The client changed the scope.", "고객사가 범위를 바꿨어요"),
    ConvExpr("That will cost extra.", "그건 비용이 더 들어요"),
    ConvExpr("It's over our budget.", "예산을 넘어요"),
    ConvExpr("Let's find a middle ground.", "절충안을 찾아봐요"),
    ConvExpr("I'll follow up with them.", "제가 후속 연락할게요"),
    ConvExpr("Keep me posted, please.", "진행 상황 알려 주세요"),
    ConvExpr("I'll keep you in the loop.", "계속 공유해 드릴게요"),
  ],
  // 14번 주제
  [
    ConvExpr("phone call", "전화 통화"),
    ConvExpr("voicemail", "음성 메시지"),
    ConvExpr("text message", "문자 메시지"),
    ConvExpr("missed call", "부재중 전화"),
    ConvExpr("speaker phone", "스피커폰"),
    ConvExpr("signal", "신호"),
    ConvExpr("battery", "배터리"),
    ConvExpr("charger", "충전기"),
    ConvExpr("inbox", "받은 편지함"),
    ConvExpr("attachment", "첨부 파일"),
    ConvExpr("subject line", "제목 줄"),
    ConvExpr("reply", "답장"),
    ConvExpr("sender", "보낸 사람"),
    ConvExpr("group chat", "단체 대화방"),
    ConvExpr("notification", "알림"),
    ConvExpr("contact", "연락처"),
    ConvExpr("video call", "영상 통화"),
    ConvExpr("conference call", "다자 통화"),
    ConvExpr("extension", "내선 번호"),
    ConvExpr("hold", "대기"),
    ConvExpr("Hello, this is Mina.", "여보세요, 저 미나예요"),
    ConvExpr("Who's calling, please?", "전화 주신 분이 누구세요?"),
    ConvExpr("May I speak to Tom?", "톰 씨 좀 바꿔 주시겠어요?"),
    ConvExpr("Speaking.", "접니다"),
    ConvExpr("Just a moment, please.", "잠시만 기다려 주세요"),
    ConvExpr("I'll put you through.", "연결해 드릴게요"),
    ConvExpr("Please hold the line.", "끊지 말고 기다려 주세요"),
    ConvExpr("He's not available now.", "지금 자리에 안 계세요"),
    ConvExpr("She's in a meeting.", "회의 중이세요"),
    ConvExpr("Can I take a message?", "메시지 남겨 드릴까요?"),
    ConvExpr("Could you take a message?", "메시지 좀 전해 주시겠어요?"),
    ConvExpr("Please tell him I called.", "전화했다고 전해 주세요"),
    ConvExpr("I'll call back later.", "나중에 다시 걸게요"),
    ConvExpr("When is a good time?", "언제가 괜찮으세요?"),
    ConvExpr("Could you call me back?", "다시 전화해 주시겠어요?"),
    ConvExpr("What's your number?", "전화번호가 어떻게 되세요?"),
    ConvExpr("Let me write that down.", "받아 적을게요"),
    ConvExpr("Could you repeat the number?", "번호를 다시 불러 주시겠어요?"),
    ConvExpr("Sorry, wrong number.", "죄송해요, 잘못 걸었어요"),
    ConvExpr("The line is busy.", "통화 중이에요"),
    ConvExpr("I can barely hear you.", "거의 안 들려요"),
    ConvExpr("The signal is bad here.", "여기 신호가 안 좋아요"),
    ConvExpr("Can you hear me now?", "지금은 들리세요?"),
    ConvExpr("We got cut off.", "통화가 끊겼어요"),
    ConvExpr("Let me call you back.", "제가 다시 걸게요"),
    ConvExpr("My battery is dying.", "배터리가 없어요"),
    ConvExpr("I'm running out of battery.", "배터리가 거의 없어요"),
    ConvExpr("Let's switch to video.", "영상 통화로 바꿔요"),
    ConvExpr("I'll send you the link.", "링크 보내 드릴게요"),
    ConvExpr("Are you on your phone?", "지금 전화 되세요?"),
    ConvExpr("Is now a good time?", "지금 통화 괜찮으세요?"),
    ConvExpr("Can I call you later?", "나중에 전화해도 될까요?"),
    ConvExpr("I'll text you the address.", "주소 문자로 보낼게요"),
    ConvExpr("Did you get my text?", "제 문자 받으셨어요?"),
    ConvExpr("Sorry for the late reply.", "답장이 늦어서 죄송해요"),
    ConvExpr("I just saw your message.", "이제야 메시지 봤어요"),
    ConvExpr("I'll get back to you soon.", "곧 답 드릴게요"),
    ConvExpr("Let me know either way.", "어느 쪽이든 알려 주세요"),
    ConvExpr("Sounds good, see you then.", "좋아요, 그때 봬요"),
    ConvExpr("Thanks for letting me know.", "알려 주셔서 고마워요"),
    ConvExpr("I'm on my way.", "가는 중이에요"),
    ConvExpr("Running a little late.", "조금 늦어요"),
    ConvExpr("Be there in ten.", "10분 뒤에 도착해요"),
    ConvExpr("Where are you now?", "지금 어디예요?"),
    ConvExpr("Call me when you arrive.", "도착하면 전화해요"),
    ConvExpr("I'll ping you later.", "나중에 연락할게요"),
    ConvExpr("Let's move this to chat.", "채팅으로 옮겨요"),
    ConvExpr("I added you to the group.", "단체방에 초대했어요"),
    ConvExpr("Mute the group chat.", "단체방 알림을 꺼요"),
    ConvExpr("I'll share the file here.", "여기에 파일 공유할게요"),
    ConvExpr("Please check your inbox.", "받은 편지함 확인해 주세요"),
    ConvExpr("I sent it this morning.", "오늘 아침에 보냈어요"),
    ConvExpr("It might be in spam.", "스팸함에 있을 수도 있어요"),
    ConvExpr("Could you resend it?", "다시 보내 주시겠어요?"),
    ConvExpr("The attachment didn't open.", "첨부 파일이 안 열려요"),
    ConvExpr("Try a different format.", "다른 형식으로 해 보세요"),
    ConvExpr("I'll send a PDF instead.", "대신 피디에프로 보낼게요"),
    ConvExpr("Thanks for the quick reply.", "빠른 답장 고마워요"),
    ConvExpr("I appreciate your help.", "도와주셔서 감사해요"),
    ConvExpr("Please let me know soon.", "빨리 알려 주세요"),
    ConvExpr("Looking forward to your reply.", "답장 기다릴게요"),
    ConvExpr("Feel free to reach out.", "편하게 연락 주세요"),
    ConvExpr("Reply all, please.", "전체 답장 해 주세요"),
    ConvExpr("Don't reply all.", "전체 답장은 하지 마세요"),
    ConvExpr("I'll loop in my manager.", "팀장님도 참조할게요"),
    ConvExpr("Adding Sara to this thread.", "이 메일에 사라를 추가해요"),
    ConvExpr("Per my last email.", "지난 메일에서 말씀드린 대로요"),
    ConvExpr("As discussed on the phone.", "통화에서 말씀드린 대로요"),
    ConvExpr("Following up on my request.", "요청드린 건 다시 여쭤요"),
    ConvExpr("Just checking in on this.", "진행 상황 여쭤봐요"),
    ConvExpr("Any update on this?", "진행된 게 있나요?"),
    ConvExpr("Sorry to chase you.", "재촉해서 죄송해요"),
    ConvExpr("No rush at all.", "전혀 급하지 않아요"),
    ConvExpr("Whenever you get a chance.", "시간 되실 때요"),
    ConvExpr("I'll confirm by email.", "메일로 확정해 드릴게요"),
    ConvExpr("Please confirm receipt.", "수신 확인 부탁드려요"),
    ConvExpr("The details are attached.", "자세한 내용은 첨부했어요"),
    ConvExpr("Let me summarize the call.", "통화 내용을 정리할게요"),
    ConvExpr("I'll send meeting notes.", "회의록 보내 드릴게요"),
    ConvExpr("Could you put it in writing?", "문서로 남겨 주시겠어요?"),
  ],
  // 15번 주제
  [
    ConvExpr("headache", "두통"),
    ConvExpr("fever", "열"),
    ConvExpr("cough", "기침"),
    ConvExpr("sore throat", "인후통"),
    ConvExpr("runny nose", "콧물"),
    ConvExpr("stomachache", "복통"),
    ConvExpr("back pain", "허리 통증"),
    ConvExpr("toothache", "치통"),
    ConvExpr("rash", "발진"),
    ConvExpr("nausea", "메스꺼움"),
    ConvExpr("allergy", "알레르기"),
    ConvExpr("prescription", "처방전"),
    ConvExpr("pharmacy", "약국"),
    ConvExpr("painkiller", "진통제"),
    ConvExpr("antibiotics", "항생제"),
    ConvExpr("bandage", "붕대"),
    ConvExpr("vitamin", "비타민"),
    ConvExpr("appointment", "진료 예약"),
    ConvExpr("insurance", "보험"),
    ConvExpr("I don't feel well.", "몸이 안 좋아요"),
    ConvExpr("I think I'm sick.", "아픈 것 같아요"),
    ConvExpr("My throat is sore.", "목이 아파요"),
    ConvExpr("I've been coughing.", "기침을 계속해요"),
    ConvExpr("My stomach hurts.", "배가 아파요"),
    ConvExpr("My back hurts a lot.", "허리가 많이 아파요"),
    ConvExpr("It hurts right here.", "여기가 아파요"),
    ConvExpr("It hurts when I move.", "움직이면 아파요"),
    ConvExpr("I feel nauseous.", "속이 메스꺼워요"),
    ConvExpr("I can't sleep well.", "잠을 잘 못 자요"),
    ConvExpr("I have no appetite.", "입맛이 없어요"),
    ConvExpr("I'm very tired lately.", "요즘 너무 피곤해요"),
    ConvExpr("I'd like to see a doctor.", "진료를 받고 싶어요"),
    ConvExpr("Do I need an appointment?", "예약해야 하나요?"),
    ConvExpr("Can I come in today?", "오늘 갈 수 있을까요?"),
    ConvExpr("Is there an opening tomorrow?", "내일 자리 있나요?"),
    ConvExpr("I'd like to book a checkup.", "건강검진 예약하고 싶어요"),
    ConvExpr("This is my first visit.", "처음 방문이에요"),
    ConvExpr("Do you have insurance?", "보험 있으세요?"),
    ConvExpr("Here is my insurance card.", "여기 보험증이에요"),
    ConvExpr("What seems to be the problem?", "어디가 불편하세요?"),
    ConvExpr("How long has this lasted?", "얼마나 됐어요?"),
    ConvExpr("It started three days ago.", "사흘 전에 시작됐어요"),
    ConvExpr("It's been about a week.", "일주일쯤 됐어요"),
    ConvExpr("It comes and goes.", "나았다 아팠다 해요"),
    ConvExpr("It's getting worse.", "점점 심해져요"),
    ConvExpr("It's a little better today.", "오늘은 좀 나아요"),
    ConvExpr("Does it hurt here?", "여기 아프세요?"),
    ConvExpr("It's about a six.", "6점 정도요"),
    ConvExpr("Let me check your temperature.", "체온을 재 볼게요"),
    ConvExpr("Please take a deep breath.", "숨을 크게 쉬어 보세요"),
    ConvExpr("Open your mouth, please.", "입을 벌려 주세요"),
    ConvExpr("Roll up your sleeve.", "소매를 걷어 주세요"),
    ConvExpr("I'll take your blood pressure.", "혈압을 잴게요"),
    ConvExpr("We need a blood test.", "혈액 검사가 필요해요"),
    ConvExpr("Do I need an X-ray?", "엑스레이 찍어야 하나요?"),
    ConvExpr("When will results come?", "결과는 언제 나와요?"),
    ConvExpr("Is it serious?", "심각한가요?"),
    ConvExpr("It's nothing serious.", "심각한 건 아니에요"),
    ConvExpr("You have a bad cold.", "심한 감기예요"),
    ConvExpr("It might be the flu.", "독감일 수도 있어요"),
    ConvExpr("You need plenty of rest.", "푹 쉬셔야 해요"),
    ConvExpr("Drink lots of water.", "물을 많이 드세요"),
    ConvExpr("Stay home for a few days.", "며칠 집에 계세요"),
    ConvExpr("I'll write a prescription.", "처방전을 써 드릴게요"),
    ConvExpr("Take this twice a day.", "이걸 하루 두 번 드세요"),
    ConvExpr("Take it after meals.", "식후에 드세요"),
    ConvExpr("Take it before bed.", "자기 전에 드세요"),
    ConvExpr("Finish all the medicine.", "약을 다 드세요"),
    ConvExpr("Any side effects?", "부작용이 있나요?"),
    ConvExpr("It may make you sleepy.", "졸릴 수 있어요"),
    ConvExpr("Don't drink alcohol with it.", "이 약과 술은 안 돼요"),
    ConvExpr("I'm allergic to penicillin.", "페니실린 알레르기가 있어요"),
    ConvExpr("Is there another option?", "다른 약은 없을까요?"),
    ConvExpr("I'm taking other medication.", "다른 약을 먹고 있어요"),
    ConvExpr("Let me check for interactions.", "약물 상호작용을 확인할게요"),
    ConvExpr("Come back in one week.", "일주일 뒤에 다시 오세요"),
    ConvExpr("Call if it gets worse.", "심해지면 전화 주세요"),
    ConvExpr("Where is the nearest pharmacy?", "가장 가까운 약국이 어디예요?"),
    ConvExpr("I have a prescription to fill.", "처방전 약을 받으려고요"),
    ConvExpr("How long will it take?", "얼마나 걸려요?"),
    ConvExpr("Is there a generic version?", "복제약도 있나요?"),
    ConvExpr("How much does it cost?", "비용이 얼마예요?"),
    ConvExpr("Does insurance cover this?", "보험 적용되나요?"),
    ConvExpr("Do I need a receipt?", "영수증 필요하세요?"),
    ConvExpr("Do you have cold medicine?", "감기약 있어요?"),
    ConvExpr("Something for a headache?", "두통약 있을까요?"),
    ConvExpr("Is this safe for children?", "이거 아이가 먹어도 되나요?"),
    ConvExpr("How often can I take it?", "얼마나 자주 먹어요?"),
    ConvExpr("Don't exceed the dose.", "정해진 양을 넘기지 마세요"),
    ConvExpr("I need a doctor's note.", "진단서가 필요해요"),
    ConvExpr("For my workplace, please.", "회사 제출용이에요"),
    ConvExpr("I hurt my ankle.", "발목을 다쳤어요"),
    ConvExpr("I fell down the stairs.", "계단에서 넘어졌어요"),
    ConvExpr("I think it's sprained.", "삔 것 같아요"),
    ConvExpr("Can you move your fingers?", "손가락 움직여지세요?"),
    ConvExpr("We'll put on a cast.", "깁스를 할게요"),
    ConvExpr("Keep it elevated.", "높이 올려 두세요"),
    ConvExpr("Put ice on it.", "얼음을 대세요"),
    ConvExpr("I need to see a dentist.", "치과에 가야 해요"),
    ConvExpr("This tooth is killing me.", "이 이가 너무 아파요"),
  ],
  // 16번 주제
  [
    ConvExpr("laundry", "빨래"),
    ConvExpr("dishes", "설거지"),
    ConvExpr("vacuum", "청소기"),
    ConvExpr("trash", "쓰레기"),
    ConvExpr("recycling", "재활용"),
    ConvExpr("sink", "싱크대"),
    ConvExpr("stove", "가스레인지"),
    ConvExpr("fridge", "냉장고"),
    ConvExpr("closet", "옷장"),
    ConvExpr("drawer", "서랍"),
    ConvExpr("mop", "대걸레"),
    ConvExpr("broom", "빗자루"),
    ConvExpr("detergent", "세제"),
    ConvExpr("leak", "누수"),
    ConvExpr("plumber", "배관공"),
    ConvExpr("landlord", "집주인"),
    ConvExpr("rent", "월세"),
    ConvExpr("utility bill", "공과금"),
    ConvExpr("neighbor", "이웃"),
    ConvExpr("mailbox", "우편함"),
    ConvExpr("I need to do laundry.", "빨래해야 해요"),
    ConvExpr("The laundry is piling up.", "빨래가 쌓여 가요"),
    ConvExpr("Could you fold the clothes?", "빨래 좀 개 주시겠어요?"),
    ConvExpr("I'll wash the dishes.", "제가 설거지할게요"),
    ConvExpr("The dishes can wait.", "설거지는 나중에 해도 돼요"),
    ConvExpr("It's your turn tonight.", "오늘 밤은 당신 차례예요"),
    ConvExpr("I'll take out the trash.", "쓰레기 버리고 올게요"),
    ConvExpr("Trash day is Tuesday.", "쓰레기 버리는 날은 화요일이에요"),
    ConvExpr("Where does this go?", "이건 어디에 버려요?"),
    ConvExpr("That's recycling.", "그건 재활용이에요"),
    ConvExpr("Let's clean up a bit.", "좀 치웁시다"),
    ConvExpr("The place is a mess.", "집이 엉망이에요"),
    ConvExpr("I'll vacuum the floor.", "바닥 청소기 돌릴게요"),
    ConvExpr("Could you wipe the table?", "식탁 좀 닦아 주시겠어요?"),
    ConvExpr("I'm making the bed.", "침대 정리 중이에요"),
    ConvExpr("Put it back where it was.", "원래 자리에 두세요"),
    ConvExpr("Don't leave it there.", "거기 두지 마세요"),
    ConvExpr("I can't find my keys.", "열쇠를 못 찾겠어요"),
    ConvExpr("Check the drawer.", "서랍을 확인해 봐요"),
    ConvExpr("It's in the closet.", "옷장 안에 있어요"),
    ConvExpr("We're out of milk.", "우유가 다 떨어졌어요"),
    ConvExpr("Add it to the list.", "목록에 추가해요"),
    ConvExpr("I'll stop by the store.", "가게에 들를게요"),
    ConvExpr("Do we need anything else?", "더 필요한 거 있어요?"),
    ConvExpr("The fridge is empty.", "냉장고가 텅 비었어요"),
    ConvExpr("This food went bad.", "이 음식 상했어요"),
    ConvExpr("Check the expiration date.", "유통기한을 확인해 봐요"),
    ConvExpr("I'll cook tonight.", "오늘 저녁은 제가 할게요"),
    ConvExpr("Let's order in instead.", "그냥 시켜 먹어요"),
    ConvExpr("Dinner is ready.", "저녁 다 됐어요"),
    ConvExpr("The sink is leaking.", "싱크대에서 물이 새요"),
    ConvExpr("The drain is clogged.", "배수구가 막혔어요"),
    ConvExpr("We should call a plumber.", "배관공을 불러야겠어요"),
    ConvExpr("The light bulb burned out.", "전구가 나갔어요"),
    ConvExpr("I'll change the bulb.", "전구 갈게요"),
    ConvExpr("The door won't lock.", "문이 안 잠겨요"),
    ConvExpr("Something smells funny.", "뭔가 이상한 냄새가 나요"),
    ConvExpr("Did you leave the gas on?", "가스 켜 두셨어요?"),
    ConvExpr("Turn off the lights.", "불 좀 꺼 주세요"),
    ConvExpr("Close the window, please.", "창문 닫아 주세요"),
    ConvExpr("It's freezing in here.", "여기 너무 추워요"),
    ConvExpr("Turn up the heat.", "난방 좀 올려요"),
    ConvExpr("The heating bill is huge.", "난방비가 엄청 나왔어요"),
    ConvExpr("Our rent is due Friday.", "월세가 금요일까지예요"),
    ConvExpr("I paid the electric bill.", "전기 요금 냈어요"),
    ConvExpr("The internet is down again.", "인터넷이 또 끊겼어요"),
    ConvExpr("I'll call the provider.", "통신사에 전화할게요"),
    ConvExpr("Someone is at the door.", "누가 문 앞에 왔어요"),
    ConvExpr("It's just a delivery.", "그냥 택배예요"),
    ConvExpr("A package came for you.", "택배 왔어요"),
    ConvExpr("I'll leave it by the door.", "문 앞에 둘게요"),
    ConvExpr("Did you check the mail?", "우편함 확인했어요?"),
    ConvExpr("It's mostly junk mail.", "대부분 광고 우편이에요"),
    ConvExpr("I need to pay this bill.", "이 고지서를 내야 해요"),
    ConvExpr("It's due next week.", "다음 주까지예요"),
    ConvExpr("I set up auto-pay.", "자동 이체를 걸어 뒀어요"),
    ConvExpr("Let's split the chores.", "집안일을 나눠서 해요"),
    ConvExpr("I did it last time.", "지난번엔 제가 했어요"),
    ConvExpr("That's not fair.", "그건 공평하지 않아요"),
    ConvExpr("Fine, I'll do it.", "알았어요, 제가 할게요"),
    ConvExpr("Thanks for helping out.", "도와줘서 고마워요"),
    ConvExpr("I'll handle the rest.", "나머지는 제가 할게요"),
    ConvExpr("We need to declutter.", "물건을 좀 정리해야 해요"),
    ConvExpr("Let's donate these clothes.", "이 옷들은 기부해요"),
    ConvExpr("Throw away what's broken.", "망가진 건 버려요"),
    ConvExpr("This still works fine.", "이건 아직 멀쩡해요"),
    ConvExpr("Keep it for now.", "일단 두세요"),
    ConvExpr("I'm moving next month.", "다음 달에 이사해요"),
    ConvExpr("We need moving boxes.", "이사 박스가 필요해요"),
    ConvExpr("Label every box.", "상자마다 이름을 적어요"),
    ConvExpr("The movers come at nine.", "이삿짐센터가 아홉 시에 와요"),
    ConvExpr("Be careful with that.", "그거 조심해서 다뤄요"),
    ConvExpr("It's heavier than it looks.", "보기보다 무거워요"),
    ConvExpr("Could you hold this?", "이것 좀 들어 주시겠어요?"),
    ConvExpr("Where should we put it?", "어디에 놓을까요?"),
    ConvExpr("A little to the left.", "왼쪽으로 조금만요"),
    ConvExpr("That looks perfect.", "딱 좋아요"),
    ConvExpr("My neighbor is very loud.", "이웃이 너무 시끄러워요"),
    ConvExpr("The music went on late.", "음악 소리가 늦게까지 났어요"),
    ConvExpr("I'll talk to them politely.", "정중하게 얘기해 볼게요"),
  ],
  // 17번 주제
  [
    ConvExpr("hobby", "취미"),
    ConvExpr("free time", "여가 시간"),
    ConvExpr("workout", "운동"),
    ConvExpr("gym membership", "헬스장 회원권"),
    ConvExpr("jogging", "조깅"),
    ConvExpr("hiking", "등산"),
    ConvExpr("yoga", "요가"),
    ConvExpr("swimming", "수영"),
    ConvExpr("cycling", "자전거 타기"),
    ConvExpr("camping", "캠핑"),
    ConvExpr("fishing", "낚시"),
    ConvExpr("gardening", "원예"),
    ConvExpr("painting", "그림 그리기"),
    ConvExpr("photography", "사진 찍기"),
    ConvExpr("baking", "베이킹"),
    ConvExpr("knitting", "뜨개질"),
    ConvExpr("board game", "보드게임"),
    ConvExpr("video game", "비디오 게임"),
    ConvExpr("concert", "콘서트"),
    ConvExpr("museum", "박물관"),
    ConvExpr("What do you do for fun?", "재미로 뭘 하세요?"),
    ConvExpr("Do you have any hobbies?", "취미 있으세요?"),
    ConvExpr("I like taking photos.", "사진 찍는 걸 좋아해요"),
    ConvExpr("I'm into hiking lately.", "요즘 등산에 빠졌어요"),
    ConvExpr("I picked up a new hobby.", "새 취미를 시작했어요"),
    ConvExpr("How long have you done that?", "얼마나 하셨어요?"),
    ConvExpr("Since I was a kid.", "어릴 때부터요"),
    ConvExpr("I'm still a beginner.", "아직 초보예요"),
    ConvExpr("You should try it.", "한번 해 보세요"),
    ConvExpr("It's really relaxing.", "정말 마음이 편해져요"),
    ConvExpr("I work out three times weekly.", "일주일에 세 번 운동해요"),
    ConvExpr("I go to the gym early.", "헬스장에 일찍 가요"),
    ConvExpr("I prefer running outside.", "밖에서 뛰는 걸 더 좋아해요"),
    ConvExpr("How far do you run?", "얼마나 뛰세요?"),
    ConvExpr("About five kilometers.", "5킬로미터쯤요"),
    ConvExpr("I'm training for a race.", "대회 준비 중이에요"),
    ConvExpr("My legs are so sore.", "다리가 너무 아파요"),
    ConvExpr("I skipped my workout today.", "오늘 운동을 걸렀어요"),
    ConvExpr("I need to get in shape.", "몸을 좀 만들어야 해요"),
    ConvExpr("Want to join me?", "같이 하실래요?"),
    ConvExpr("Do you play any sports?", "운동 하는 거 있어요?"),
    ConvExpr("I play tennis on weekends.", "주말에 테니스 쳐요"),
    ConvExpr("I'm not very athletic.", "운동은 잘 못해요"),
    ConvExpr("Who's your favorite team?", "어느 팀 좋아하세요?"),
    ConvExpr("Did you watch the game?", "그 경기 보셨어요?"),
    ConvExpr("What a close match.", "정말 아슬아슬한 경기였어요"),
    ConvExpr("We won in the last minute.", "마지막에 이겼어요"),
    ConvExpr("They lost again.", "또 졌어요"),
    ConvExpr("I can't believe that goal.", "그 골 정말 대단했어요"),
    ConvExpr("Let's watch it together.", "같이 봐요"),
    ConvExpr("I love action movies.", "액션 영화를 좋아해요"),
    ConvExpr("I'm not into horror.", "공포물은 별로예요"),
    ConvExpr("Have you seen that film?", "그 영화 보셨어요?"),
    ConvExpr("It got great reviews.", "평이 아주 좋아요"),
    ConvExpr("The ending surprised me.", "결말이 놀라웠어요"),
    ConvExpr("No spoilers, please.", "스포일러는 하지 마세요"),
    ConvExpr("I'll wait for streaming.", "스트리밍으로 볼게요"),
    ConvExpr("Let's go to the movies.", "영화 보러 가요"),
    ConvExpr("What time is the show?", "상영이 몇 시예요?"),
    ConvExpr("What music do you listen to?", "무슨 음악 들으세요?"),
    ConvExpr("I listen to everything.", "다 가리지 않고 들어요"),
    ConvExpr("Who is your favorite artist?", "좋아하는 가수가 누구예요?"),
    ConvExpr("I saw them live once.", "공연으로 한 번 봤어요"),
    ConvExpr("The concert was amazing.", "콘서트가 정말 좋았어요"),
    ConvExpr("Tickets sold out fast.", "표가 금방 매진됐어요"),
    ConvExpr("I play the guitar a little.", "기타를 조금 쳐요"),
    ConvExpr("I'm learning the piano.", "피아노를 배우고 있어요"),
    ConvExpr("I practice every evening.", "매일 저녁 연습해요"),
    ConvExpr("Do you read much?", "책 많이 읽으세요?"),
    ConvExpr("I'm halfway through it.", "절반쯤 읽었어요"),
    ConvExpr("It's hard to put down.", "손에서 놓기 어려워요"),
    ConvExpr("Can you recommend a book?", "책 좀 추천해 주실래요?"),
    ConvExpr("I prefer audiobooks now.", "요즘은 오디오북이 좋아요"),
    ConvExpr("I listen while commuting.", "출퇴근하면서 들어요"),
    ConvExpr("What are you watching now?", "요즘 뭐 보세요?"),
    ConvExpr("I binged the whole season.", "한 시즌을 몰아 봤어요"),
    ConvExpr("Just one more episode.", "딱 한 편만 더요"),
    ConvExpr("I stayed up too late.", "너무 늦게까지 깨어 있었어요"),
    ConvExpr("We went camping.", "캠핑 갔다 왔어요"),
    ConvExpr("The weather was perfect.", "날씨가 완벽했어요"),
    ConvExpr("We grilled by the lake.", "호숫가에서 구워 먹었어요"),
    ConvExpr("I caught two fish.", "물고기 두 마리 잡았어요"),
    ConvExpr("I fell asleep in the tent.", "텐트에서 잠들었어요"),
    ConvExpr("Let's do it again soon.", "조만간 또 해요"),
    ConvExpr("I started a small garden.", "작은 정원을 시작했어요"),
    ConvExpr("My tomatoes are growing.", "토마토가 자라고 있어요"),
    ConvExpr("I killed my last plant.", "지난번 화분은 죽였어요"),
    ConvExpr("Plants need patience.", "식물엔 인내가 필요해요"),
    ConvExpr("I baked bread yesterday.", "어제 빵을 구웠어요"),
    ConvExpr("It turned out great.", "아주 잘 됐어요"),
    ConvExpr("Want to try some?", "좀 드셔 보실래요?"),
    ConvExpr("I'm learning to cook.", "요리를 배우고 있어요"),
    ConvExpr("I follow online recipes.", "인터넷 레시피를 따라 해요"),
    ConvExpr("Cooking relaxes me.", "요리하면 마음이 편해져요"),
    ConvExpr("I took an art class.", "미술 수업을 들었어요"),
    ConvExpr("I'm not good at drawing.", "그림은 잘 못 그려요"),
    ConvExpr("It's about having fun.", "즐기는 게 중요하죠"),
    ConvExpr("I need a new hobby.", "새 취미가 필요해요"),
    ConvExpr("Any suggestions for me?", "추천해 주실 거 있어요?"),
    ConvExpr("Try something outdoors.", "야외 활동을 해 보세요"),
  ],
  // 18번 주제
  [
    ConvExpr("plan", "계획"),
    ConvExpr("invitation", "초대"),
    ConvExpr("party", "파티"),
    ConvExpr("dinner party", "저녁 모임"),
    ConvExpr("birthday", "생일"),
    ConvExpr("anniversary", "기념일"),
    ConvExpr("wedding", "결혼식"),
    ConvExpr("reunion", "동창회"),
    ConvExpr("housewarming", "집들이"),
    ConvExpr("potluck", "각자 음식 가져오기"),
    ConvExpr("guest list", "초대 손님 명단"),
    ConvExpr("venue", "장소"),
    ConvExpr("reservation time", "예약 시간"),
    ConvExpr("schedule conflict", "일정 겹침"),
    ConvExpr("rain check", "다음 기회"),
    ConvExpr("RSVP", "참석 회신"),
    ConvExpr("host", "주최자"),
    ConvExpr("gathering", "모임"),
    ConvExpr("get-together", "가벼운 모임"),
    ConvExpr("catch-up", "안부 나누기"),
    ConvExpr("Are you free this weekend?", "이번 주말에 시간 있어요?"),
    ConvExpr("What are you doing Saturday?", "토요일에 뭐 해요?"),
    ConvExpr("Do you have plans tonight?", "오늘 밤 계획 있어요?"),
    ConvExpr("Nothing special yet.", "아직 특별한 건 없어요"),
    ConvExpr("I'm free after six.", "여섯 시 이후엔 괜찮아요"),
    ConvExpr("Let's grab dinner sometime.", "언제 저녁 같이 먹어요"),
    ConvExpr("Want to grab coffee?", "커피 한잔할래요?"),
    ConvExpr("How about Friday evening?", "금요일 저녁 어때요?"),
    ConvExpr("Does seven work for you?", "일곱 시 괜찮으세요?"),
    ConvExpr("Let's say eight o'clock.", "여덟 시로 해요"),
    ConvExpr("Where should we meet?", "어디서 만날까요?"),
    ConvExpr("Let's meet at the station.", "역에서 만나요"),
    ConvExpr("I'll meet you there.", "거기서 봬요"),
    ConvExpr("I'll pick you up.", "제가 데리러 갈게요"),
    ConvExpr("Send me the address.", "주소 보내 주세요"),
    ConvExpr("I'd love to come.", "꼭 가고 싶어요"),
    ConvExpr("Count on me.", "저 갈게요"),
    ConvExpr("I'm definitely coming.", "무조건 갈게요"),
    ConvExpr("Sounds great to me.", "저는 좋아요"),
    ConvExpr("Thanks for the invite.", "초대해 줘서 고마워요"),
    ConvExpr("I'll have to check.", "확인해 봐야 해요"),
    ConvExpr("Let me get back to you.", "나중에 알려 드릴게요"),
    ConvExpr("I'll let you know tonight.", "오늘 밤에 알려 드릴게요"),
    ConvExpr("I'm not sure yet.", "아직 확실하지 않아요"),
    ConvExpr("It depends on work.", "일에 따라 달라요"),
    ConvExpr("I can't make it.", "못 갈 것 같아요"),
    ConvExpr("Sorry, I already have plans.", "미안해요, 이미 약속이 있어요"),
    ConvExpr("Maybe another time.", "다음 기회에요"),
    ConvExpr("Can I take a rain check?", "다음으로 미뤄도 될까요?"),
    ConvExpr("I'll join you next time.", "다음엔 꼭 갈게요"),
    ConvExpr("Something came up.", "일이 생겼어요"),
    ConvExpr("Can we reschedule?", "일정을 다시 잡을까요?"),
    ConvExpr("Could we move it up?", "좀 앞당길 수 있을까요?"),
    ConvExpr("Could we push it later?", "좀 늦출 수 있을까요?"),
    ConvExpr("Does Sunday work instead?", "대신 일요일 괜찮아요?"),
    ConvExpr("Any day but Monday.", "월요일만 빼고 아무 때나요"),
    ConvExpr("That works for me.", "저는 괜찮아요"),
    ConvExpr("Let's lock it in.", "그걸로 확정해요"),
    ConvExpr("I'll put it in my calendar.", "제 일정에 넣을게요"),
    ConvExpr("Don't forget about tomorrow.", "내일 잊지 마세요"),
    ConvExpr("See you then.", "그때 봬요"),
    ConvExpr("I'm having a party.", "파티를 열어요"),
    ConvExpr("It's my birthday Saturday.", "토요일이 제 생일이에요"),
    ConvExpr("You're welcome to come.", "오셔도 좋아요"),
    ConvExpr("Bring whoever you want.", "누구든 데려오세요"),
    ConvExpr("Feel free to bring a friend.", "친구 데려오셔도 돼요"),
    ConvExpr("Should I bring anything?", "뭘 좀 가져갈까요?"),
    ConvExpr("Just bring yourself.", "몸만 오세요"),
    ConvExpr("Bring a dish to share.", "나눠 먹을 음식 하나 가져오세요"),
    ConvExpr("I'll bring dessert.", "디저트 가져갈게요"),
    ConvExpr("What's the dress code?", "복장은 어떻게 해요?"),
    ConvExpr("It's pretty casual.", "편하게 입으면 돼요"),
    ConvExpr("Is it a surprise party?", "깜짝 파티예요?"),
    ConvExpr("Don't tell her yet.", "아직 말하지 마세요"),
    ConvExpr("Let's keep it a secret.", "비밀로 해요"),
    ConvExpr("I'll get the cake.", "제가 케이크 가져올게요"),
    ConvExpr("Did everyone RSVP?", "다들 참석 회신했어요?"),
    ConvExpr("About ten people are coming.", "열 명쯤 와요"),
    ConvExpr("The more the merrier.", "많을수록 좋아요"),
    ConvExpr("I'll make a reservation.", "예약할게요"),
    ConvExpr("For four people, please.", "네 명으로 부탁해요"),
    ConvExpr("Under what name?", "누구 이름으로요?"),
    ConvExpr("Should I book a table?", "자리를 예약할까요?"),
    ConvExpr("They're fully booked.", "예약이 다 찼어요"),
    ConvExpr("Let's try another place.", "다른 데로 해 봐요"),
    ConvExpr("Any place is fine.", "아무 데나 괜찮아요"),
    ConvExpr("You choose this time.", "이번엔 당신이 골라요"),
    ConvExpr("I'm running late.", "좀 늦어요"),
    ConvExpr("Start without me.", "먼저 시작하세요"),
    ConvExpr("Save me a seat.", "자리 하나 맡아 주세요"),
    ConvExpr("I just arrived.", "방금 도착했어요"),
    ConvExpr("Where are you sitting?", "어디 앉아 계세요?"),
    ConvExpr("Sorry I'm late.", "늦어서 미안해요"),
    ConvExpr("Traffic was terrible.", "차가 너무 막혔어요"),
    ConvExpr("No worries, you made it.", "괜찮아요, 오셨잖아요"),
    ConvExpr("Thanks for having me.", "초대해 주셔서 감사해요"),
    ConvExpr("I had a great time.", "정말 즐거웠어요"),
    ConvExpr("Let's do this again.", "또 해요"),
    ConvExpr("It's getting late.", "늦었네요"),
    ConvExpr("Text me when you're home.", "집에 도착하면 문자해요"),
  ],
  // 19번 주제
  [
    ConvExpr("opinion", "의견"),
    ConvExpr("agreement", "동의"),
    ConvExpr("disagreement", "이견"),
    ConvExpr("suggestion", "제안"),
    ConvExpr("point of view", "관점"),
    ConvExpr("reason", "이유"),
    ConvExpr("example", "예시"),
    ConvExpr("advantage", "장점"),
    ConvExpr("disadvantage", "단점"),
    ConvExpr("compromise", "타협"),
    ConvExpr("argument", "주장"),
    ConvExpr("fact", "사실"),
    ConvExpr("guess", "추측"),
    ConvExpr("preference", "선호"),
    ConvExpr("decision", "결정"),
    ConvExpr("option", "선택지"),
    ConvExpr("choice", "선택"),
    ConvExpr("doubt", "의심"),
    ConvExpr("concern", "우려"),
    ConvExpr("solution", "해결책"),
    ConvExpr("What do you think?", "어떻게 생각하세요?"),
    ConvExpr("How do you feel about it?", "이거 어떻게 보세요?"),
    ConvExpr("What's your opinion?", "의견이 어떠세요?"),
    ConvExpr("In my opinion, it's fine.", "제 생각엔 괜찮아요"),
    ConvExpr("I think so too.", "저도 그렇게 생각해요"),
    ConvExpr("I feel the same way.", "저도 같은 생각이에요"),
    ConvExpr("That's exactly right.", "딱 맞아요"),
    ConvExpr("You're absolutely right.", "완전히 맞는 말씀이에요"),
    ConvExpr("I couldn't agree more.", "전적으로 동의해요"),
    ConvExpr("Good point.", "좋은 지적이에요"),
    ConvExpr("That makes sense to me.", "저한텐 말이 되네요"),
    ConvExpr("I see what you mean.", "무슨 말인지 알겠어요"),
    ConvExpr("Fair enough.", "그럴 만해요"),
    ConvExpr("I'm with you on that.", "그 점은 저도 같아요"),
    ConvExpr("Exactly my thoughts.", "제 생각과 똑같아요"),
    ConvExpr("I'm not so sure.", "잘 모르겠어요"),
    ConvExpr("I'm not convinced.", "확신이 안 서요"),
    ConvExpr("I have my doubts.", "좀 의심스러워요"),
    ConvExpr("That's one way to see it.", "그렇게 볼 수도 있죠"),
    ConvExpr("I see it differently.", "저는 다르게 봐요"),
    ConvExpr("I have to disagree.", "동의하기 어려워요"),
    ConvExpr("I don't think so.", "그렇게 생각 안 해요"),
    ConvExpr("That's not quite right.", "그건 좀 아닌 것 같아요"),
    ConvExpr("I respectfully disagree.", "죄송하지만 생각이 달라요"),
    ConvExpr("With all due respect.", "말씀드리기 조심스럽지만요"),
    ConvExpr("I understand, but still.", "이해하지만 그래도요"),
    ConvExpr("That's true, however.", "맞아요, 그런데요"),
    ConvExpr("Yes and no.", "맞기도 하고 아니기도 해요"),
    ConvExpr("It depends on the situation.", "상황에 따라 달라요"),
    ConvExpr("There are two sides.", "양쪽 다 이유가 있어요"),
    ConvExpr("Let me explain why.", "이유를 말씀드릴게요"),
    ConvExpr("Here is my reason.", "제 이유는 이래요"),
    ConvExpr("For example, look at this.", "예를 들면 이걸 보세요"),
    ConvExpr("Take this case.", "이 경우를 보세요"),
    ConvExpr("The main advantage is cost.", "가장 큰 장점은 비용이에요"),
    ConvExpr("The downside is time.", "단점은 시간이에요"),
    ConvExpr("It has pros and cons.", "장단점이 있어요"),
    ConvExpr("Let's weigh both sides.", "양쪽을 저울질해 봐요"),
    ConvExpr("What if we tried this?", "이렇게 해 보면 어때요?"),
    ConvExpr("Why don't we start small?", "작게 시작하면 어때요?"),
    ConvExpr("How about another approach?", "다른 방법은 어때요?"),
    ConvExpr("Maybe we should wait.", "좀 기다리는 게 나을 수도요"),
    ConvExpr("I'd suggest asking first.", "먼저 물어보길 권해요"),
    ConvExpr("It might be better to wait.", "기다리는 게 나을 것 같아요"),
    ConvExpr("Have you considered this?", "이건 생각해 보셨어요?"),
    ConvExpr("That's worth considering.", "고려해 볼 만해요"),
    ConvExpr("I hadn't thought of that.", "그건 생각 못 했어요"),
    ConvExpr("You have a point there.", "일리가 있네요"),
    ConvExpr("Give me a moment.", "잠깐만 시간 주세요"),
    ConvExpr("I need more information.", "정보가 더 필요해요"),
    ConvExpr("Where did you hear that?", "그거 어디서 들으셨어요?"),
    ConvExpr("Is that really true?", "그게 정말이에요?"),
    ConvExpr("I read it somewhere.", "어딘가에서 읽었어요"),
    ConvExpr("I'm not certain about that.", "그건 확실하지 않아요"),
    ConvExpr("Let's check the facts.", "사실을 확인해 봐요"),
    ConvExpr("That's just a guess.", "그건 추측일 뿐이에요"),
    ConvExpr("Speaking from experience.", "경험에서 말하자면요"),
    ConvExpr("In my experience, it works.", "제 경험으론 잘 돼요"),
    ConvExpr("It worked for me.", "저한테는 효과가 있었어요"),
    ConvExpr("It may not work here.", "여기선 안 될 수도 있어요"),
    ConvExpr("Every case is different.", "경우마다 달라요"),
    ConvExpr("Let's agree to disagree.", "서로 생각이 다른 걸로 해요"),
    ConvExpr("We can meet halfway.", "중간에서 만나요"),
    ConvExpr("Let's find a compromise.", "타협점을 찾아봐요"),
    ConvExpr("Can we try both ways?", "둘 다 해 볼 수 있을까요?"),
    ConvExpr("I'm open to ideas.", "의견 환영해요"),
    ConvExpr("I'm flexible on this.", "이건 유연하게 갈 수 있어요"),
    ConvExpr("Whatever you prefer.", "원하시는 대로요"),
    ConvExpr("It's up to you.", "당신에게 맡길게요"),
    ConvExpr("I'll go with your choice.", "당신 선택을 따를게요"),
    ConvExpr("I'd rather not.", "그러고 싶지 않아요"),
    ConvExpr("I'd prefer the first option.", "첫 번째가 더 좋아요"),
    ConvExpr("That works better for me.", "그게 저한테 더 맞아요"),
    ConvExpr("Either one is fine.", "둘 다 괜찮아요"),
    ConvExpr("I have no strong feelings.", "특별한 의견은 없어요"),
    ConvExpr("Let's put it to a vote.", "투표로 정해요"),
    ConvExpr("The majority decides.", "다수가 정해요"),
    ConvExpr("Does everyone agree?", "다들 동의하세요?"),
    ConvExpr("Any objections?", "반대 의견 있으세요?"),
    ConvExpr("Speak up if you disagree.", "다르게 생각하면 말씀하세요"),
  ],
  // 20번 주제
  [
    ConvExpr("sit down", "앉다"),
    ConvExpr("stand up", "일어서다"),
    ConvExpr("come in", "들어오다"),
    ConvExpr("go out", "나가다"),
    ConvExpr("turn on", "켜다"),
    ConvExpr("turn off", "끄다"),
    ConvExpr("put on", "입다"),
    ConvExpr("take off", "벗다"),
    ConvExpr("pick up", "집다"),
    ConvExpr("put down", "내려놓다"),
    ConvExpr("look at", "쳐다보다"),
    ConvExpr("look for", "찾다"),
    ConvExpr("wait for", "기다리다"),
    ConvExpr("listen to", "귀 기울이다"),
    ConvExpr("talk about", "이야기하다"),
    ConvExpr("think about", "생각하다"),
    ConvExpr("write down", "적어 두다"),
    ConvExpr("find out", "알아내다"),
    ConvExpr("Get up, it's late.", "일어나요, 늦었어요"),
    ConvExpr("I woke up at six.", "여섯 시에 깼어요"),
    ConvExpr("Please sit down here.", "여기 앉으세요"),
    ConvExpr("Everyone stand up, please.", "모두 일어나 주세요"),
    ConvExpr("Come in and have a seat.", "들어와서 앉으세요"),
    ConvExpr("Let's go out tonight.", "오늘 밤 나가서 놀아요"),
    ConvExpr("Turn on the light.", "불 좀 켜 주세요"),
    ConvExpr("Turn off your phone.", "휴대폰 꺼 주세요"),
    ConvExpr("Put on your coat.", "코트를 입으세요"),
    ConvExpr("Take off your shoes here.", "여기서 신발을 벗으세요"),
    ConvExpr("Pick up the phone.", "전화 좀 받으세요"),
    ConvExpr("Put down that bag.", "그 가방 내려놓으세요"),
    ConvExpr("Look at this picture.", "이 사진 좀 보세요"),
    ConvExpr("I'm looking for my wallet.", "지갑을 찾고 있어요"),
    ConvExpr("Wait for me outside.", "밖에서 기다려요"),
    ConvExpr("Listen to this song.", "이 노래 들어 봐요"),
    ConvExpr("Let's talk about it later.", "나중에 얘기해요"),
    ConvExpr("I'll think about it.", "생각해 볼게요"),
    ConvExpr("Write down your name.", "이름을 적어 주세요"),
    ConvExpr("I'll find out for you.", "제가 알아봐 드릴게요"),
    ConvExpr("turn around", "돌아서다"),
    ConvExpr("come back", "돌아오다"),
    ConvExpr("go back", "되돌아가다"),
    ConvExpr("get in", "타다"),
    ConvExpr("get out", "내리다"),
    ConvExpr("get on", "올라타다"),
    ConvExpr("give up", "포기하다"),
    ConvExpr("grow up", "자라다"),
    ConvExpr("hurry up", "서두르다"),
    ConvExpr("Turn around and look.", "돌아서서 보세요"),
    ConvExpr("I'll come back soon.", "곧 돌아올게요"),
    ConvExpr("Let's go back home.", "집으로 돌아가요"),
    ConvExpr("Get in the car.", "차에 타세요"),
    ConvExpr("Get out of the way.", "비켜 주세요"),
    ConvExpr("Get on the bus here.", "여기서 버스를 타세요"),
    ConvExpr("Get off at the next stop.", "다음 정류장에서 내리세요"),
    ConvExpr("Don't give up now.", "지금 포기하지 마세요"),
    ConvExpr("Hurry up, we're late.", "서둘러요, 늦었어요"),
    ConvExpr("clean up", "치우다"),
    ConvExpr("call back", "다시 전화하다"),
    ConvExpr("check out", "확인하다"),
    ConvExpr("come over", "놀러 오다"),
    ConvExpr("eat out", "외식하다"),
    ConvExpr("fill out", "작성하다"),
    ConvExpr("hang up", "전화를 끊다"),
    ConvExpr("look after", "돌보다"),
    ConvExpr("put away", "치워 두다"),
    ConvExpr("Clean up your desk.", "책상을 치우세요"),
    ConvExpr("I'll call back in ten minutes.", "10분 뒤에 다시 전화할게요"),
    ConvExpr("Check out this website.", "이 사이트 한번 보세요"),
    ConvExpr("Come over anytime.", "언제든 놀러 오세요"),
    ConvExpr("Let's eat out tonight.", "오늘 저녁 외식해요"),
    ConvExpr("Fill out the application.", "신청서를 작성하세요"),
    ConvExpr("Don't hang up yet.", "아직 끊지 마세요"),
    ConvExpr("Hold on a second.", "잠깐만요"),
    ConvExpr("Could you look after my dog?", "제 강아지 좀 봐 주실래요?"),
    ConvExpr("Put away your toys.", "장난감을 치우세요"),
    ConvExpr("show up", "나타나다"),
    ConvExpr("sign up", "등록하다"),
    ConvExpr("throw away", "버리다"),
    ConvExpr("try on", "입어 보다"),
    ConvExpr("turn in", "제출하다"),
    ConvExpr("work out", "운동하다"),
    ConvExpr("break down", "고장 나다"),
    ConvExpr("run out of", "다 떨어지다"),
    ConvExpr("set up", "설치하다"),
    ConvExpr("He didn't show up.", "그 사람이 안 왔어요"),
    ConvExpr("I signed up for class.", "수업에 등록했어요"),
    ConvExpr("Don't throw that away.", "그거 버리지 마세요"),
    ConvExpr("Can I try this on?", "이거 입어 봐도 돼요?"),
    ConvExpr("Turn in your report today.", "오늘 보고서를 제출하세요"),
    ConvExpr("I work out every morning.", "매일 아침 운동해요"),
    ConvExpr("My car broke down.", "차가 고장 났어요"),
    ConvExpr("We ran out of time.", "시간이 다 됐어요"),
    ConvExpr("Let me set it up.", "제가 설치할게요"),
    ConvExpr("keep up", "따라가다"),
    ConvExpr("look up", "찾아보다"),
    ConvExpr("move in", "이사 들어가다"),
    ConvExpr("pay back", "갚다"),
    ConvExpr("point out", "지적하다"),
    ConvExpr("wake me up", "나를 깨우다"),
    ConvExpr("work on", "작업하다"),
  ],
];
