// 자동 생성 데이터 — 성인 영어회화 표현 묶음.
// 기초 회화 1000 — 주제 1~10 (주제당 100개)

import 'conversation_data.dart';

/// 기초 회화 1000 — 주제 1~10
const List<List<ConvExpr>> convTier1 = [
  // 1번 주제
  [
    ConvExpr("Hi", "안녕"),
    ConvExpr("Hello", "안녕하세요"),
    ConvExpr("Bye", "잘 가요"),
    ConvExpr("Yes", "네"),
    ConvExpr("No", "아니요"),
    ConvExpr("Name", "이름"),
    ConvExpr("Friend", "친구"),
    ConvExpr("Thanks", "고마워요"),
    ConvExpr("Sorry", "미안해요"),
    ConvExpr("Please", "부탁해요"),
    ConvExpr("Good morning", "좋은 아침이에요"),
    ConvExpr("Good night", "안녕히 주무세요"),
    ConvExpr("See you", "또 봐요"),
    ConvExpr("Take care", "조심히 가요"),
    ConvExpr("My name", "제 이름"),
    ConvExpr("Nice to meet you.", "만나서 반가워요"),
    ConvExpr("How are you?", "어떻게 지내세요?"),
    ConvExpr("I'm fine.", "잘 지내요"),
    ConvExpr("What's your name?", "이름이 뭐예요?"),
    ConvExpr("My name is Tom.", "제 이름은 톰이에요"),
    ConvExpr("Where are you from?", "어디서 오셨어요?"),
    ConvExpr("I'm from Korea.", "저는 한국에서 왔어요"),
    ConvExpr("How old are you?", "몇 살이에요?"),
    ConvExpr("I'm thirty years old.", "저는 서른 살이에요"),
    ConvExpr("It's nice to meet you.", "만나서 정말 반가워요"),
    ConvExpr("Long time no see.", "오랜만이에요"),
    ConvExpr("This is my friend.", "제 친구예요"),
    ConvExpr("Let me introduce myself.", "제 소개를 할게요"),
    ConvExpr("What do you do?", "무슨 일을 하세요?"),
    ConvExpr("I'm a teacher.", "저는 교사예요"),
    ConvExpr("I'm a student.", "저는 학생이에요"),
    ConvExpr("Where do you live?", "어디에 사세요?"),
    ConvExpr("I live in Seoul.", "저는 서울에 살아요"),
    ConvExpr("Can I ask your name?", "이름을 여쭤봐도 될까요?"),
    ConvExpr("Have we met before?", "전에 만난 적 있나요?"),
    ConvExpr("I don't think we've met.", "우리 처음 뵙는 것 같아요"),
    ConvExpr("Same here.", "저도 그래요"),
    ConvExpr("It's a pleasure.", "만나서 영광이에요"),
    ConvExpr("Welcome", "환영해요"),
    ConvExpr("Welcome to Korea.", "한국에 오신 걸 환영해요"),
    ConvExpr("Thanks for coming.", "와 주셔서 감사해요"),
    ConvExpr("I appreciate it.", "감사드려요"),
    ConvExpr("No problem.", "괜찮아요"),
    ConvExpr("Don't mention it.", "별말씀을요"),
    ConvExpr("What's up?", "잘 지내?"),
    ConvExpr("Not much.", "별일 없어요"),
    ConvExpr("How's it going?", "어떻게 지내요?"),
    ConvExpr("Pretty good, thanks.", "꽤 좋아요 고마워요"),
    ConvExpr("I should get going.", "저는 이만 가봐야겠어요"),
    ConvExpr("Talk to you later.", "나중에 얘기해요"),
    ConvExpr("Keep in touch.", "연락하고 지내요"),
    ConvExpr("Let's stay in touch.", "계속 연락해요"),
    ConvExpr("Nice talking to you.", "얘기 나눠서 좋았어요"),
    ConvExpr("Take care of yourself.", "몸조심하세요"),
    ConvExpr("Have a good day.", "좋은 하루 보내세요"),
    ConvExpr("You too.", "당신도요"),
    ConvExpr("See you tomorrow.", "내일 봐요"),
    ConvExpr("See you soon.", "곧 봐요"),
    ConvExpr("See you next time.", "다음에 봐요"),
    ConvExpr("What's your last name?", "성이 어떻게 되세요?"),
    ConvExpr("Can I get your number?", "번호 좀 알 수 있을까요?"),
    ConvExpr("Here's my number.", "제 번호예요"),
    ConvExpr("What's your phone number?", "전화번호가 뭐예요?"),
    ConvExpr("Do you have an email?", "이메일 있으세요?"),
    ConvExpr("This is a friend of mine.", "제 친구 중 한 명이에요"),
    ConvExpr("Let me introduce my friend.", "제 친구를 소개할게요"),
    ConvExpr("Have you two met?", "두 분 서로 아세요?"),
    ConvExpr("I don't believe we've been introduced.", "통성명을 안 한 것 같네요"),
    ConvExpr("Allow me to introduce myself.", "제 소개를 하겠습니다"),
    ConvExpr("I've heard a lot about you.", "말씀 많이 들었어요"),
    ConvExpr("All good things, I hope.", "좋은 얘기였길 바라요"),
    ConvExpr("What brings you here?", "여기는 어쩐 일이세요?"),
    ConvExpr("I'm here on business.", "업무차 왔어요"),
    ConvExpr("I'm just visiting.", "그냥 여행 왔어요"),
    ConvExpr("How long are you staying?", "얼마나 머무세요?"),
    ConvExpr("I'm staying for a week.", "일주일 동안 머물러요"),
    ConvExpr("Are you new here?", "여기 처음이세요?"),
    ConvExpr("Yes, I just moved here.", "이제 막 이사 왔어요"),
    ConvExpr("Where did you grow up?", "어디서 자라셨어요?"),
    ConvExpr("I grew up in Busan.", "저는 부산에서 자랐어요"),
    ConvExpr("What languages do you speak?", "어떤 언어를 하세요?"),
    ConvExpr("I speak a little English.", "영어를 조금 해요"),
    ConvExpr("Sorry, I didn't catch your name.", "이름을 못 들었어요"),
    ConvExpr("Could you say that again?", "다시 말씀해 주시겠어요?"),
    ConvExpr("Sure, my name is Sarah.", "제 이름은 사라예요"),
    ConvExpr("Nice name.", "이름이 예쁘네요"),
    ConvExpr("Thanks, I like yours too.", "당신 이름도 좋아요"),
    ConvExpr("Do you come here often?", "여기 자주 오세요?"),
    ConvExpr("This is my first time here.", "여기 처음 와 봐요"),
    ConvExpr("I hope we can be friends.", "우리 친구가 되면 좋겠어요"),
    ConvExpr("Let's exchange contacts.", "연락처 교환해요"),
    ConvExpr("I'll add you on social media.", "SNS에서 추가할게요"),
    ConvExpr("I'm looking forward to it.", "기대하고 있어요"),
    ConvExpr("I've been looking forward to this.", "이 만남을 기대했어요"),
    ConvExpr("The pleasure is all mine.", "오히려 제가 영광이에요"),
    ConvExpr("Please, call me Tom.", "그냥 톰이라고 불러 주세요"),
    ConvExpr("What should I call you?", "뭐라고 불러야 할까요?"),
    ConvExpr("You can call me Sue.", "수라고 부르셔도 돼요"),
    ConvExpr("I go by my middle name.", "미들네임으로 불려요"),
    ConvExpr("Great to finally meet you.", "드디어 만나서 반가워요"),
  ],
  // 2번 주제
  [
    ConvExpr("Sleep", "잠"),
    ConvExpr("Wake up", "잠에서 깨다"),
    ConvExpr("Breakfast", "아침 식사"),
    ConvExpr("Lunch", "점심 식사"),
    ConvExpr("Dinner", "저녁 식사"),
    ConvExpr("Work", "일"),
    ConvExpr("School", "학교"),
    ConvExpr("Home", "집"),
    ConvExpr("Bus", "버스"),
    ConvExpr("Subway", "지하철"),
    ConvExpr("Get up", "자리에서 일어나다"),
    ConvExpr("Brush teeth", "이 닦기"),
    ConvExpr("Take a shower", "샤워하다"),
    ConvExpr("Get dressed", "옷 입기"),
    ConvExpr("Go to work", "출근하다"),
    ConvExpr("Go to school", "등교하다"),
    ConvExpr("Go home", "귀가하다"),
    ConvExpr("Take a nap", "낮잠 자기"),
    ConvExpr("Go to bed", "잠자리에 들다"),
    ConvExpr("Every day", "매일"),
    ConvExpr("I wake up early.", "일찍 일어나요"),
    ConvExpr("I get up at seven.", "일곱 시에 일어나요"),
    ConvExpr("I brush my teeth.", "이를 닦아요"),
    ConvExpr("I eat breakfast at home.", "집에서 아침을 먹어요"),
    ConvExpr("I take a shower.", "샤워를 해요"),
    ConvExpr("I go to work by bus.", "버스로 출근해요"),
    ConvExpr("I take the subway.", "지하철을 타요"),
    ConvExpr("I leave home at eight.", "여덟 시에 집을 나가요"),
    ConvExpr("I have lunch at noon.", "정오에 점심을 먹어요"),
    ConvExpr("I finish work at six.", "여섯 시에 퇴근해요"),
    ConvExpr("I go home after work.", "퇴근 후 집에 가요"),
    ConvExpr("I cook dinner.", "저녁을 요리해요"),
    ConvExpr("I eat dinner with my family.", "가족과 저녁을 먹어요"),
    ConvExpr("I wash the dishes.", "설거지를 해요"),
    ConvExpr("I watch TV at night.", "밤에 TV를 봐요"),
    ConvExpr("I read before bed.", "자기 전에 책을 읽어요"),
    ConvExpr("I go to bed at ten.", "열 시에 자러 가요"),
    ConvExpr("I sleep eight hours.", "여덟 시간을 자요"),
    ConvExpr("What time do you wake up?", "몇 시에 일어나세요?"),
    ConvExpr("I usually wake up at six.", "보통 여섯 시에 일어나요"),
    ConvExpr("Do you shower in the morning?", "아침에 샤워하세요?"),
    ConvExpr("Yes, I shower every morning.", "매일 아침 샤워해요"),
    ConvExpr("How do you get to work?", "직장에 어떻게 가세요?"),
    ConvExpr("I walk to work.", "걸어서 출근해요"),
    ConvExpr("I drive to work.", "차로 출근해요"),
    ConvExpr("It takes thirty minutes.", "삼십 분 걸려요"),
    ConvExpr("I'm always in a rush.", "항상 서둘러요"),
    ConvExpr("I skip breakfast sometimes.", "가끔 아침을 걸러요"),
    ConvExpr("Breakfast is the most important meal.", "아침이 가장 중요한 식사예요"),
    ConvExpr("I never skip breakfast.", "아침은 절대 안 걸러요"),
    ConvExpr("What do you have for breakfast?", "아침으로 뭘 드세요?"),
    ConvExpr("I usually eat toast and eggs.", "보통 토스트와 계란을 먹어요"),
    ConvExpr("I drink coffee every morning.", "매일 아침 커피를 마셔요"),
    ConvExpr("I pack my lunch.", "점심 도시락을 싸요"),
    ConvExpr("I eat out for lunch.", "점심은 밖에서 먹어요"),
    ConvExpr("My commute is long.", "통근 시간이 길어요"),
    ConvExpr("Traffic is bad in the morning.", "아침엔 차가 막혀요"),
    ConvExpr("I nap on the subway.", "지하철에서 졸아요"),
    ConvExpr("I get off at my stop.", "제 정류장에서 내려요"),
    ConvExpr("I arrive at work on time.", "제시간에 출근해요"),
    ConvExpr("I'm often late for work.", "자주 회사에 늦어요"),
    ConvExpr("I need more sleep.", "잠이 더 필요해요"),
    ConvExpr("I stayed up late last night.", "어젯밤 늦게까지 깨어 있었어요"),
    ConvExpr("I overslept this morning.", "오늘 아침 늦잠 잤어요"),
    ConvExpr("I set my alarm for six.", "알람을 여섯 시로 맞춰요"),
    ConvExpr("I hit the snooze button.", "다시 알람을 눌러요"),
    ConvExpr("I'm a morning person.", "저는 아침형 인간이에요"),
    ConvExpr("I'm a night owl.", "저는 저녁형 인간이에요"),
    ConvExpr("I feel sleepy in class.", "수업 시간에 졸려요"),
    ConvExpr("I take a break at work.", "직장에서 쉬는 시간을 가져요"),
    ConvExpr("My daily routine never changes.", "제 일과는 항상 똑같아요"),
    ConvExpr("I follow the same schedule daily.", "매일 같은 일정을 따라요"),
    ConvExpr("On weekdays, I wake up early.", "평일엔 일찍 일어나요"),
    ConvExpr("On weekends, I sleep in.", "주말엔 늦잠을 자요"),
    ConvExpr("I like to relax on Sundays.", "일요일엔 쉬는 걸 좋아해요"),
    ConvExpr("I do chores after dinner.", "저녁 후에 집안일을 해요"),
    ConvExpr("I exercise before work.", "출근 전에 운동해요"),
    ConvExpr("I go for a morning run.", "아침에 달리기를 해요"),
    ConvExpr("I meditate before bed.", "자기 전에 명상해요"),
    ConvExpr("I check my email first thing.", "제일 먼저 이메일을 확인해요"),
    ConvExpr("My schedule is packed today.", "오늘 일정이 꽉 찼어요"),
    ConvExpr("I barely have time for lunch.", "점심 먹을 시간도 없어요"),
    ConvExpr("I multitask during breakfast.", "아침 먹으며 딴 일을 해요"),
    ConvExpr("I'm running behind schedule.", "일정보다 늦어지고 있어요"),
    ConvExpr("I need more sleep this week.", "이번 주는 잠이 더 필요해요"),
    ConvExpr("I try to unwind before bed.", "자기 전에 긴장을 풀어요"),
    ConvExpr("I wind down with a book.", "책으로 마음을 가라앉혀요"),
    ConvExpr("My alarm didn't go off.", "알람이 안 울렸어요"),
    ConvExpr("I rushed out the door.", "서둘러 집을 나섰어요"),
    ConvExpr("I forgot to eat breakfast.", "아침 먹는 걸 깜빡했어요"),
    ConvExpr("I'm trying to build a routine.", "루틴을 만들려고 해요"),
    ConvExpr("Consistency is key for me.", "꾸준함이 중요해요"),
    ConvExpr("I keep a consistent bedtime.", "잠자리 시간을 일정하게 해요"),
    ConvExpr("Waking up early boosts my mood.", "일찍 일어나면 기분이 좋아요"),
    ConvExpr("Mornings make me more productive.", "아침에 더 생산적이에요"),
    ConvExpr("I struggle to fall asleep sometimes.", "가끔 잠들기 힘들어요"),
    ConvExpr("I toss and turn at night.", "밤에 뒤척여요"),
    ConvExpr("I've been sleeping better lately.", "요즘 잠을 잘 자요"),
    ConvExpr("Cutting caffeine helped my sleep.", "카페인을 줄이니 잘 자요"),
    ConvExpr("I changed my morning routine recently.", "최근에 아침 루틴을 바꿨어요"),
  ],
  // 3번 주제
  [
    ConvExpr("One", "하나"),
    ConvExpr("Two", "둘"),
    ConvExpr("Three", "셋"),
    ConvExpr("Four", "넷"),
    ConvExpr("Five", "다섯"),
    ConvExpr("Six", "여섯"),
    ConvExpr("Seven", "일곱"),
    ConvExpr("Eight", "여덟"),
    ConvExpr("Nine", "아홉"),
    ConvExpr("Ten", "열"),
    ConvExpr("Eleven", "열하나"),
    ConvExpr("Twelve", "열둘"),
    ConvExpr("Twenty", "스물"),
    ConvExpr("Hundred", "백"),
    ConvExpr("Hour", "시간"),
    ConvExpr("Minute", "분"),
    ConvExpr("Second", "초"),
    ConvExpr("Today", "오늘"),
    ConvExpr("Tomorrow", "내일"),
    ConvExpr("Yesterday", "어제"),
    ConvExpr("Monday", "월요일"),
    ConvExpr("Tuesday", "화요일"),
    ConvExpr("Wednesday", "수요일"),
    ConvExpr("Thursday", "목요일"),
    ConvExpr("Friday", "금요일"),
    ConvExpr("Saturday", "토요일"),
    ConvExpr("Sunday", "일요일"),
    ConvExpr("Weekday", "평일"),
    ConvExpr("Weekend", "주말"),
    ConvExpr("Week", "주"),
    ConvExpr("What time is it?", "몇 시예요?"),
    ConvExpr("It's three o'clock.", "세 시예요"),
    ConvExpr("It's half past three.", "세 시 반이에요"),
    ConvExpr("It's almost noon.", "거의 정오예요"),
    ConvExpr("It's midnight.", "자정이에요"),
    ConvExpr("What day is it today?", "오늘 무슨 요일이에요?"),
    ConvExpr("Today is Monday.", "오늘은 월요일이에요"),
    ConvExpr("What's the date today?", "오늘 며칠이에요?"),
    ConvExpr("It's September twentieth.", "구월 이십 일이에요"),
    ConvExpr("It's my birthday today.", "오늘 제 생일이에요"),
    ConvExpr("When is your birthday?", "생일이 언제예요?"),
    ConvExpr("My birthday is in May.", "제 생일은 오월이에요"),
    ConvExpr("What month is it?", "몇 월이에요?"),
    ConvExpr("It's September.", "구월이에요"),
    ConvExpr("It's autumn now.", "지금은 가을이에요"),
    ConvExpr("How many days in a week?", "일주일은 며칠이에요?"),
    ConvExpr("A week has seven days.", "일주일은 칠 일이에요"),
    ConvExpr("How many months in a year?", "일 년은 몇 개월이에요?"),
    ConvExpr("There are twelve months.", "열두 달이 있어요"),
    ConvExpr("What year is it?", "몇 년도예요?"),
    ConvExpr("It's twenty twenty-six.", "이천이십육 년이에요"),
    ConvExpr("What's the time now?", "지금 몇 시예요?"),
    ConvExpr("Do you have the time?", "지금 몇 시인지 아세요?"),
    ConvExpr("I have a meeting at two.", "두 시에 회의가 있어요"),
    ConvExpr("The train leaves at nine.", "기차는 아홉 시에 떠나요"),
    ConvExpr("See you at five.", "다섯 시에 봐요"),
    ConvExpr("Let's meet at noon.", "정오에 만나요"),
    ConvExpr("I'll call you at eight.", "여덟 시에 전화할게요"),
    ConvExpr("The store opens at ten.", "가게는 열 시에 열어요"),
    ConvExpr("The store closes at nine.", "가게는 아홉 시에 닫아요"),
    ConvExpr("Always", "항상"),
    ConvExpr("Usually", "보통"),
    ConvExpr("Often", "자주"),
    ConvExpr("Sometimes", "가끔"),
    ConvExpr("Rarely", "거의 안"),
    ConvExpr("Never", "절대 안"),
    ConvExpr("Once a week", "일주일에 한 번"),
    ConvExpr("Twice a month", "한 달에 두 번"),
    ConvExpr("Every other day", "하루걸러"),
    ConvExpr("How often do you exercise?", "운동 얼마나 자주 하세요?"),
    ConvExpr("I exercise three times a week.", "일주일에 세 번 운동해요"),
    ConvExpr("I usually wake up early.", "저는 보통 일찍 일어나요"),
    ConvExpr("I rarely eat out.", "외식은 거의 안 해요"),
    ConvExpr("I never drink coffee at night.", "밤에 커피는 절대 안 마셔요"),
    ConvExpr("I sometimes work late.", "가끔 늦게까지 일해요"),
    ConvExpr("How long does it take?", "얼마나 걸려요?"),
    ConvExpr("It takes about an hour.", "한 시간 정도 걸려요"),
    ConvExpr("It takes ten minutes.", "십 분 걸려요"),
    ConvExpr("It won't take long.", "오래 안 걸려요"),
    ConvExpr("Just a minute, please.", "잠시만요"),
    ConvExpr("I'll be there in five minutes.", "오 분 안에 갈게요"),
    ConvExpr("I've been waiting for an hour.", "한 시간째 기다리고 있어요"),
    ConvExpr("The meeting starts in ten minutes.", "십 분 후에 회의가 시작해요"),
    ConvExpr("I'm running fifteen minutes late.", "십오 분 늦고 있어요"),
    ConvExpr("Can we meet next week?", "다음 주에 만날 수 있어요?"),
    ConvExpr("Let's meet the week after next.", "다다음 주에 만나요"),
    ConvExpr("My schedule is free this weekend.", "이번 주말엔 일정이 비어요"),
    ConvExpr("I'm busy until Friday.", "금요일까지 바빠요"),
    ConvExpr("Let's reschedule for next Monday.", "다음 주 월요일로 미뤄요"),
    ConvExpr("The deadline is end of month.", "마감은 월말이에요"),
    ConvExpr("I was born in nineteen ninety.", "저는 1990년에 태어났어요"),
    ConvExpr("What's today's date?", "오늘 날짜가 어떻게 돼요?"),
    ConvExpr("It's the first of January.", "일월 일 일이에요"),
    ConvExpr("The new year starts in January.", "새해는 일월에 시작해요"),
    ConvExpr("My anniversary is in June.", "제 기념일은 유월이에요"),
    ConvExpr("This month went by fast.", "이번 달 정말 빨리 갔어요"),
    ConvExpr("Time flies so fast.", "시간이 정말 빨리 가요"),
    ConvExpr("I can't believe it's fall.", "벌써 가을이라니 믿기지 않아요"),
    ConvExpr("The years go by fast.", "세월이 참 빨리 가요"),
    ConvExpr("Every year feels shorter now.", "해마다 더 짧게 느껴져요"),
  ],
  // 4번 주제
  [
    ConvExpr("Mom", "엄마"),
    ConvExpr("Dad", "아빠"),
    ConvExpr("Family", "가족"),
    ConvExpr("Brother", "남자 형제"),
    ConvExpr("Sister", "여자 형제"),
    ConvExpr("Son", "아들"),
    ConvExpr("Daughter", "딸"),
    ConvExpr("Baby", "아기"),
    ConvExpr("Parents", "부모님"),
    ConvExpr("Grandma", "할머니"),
    ConvExpr("Grandpa", "할아버지"),
    ConvExpr("Husband", "남편"),
    ConvExpr("Wife", "아내"),
    ConvExpr("Uncle", "삼촌"),
    ConvExpr("Aunt", "이모"),
    ConvExpr("Cousin", "사촌"),
    ConvExpr("Nephew", "조카"),
    ConvExpr("Niece", "조카딸"),
    ConvExpr("Only child", "외동"),
    ConvExpr("Twins", "쌍둥이"),
    ConvExpr("Tall", "키 큰"),
    ConvExpr("Short", "키 작은"),
    ConvExpr("Young", "어린"),
    ConvExpr("Old", "나이 든"),
    ConvExpr("Kind", "친절한"),
    ConvExpr("Funny", "재미있는"),
    ConvExpr("Smart", "똑똑한"),
    ConvExpr("Handsome", "잘생긴"),
    ConvExpr("Pretty", "예쁜"),
    ConvExpr("Friendly", "다정한"),
    ConvExpr("This is my mom.", "제 엄마예요"),
    ConvExpr("This is my dad.", "제 아빠예요"),
    ConvExpr("I have a brother.", "남동생이 있어요"),
    ConvExpr("I have a sister.", "여동생이 있어요"),
    ConvExpr("I have two kids.", "아이가 둘 있어요"),
    ConvExpr("I'm an only child.", "저는 외동이에요"),
    ConvExpr("How many siblings do you have?", "형제자매가 몇 명이세요?"),
    ConvExpr("I have one sister.", "여동생이 한 명 있어요"),
    ConvExpr("Are you married?", "결혼하셨어요?"),
    ConvExpr("Yes, I'm married.", "네, 결혼했어요"),
    ConvExpr("No, I'm single.", "아니요, 미혼이에요"),
    ConvExpr("Do you have kids?", "아이가 있으세요?"),
    ConvExpr("I don't have kids yet.", "아직 아이가 없어요"),
    ConvExpr("This is my husband.", "제 남편이에요"),
    ConvExpr("This is my wife.", "제 아내예요"),
    ConvExpr("He's my older brother.", "오빠예요"),
    ConvExpr("She's my younger sister.", "제 여동생이에요"),
    ConvExpr("We're twins.", "우리는 쌍둥이예요"),
    ConvExpr("My parents live nearby.", "부모님이 근처에 사세요"),
    ConvExpr("I live with my family.", "가족과 함께 살아요"),
    ConvExpr("What does your dad do?", "아버지는 무슨 일을 하세요?"),
    ConvExpr("My dad is a doctor.", "아빠는 의사예요"),
    ConvExpr("My mom is a nurse.", "엄마는 간호사예요"),
    ConvExpr("My sister is a teacher.", "언니는 선생님이에요"),
    ConvExpr("He works as an engineer.", "그는 엔지니어로 일해요"),
    ConvExpr("She's still in school.", "그녀는 아직 학생이에요"),
    ConvExpr("My brother is younger than me.", "남동생이 저보다 어려요"),
    ConvExpr("My sister is older than me.", "언니가 저보다 나이 많아요"),
    ConvExpr("We look alike.", "우리는 닮았어요"),
    ConvExpr("I take after my mom.", "저는 엄마를 닮았어요"),
    ConvExpr("What does he look like?", "그는 어떻게 생겼어요?"),
    ConvExpr("He's tall and thin.", "그는 키가 크고 말랐어요"),
    ConvExpr("She has long hair.", "그녀는 머리가 길어요"),
    ConvExpr("She has short hair.", "그녀는 머리가 짧아요"),
    ConvExpr("He wears glasses.", "그는 안경을 써요"),
    ConvExpr("She has brown eyes.", "그녀는 눈이 갈색이에요"),
    ConvExpr("He has curly hair.", "그는 곱슬머리예요"),
    ConvExpr("She's very kind.", "그녀는 정말 친절해요"),
    ConvExpr("He's a bit shy.", "그는 조금 수줍어해요"),
    ConvExpr("She's outgoing and cheerful.", "그녀는 활발하고 밝아요"),
    ConvExpr("My grandma raised me.", "할머니가 저를 키우셨어요"),
    ConvExpr("I'm close to my grandpa.", "할아버지와 사이가 좋아요"),
    ConvExpr("We're a close family.", "우리는 가까운 가족이에요"),
    ConvExpr("My family is big.", "저희 가족은 대가족이에요"),
    ConvExpr("My family is small.", "저희 가족은 단출해요"),
    ConvExpr("My aunt lives abroad.", "이모는 외국에 살아요"),
    ConvExpr("My uncle visits every summer.", "삼촌은 여름마다 방문해요"),
    ConvExpr("I get along with my cousin.", "사촌과 사이가 좋아요"),
    ConvExpr("My nephew is so cute.", "조카가 정말 귀여워요"),
    ConvExpr("My niece just turned five.", "조카딸이 방금 다섯 살 됐어요"),
    ConvExpr("I was raised by my grandparents.", "조부모님 손에 자랐어요"),
    ConvExpr("My parents got divorced.", "부모님이 이혼하셨어요"),
    ConvExpr("I'm the oldest of three.", "저는 삼 남매 중 첫째예요"),
    ConvExpr("I'm the youngest in my family.", "저희 집 막내예요"),
    ConvExpr("I'm the middle child.", "저는 둘째예요"),
    ConvExpr("My family means everything to me.", "가족이 저한테 전부예요"),
    ConvExpr("We don't see each other often.", "자주 못 만나요"),
    ConvExpr("We're not that close.", "우리는 그렇게 친하지 않아요"),
    ConvExpr("He takes after his father.", "그는 아버지를 닮았어요"),
    ConvExpr("She has her mother's smile.", "그녀는 엄마 미소를 닮았어요"),
    ConvExpr("My in-laws live with us.", "배우자 부모님과 같이 살아요"),
    ConvExpr("We're expecting a baby.", "저희 아기를 기다리고 있어요"),
    ConvExpr("Congratulations on the new baby!", "새 아기 축하해요!"),
    ConvExpr("He just became a father.", "그는 방금 아빠가 됐어요"),
    ConvExpr("She's due next month.", "다음 달이 출산 예정이에요"),
    ConvExpr("My son just started school.", "아들이 막 학교에 들어갔어요"),
    ConvExpr("My daughter is in college.", "딸은 대학에 다녀요"),
    ConvExpr("He's getting married next year.", "그는 내년에 결혼해요"),
    ConvExpr("They've been married ten years.", "결혼한 지 십 년 됐어요"),
    ConvExpr("We're planning a family reunion.", "가족 모임을 계획하고 있어요"),
  ],
  // 5번 주제
  [
    ConvExpr("Water", "물"),
    ConvExpr("Coffee", "커피"),
    ConvExpr("Tea", "차"),
    ConvExpr("Menu", "메뉴"),
    ConvExpr("Bill", "계산서"),
    ConvExpr("Table", "테이블"),
    ConvExpr("Spoon", "숟가락"),
    ConvExpr("Fork", "포크"),
    ConvExpr("Knife", "나이프"),
    ConvExpr("Napkin", "냅킨"),
    ConvExpr("Delicious", "맛있는"),
    ConvExpr("Spicy", "매운"),
    ConvExpr("Sweet", "단"),
    ConvExpr("Sour", "신"),
    ConvExpr("Salty", "짠"),
    ConvExpr("Bitter", "쓴"),
    ConvExpr("Hot food", "뜨거운 음식"),
    ConvExpr("Cold drink", "차가운 음료"),
    ConvExpr("Take out", "포장"),
    ConvExpr("For here", "여기서 먹기"),
    ConvExpr("Excuse me.", "저기요"),
    ConvExpr("Can I see the menu?", "메뉴 좀 볼 수 있을까요?"),
    ConvExpr("I'm ready to order.", "주문할게요"),
    ConvExpr("Water, please.", "물 좀 주세요"),
    ConvExpr("One coffee, please.", "커피 한 잔 주세요"),
    ConvExpr("Check, please.", "계산서 주세요"),
    ConvExpr("Thank you for the meal.", "잘 먹었습니다"),
    ConvExpr("This is delicious.", "이거 맛있어요"),
    ConvExpr("It's too spicy.", "너무 매워요"),
    ConvExpr("I'm full.", "배불러요"),
    ConvExpr("Can I get a coffee?", "커피 한 잔 주시겠어요?"),
    ConvExpr("I'll have the pasta.", "저는 파스타로 할게요"),
    ConvExpr("What do you recommend?", "뭐가 맛있어요?"),
    ConvExpr("Is this dish spicy?", "이 음식 매워요?"),
    ConvExpr("Can I have some water?", "물 좀 주시겠어요?"),
    ConvExpr("Table for two, please.", "두 명이요"),
    ConvExpr("Do you have an English menu?", "영어 메뉴 있어요?"),
    ConvExpr("I'd like to make a reservation.", "예약하고 싶어요"),
    ConvExpr("Is this seat taken?", "여기 자리 있어요?"),
    ConvExpr("We're just looking, thanks.", "그냥 보는 중이에요"),
    ConvExpr("What's the special today?", "오늘 특별 메뉴가 뭐예요?"),
    ConvExpr("I'll have what she's having.", "그녀와 같은 걸로 할게요"),
    ConvExpr("Can I get this to go?", "포장해 주시겠어요?"),
    ConvExpr("For here or to go?", "여기서 드세요, 포장이세요?"),
    ConvExpr("I'm allergic to peanuts.", "저는 땅콩 알레르기가 있어요"),
    ConvExpr("Does this have nuts in it?", "여기 견과류 들어가요?"),
    ConvExpr("I'm a vegetarian.", "저는 채식주의자예요"),
    ConvExpr("Can I get this without onions?", "양파 빼 주시겠어요?"),
    ConvExpr("Could I get some more napkins?", "냅킨 좀 더 주시겠어요?"),
    ConvExpr("This tastes amazing.", "진짜 맛있어요"),
    ConvExpr("Can we get the check, please?", "계산서 좀 주시겠어요?"),
    ConvExpr("Is service charge included?", "봉사료 포함이에요?"),
    ConvExpr("Do you take credit cards?", "카드 되나요?"),
    ConvExpr("Can we split the bill?", "나눠서 계산할 수 있어요?"),
    ConvExpr("I'll get this one.", "이건 제가 낼게요"),
    ConvExpr("It's on me.", "제가 살게요"),
    ConvExpr("Let's split it.", "반씩 내요"),
    ConvExpr("Can I get a refill?", "리필 되나요?"),
    ConvExpr("Could you box this up?", "이거 포장해 주시겠어요?"),
    ConvExpr("Is there a wait?", "기다려야 하나요?"),
    ConvExpr("We'd like a window table.", "창가 자리로 주세요"),
    ConvExpr("Can we wait for our friend?", "친구를 기다려도 될까요?"),
    ConvExpr("What comes with this?", "이거 뭐랑 같이 나와요?"),
    ConvExpr("Can I swap fries for salad?", "감자튀김 대신 샐러드로요?"),
    ConvExpr("How spicy is this dish?", "이 음식 얼마나 매워요?"),
    ConvExpr("Could you make it less spicy?", "덜 맵게 해 주시겠어요?"),
    ConvExpr("I'd like it well done.", "완전히 익혀 주세요"),
    ConvExpr("I'd like it medium rare.", "미디엄 레어로 해 주세요"),
    ConvExpr("Could we get some more time?", "시간을 좀 더 주시겠어요?"),
    ConvExpr("We're ready to order now.", "이제 주문할게요"),
    ConvExpr("This isn't what I ordered.", "이거 제가 주문한 게 아니에요"),
    ConvExpr("Could you check this again?", "다시 확인해 주시겠어요?"),
    ConvExpr("I think the bill is wrong.", "계산서가 잘못된 것 같아요"),
    ConvExpr("Please take this back.", "이거 다시 가져가 주세요"),
    ConvExpr("This is undercooked.", "덜 익었어요"),
    ConvExpr("This is cold.", "이거 차가워요"),
    ConvExpr("Could I get a new one?", "새로 하나 주시겠어요?"),
    ConvExpr("Sorry for the confusion.", "혼란을 드려 죄송해요"),
    ConvExpr("No worries at all.", "전혀 괜찮아요"),
    ConvExpr("Thanks for fixing that.", "고쳐 주셔서 감사해요"),
    ConvExpr("This place has great reviews.", "여기 리뷰가 정말 좋아요"),
    ConvExpr("I've heard great things about it.", "여기 얘기 많이 들었어요"),
    ConvExpr("The portions here are huge.", "여기 양이 정말 많아요"),
    ConvExpr("The service was excellent.", "서비스가 훌륭했어요"),
    ConvExpr("I'll definitely come back.", "꼭 다시 올게요"),
    ConvExpr("This is my new favorite restaurant.", "여기가 새로운 최애 식당이에요"),
    ConvExpr("I could eat this every day.", "이거 매일 먹을 수 있어요"),
    ConvExpr("This is way too salty.", "이거 너무 짜요"),
    ConvExpr("It's not really my taste.", "제 입맛엔 안 맞아요"),
    ConvExpr("It's an acquired taste.", "익숙해져야 하는 맛이에요"),
    ConvExpr("Let's try somewhere new tonight.", "오늘 밤엔 새로운 곳 가봐요"),
    ConvExpr("I'm in the mood for noodles.", "국수가 당겨요"),
    ConvExpr("I could go for some coffee.", "커피 한 잔 하고 싶어요"),
    ConvExpr("I'm craving something sweet.", "단 게 당겨요"),
    ConvExpr("Let's grab a quick bite.", "간단히 먹으러 가요"),
    ConvExpr("Know a good place nearby?", "근처에 좋은 곳 알아요?"),
    ConvExpr("This restaurant is a hidden gem.", "이 식당은 숨은 맛집이에요"),
    ConvExpr("It's a bit overpriced.", "좀 비싼 것 같아요"),
    ConvExpr("The atmosphere here is really cozy.", "여기 분위기가 정말 아늑해요"),
    ConvExpr("I love this cafe's ambiance.", "이 카페 분위기가 좋아요"),
  ],
  // 6번 주제
  [
    ConvExpr("price", "가격"),
    ConvExpr("cash", "현금"),
    ConvExpr("sale", "세일"),
    ConvExpr("size", "사이즈"),
    ConvExpr("receipt", "영수증"),
    ConvExpr("discount", "할인"),
    ConvExpr("refund", "환불"),
    ConvExpr("coupon", "쿠폰"),
    ConvExpr("cart", "카트"),
    ConvExpr("change", "잔돈"),
    ConvExpr("credit card", "신용카드"),
    ConvExpr("gift card", "기프트카드"),
    ConvExpr("price tag", "가격표"),
    ConvExpr("gift wrap", "선물 포장"),
    ConvExpr("shopping bag", "쇼핑백"),
    ConvExpr("fitting room", "탈의실"),
    ConvExpr("cash register", "계산대"),
    ConvExpr("shopping list", "쇼핑 목록"),
    ConvExpr("store credit", "상품권"),
    ConvExpr("sales tax", "판매세"),
    ConvExpr("final sale", "최종 세일"),
    ConvExpr("return policy", "반품 정책"),
    ConvExpr("customer service", "고객센터"),
    ConvExpr("shopping cart", "쇼핑 카트"),
    ConvExpr("best price", "최저가"),
    ConvExpr("store hours", "영업시간"),
    ConvExpr("online order", "온라인 주문"),
    ConvExpr("free shipping", "무료 배송"),
    ConvExpr("clearance sale", "재고 정리 세일"),
    ConvExpr("department store", "백화점"),
    ConvExpr("checkout counter", "계산대 앞"),
    ConvExpr("loyalty program", "적립 프로그램"),
    ConvExpr("price match", "가격 비교 보장"),
    ConvExpr("warranty period", "보증 기간"),
    ConvExpr("This is nice.", "이거 예쁘네요"),
    ConvExpr("How much is this?", "이거 얼마예요?"),
    ConvExpr("I'll take this.", "이걸로 할게요"),
    ConvExpr("It's too expensive.", "너무 비싸요"),
    ConvExpr("I'm just looking.", "그냥 구경 중이에요"),
    ConvExpr("Can I try this?", "입어봐도 돼요?"),
    ConvExpr("Where's the fitting room?", "탈의실이 어디예요?"),
    ConvExpr("Do you have this?", "이거 있어요?"),
    ConvExpr("Do you take cards?", "카드 되나요?"),
    ConvExpr("Can I get a discount?", "할인 좀 해주세요"),
    ConvExpr("Can I get a receipt?", "영수증 주시겠어요?"),
    ConvExpr("This is on sale.", "이거 세일이에요"),
    ConvExpr("I don't like this color.", "색깔이 마음에 안 들어요"),
    ConvExpr("Do you have this in blue?", "파란색 있어요?"),
    ConvExpr("It doesn't fit me.", "저한테 안 맞아요"),
    ConvExpr("Can I pay cash?", "현금으로 낼 수 있어요?"),
    ConvExpr("I'd like a refund.", "환불하고 싶어요"),
    ConvExpr("Can I exchange this?", "이거 교환할 수 있어요?"),
    ConvExpr("Where do I pay?", "어디서 계산해요?"),
    ConvExpr("Is tax included?", "세금 포함인가요?"),
    ConvExpr("Do you have a smaller one?", "작은 거 있어요?"),
    ConvExpr("That's a good deal.", "괜찮은 가격이네요"),
    ConvExpr("I need a bag.", "봉투 주세요"),
    ConvExpr("Please wrap this as a gift.", "선물 포장 해주세요"),
    ConvExpr("I need to think it over.", "좀 생각해볼게요"),
    ConvExpr("I bought this yesterday.", "어제 이거 샀어요"),
    ConvExpr("This is out of stock.", "품절이에요"),
    ConvExpr("Can I use this coupon?", "이 쿠폰 쓸 수 있어요?"),
    ConvExpr("What size do you wear?", "사이즈가 몇이에요?"),
    ConvExpr("I want to return this.", "이거 반품하고 싶어요"),
    ConvExpr("Keep the change.", "잔돈은 됐어요"),
    ConvExpr("Here's your change.", "여기 잔돈이요"),
    ConvExpr("Do you have a membership card?", "멤버십 카드 있어요?"),
    ConvExpr("This is my size.", "이게 제 사이즈예요"),
    ConvExpr("Where are the sale items?", "세일 상품이 어디예요?"),
    ConvExpr("Do you have another color?", "다른 색으로 있어요?"),
    ConvExpr("I don't have the receipt.", "영수증이 없어요"),
    ConvExpr("It was cheaper yesterday.", "어제 더 쌌어요"),
    ConvExpr("This shirt is too tight.", "이 셔츠 너무 껴요"),
    ConvExpr("These pants are too loose.", "이 바지 너무 헐렁해요"),
    ConvExpr("I need a different size.", "다른 사이즈가 필요해요"),
    ConvExpr("Can I get a bag?", "봉투 있어요?"),
    ConvExpr("How long is the warranty?", "보증기간이 얼마나 돼요?"),
    ConvExpr("Do you offer free delivery?", "무료 배송 되나요?"),
    ConvExpr("I'll pay by card.", "카드로 계산할게요"),
    ConvExpr("This price looks wrong.", "가격이 잘못된 것 같아요"),
    ConvExpr("Can I split the payment?", "나눠서 결제할 수 있어요?"),
    ConvExpr("Is there a student discount?", "학생 할인 있어요?"),
    ConvExpr("I changed my mind.", "마음이 바뀌었어요"),
    ConvExpr("This item is defective.", "이 물건 불량이에요"),
    ConvExpr("Can I see the manager?", "매니저 불러주세요"),
    ConvExpr("What's your return policy?", "반품 정책이 어떻게 돼요?"),
    ConvExpr("I'd like to cancel this.", "이거 취소할게요"),
    ConvExpr("Does this have a warranty?", "보증서가 포함되나요?"),
    ConvExpr("Is this the final price?", "이게 최종 가격이에요?"),
    ConvExpr("Can I get store credit?", "상품권으로 받을 수 있어요?"),
    ConvExpr("I already paid for this.", "이미 결제했어요"),
    ConvExpr("The zipper is broken.", "지퍼가 고장났어요"),
    ConvExpr("Can you hold this for me?", "이거 맡아주실 수 있어요?"),
    ConvExpr("I'll come back later.", "나중에 다시 올게요"),
    ConvExpr("Where's the nearest checkout?", "가까운 계산대가 어디예요?"),
    ConvExpr("Do you price match?", "가격 맞춰주나요?"),
    ConvExpr("Can I use two coupons?", "쿠폰 두 개 되나요?"),
    ConvExpr("I need customer service.", "고객센터가 필요해요"),
    ConvExpr("The tag shows a different price.", "태그 가격이 달라요"),
    ConvExpr("Can you check the price?", "가격 좀 확인해 주세요"),
  ],
  // 7번 주제
  [
    ConvExpr("taxi", "택시"),
    ConvExpr("map", "지도"),
    ConvExpr("corner", "모퉁이"),
    ConvExpr("street", "거리"),
    ConvExpr("left", "왼쪽"),
    ConvExpr("right", "오른쪽"),
    ConvExpr("straight", "직진"),
    ConvExpr("crosswalk", "횡단보도"),
    ConvExpr("bus stop", "버스 정류장"),
    ConvExpr("subway station", "지하철역"),
    ConvExpr("taxi stand", "택시 승강장"),
    ConvExpr("traffic light", "신호등"),
    ConvExpr("one-way street", "일방통행로"),
    ConvExpr("bus fare", "버스 요금"),
    ConvExpr("subway fare", "지하철 요금"),
    ConvExpr("transfer station", "환승역"),
    ConvExpr("exit number", "출구 번호"),
    ConvExpr("rush hour", "출퇴근 시간"),
    ConvExpr("walking distance", "도보 거리"),
    ConvExpr("round trip", "왕복"),
    ConvExpr("bike lane", "자전거 도로"),
    ConvExpr("traffic jam", "교통 체증"),
    ConvExpr("express bus", "고속버스"),
    ConvExpr("local train", "완행열차"),
    ConvExpr("last train", "막차"),
    ConvExpr("next stop", "다음 정류장"),
    ConvExpr("parking lot", "주차장"),
    ConvExpr("side street", "골목길"),
    ConvExpr("main street", "큰길"),
    ConvExpr("transit card", "교통카드"),
    ConvExpr("subway map", "지하철 노선도"),
    ConvExpr("shortest route", "최단 경로"),
    ConvExpr("I'm lost.", "길을 잃었어요"),
    ConvExpr("Where's the subway?", "지하철이 어디예요?"),
    ConvExpr("Turn left.", "왼쪽으로 도세요"),
    ConvExpr("Turn right.", "오른쪽으로 도세요"),
    ConvExpr("Go straight.", "직진하세요"),
    ConvExpr("Is it far?", "멀어요?"),
    ConvExpr("How do I get there?", "거기 어떻게 가요?"),
    ConvExpr("Can you show me?", "보여주시겠어요?"),
    ConvExpr("Turn left at the corner.", "모퉁이에서 왼쪽으로 도세요"),
    ConvExpr("It's near the bank.", "은행 근처예요"),
    ConvExpr("It's across from the park.", "공원 맞은편이에요"),
    ConvExpr("Where's the nearest bus stop?", "가까운 버스 정류장이 어디예요?"),
    ConvExpr("Which bus goes downtown?", "시내 가는 버스가 뭐예요?"),
    ConvExpr("How much is the fare?", "요금이 얼마예요?"),
    ConvExpr("Does this bus go downtown?", "이 버스 시내로 가요?"),
    ConvExpr("Can you help me?", "도와주시겠어요?"),
    ConvExpr("Where can I catch a taxi?", "택시 어디서 타요?"),
    ConvExpr("Take me to this address.", "이 주소로 가주세요"),
    ConvExpr("Please drop me off here.", "여기서 내려주세요"),
    ConvExpr("How much will it cost?", "얼마 나와요?"),
    ConvExpr("Please stop here.", "여기서 세워주세요"),
    ConvExpr("Where do I transfer?", "어디서 환승해요?"),
    ConvExpr("Which exit should I take?", "몇 번 출구로 나가요?"),
    ConvExpr("When does the last bus leave?", "막차가 언제 있어요?"),
    ConvExpr("Where does this bus stop?", "이 버스 어디서 서요?"),
    ConvExpr("Do I need to transfer?", "갈아타야 해요?"),
    ConvExpr("Can I use this card?", "이 카드 쓸 수 있어요?"),
    ConvExpr("I got on the wrong bus.", "버스 잘못 탄 것 같아요"),
    ConvExpr("How many stops to downtown?", "시내까지 몇 정거장이에요?"),
    ConvExpr("Is there a subway nearby?", "근처에 지하철 있어요?"),
    ConvExpr("Which way is the exit?", "출구가 어느 쪽이에요?"),
    ConvExpr("Please tell me when we arrive.", "도착하면 알려주세요"),
    ConvExpr("I need this address.", "이 주소로 가야 해요"),
    ConvExpr("Is there a shortcut?", "지름길 있어요?"),
    ConvExpr("Keep going straight ahead.", "계속 직진하세요"),
    ConvExpr("Cross the street here.", "여기서 길 건너세요"),
    ConvExpr("It's a five-minute walk.", "걸어서 5분이에요"),
    ConvExpr("You can't miss it.", "못 지나칠 거예요"),
    ConvExpr("It's on the second floor.", "2층에 있어요"),
    ConvExpr("Take the elevator up.", "엘리베이터 타고 올라가세요"),
    ConvExpr("There's construction here.", "여기 공사 중이에요"),
    ConvExpr("This road is closed.", "이 길 통제됐어요"),
    ConvExpr("Can you call me a taxi?", "택시 좀 불러주세요"),
    ConvExpr("Traffic is really bad today.", "오늘 교통이 심해요"),
    ConvExpr("I'll take the subway instead.", "대신 지하철 탈게요"),
    ConvExpr("Which platform does this leave from?", "몇 번 플랫폼이에요?"),
    ConvExpr("Do I need a transfer ticket?", "환승표가 필요해요?"),
    ConvExpr("The bus was late again.", "버스가 또 늦었어요"),
    ConvExpr("I missed my stop.", "내릴 곳을 지나쳤어요"),
    ConvExpr("Where should I get off?", "어디서 내려야 해요?"),
    ConvExpr("This is a one-way street.", "여기는 일방통행이에요"),
    ConvExpr("You have to go around.", "돌아가야 해요"),
    ConvExpr("The exit is over there.", "출구는 저쪽이에요"),
    ConvExpr("Walking is faster than driving.", "운전보다 걷는 게 빨라요"),
    ConvExpr("I'd rather take a taxi.", "택시 탈래요"),
    ConvExpr("How far is the station?", "역까지 얼마나 멀어요?"),
    ConvExpr("We're going the wrong way.", "길을 잘못 든 것 같아요"),
    ConvExpr("Turn here, the map says.", "여기서 돌라고 나와요"),
    ConvExpr("Let's ask for directions.", "길 좀 물어보자"),
    ConvExpr("Is there a faster route?", "더 빠른 길이 있어요?"),
    ConvExpr("The next train comes soon.", "다음 기차가 곧 와요"),
    ConvExpr("I need the last train.", "막차를 타야 해요"),
    ConvExpr("Point me toward the exit.", "출구 쪽 알려주세요"),
    ConvExpr("This app shows the route.", "이 앱이 길을 보여줘요"),
    ConvExpr("Traffic is heavy near the bridge.", "다리 근처 교통이 심해요"),
    ConvExpr("I got off too early.", "너무 일찍 내렸어요"),
    ConvExpr("Can you recommend a good route?", "좋은 길 추천해주세요"),
    ConvExpr("The subway is faster now.", "지금은 지하철이 더 빨라요"),
  ],
  // 8번 주제
  [
    ConvExpr("weather", "날씨"),
    ConvExpr("rain", "비"),
    ConvExpr("snow", "눈"),
    ConvExpr("wind", "바람"),
    ConvExpr("sunny", "화창한"),
    ConvExpr("cloudy", "흐린"),
    ConvExpr("hot", "더운"),
    ConvExpr("cold", "추운"),
    ConvExpr("warm", "따뜻한"),
    ConvExpr("cool", "선선한"),
    ConvExpr("spring", "봄"),
    ConvExpr("summer", "여름"),
    ConvExpr("fall", "가을"),
    ConvExpr("winter", "겨울"),
    ConvExpr("temperature", "기온"),
    ConvExpr("humidity", "습도"),
    ConvExpr("forecast", "일기예보"),
    ConvExpr("thunderstorm", "뇌우"),
    ConvExpr("heat wave", "폭염"),
    ConvExpr("cold snap", "한파"),
    ConvExpr("rainy season", "장마철"),
    ConvExpr("fine dust", "미세먼지"),
    ConvExpr("clear sky", "맑은 하늘"),
    ConvExpr("heavy rain", "폭우"),
    ConvExpr("light rain", "가랑비"),
    ConvExpr("strong wind", "강풍"),
    ConvExpr("weather app", "날씨 앱"),
    ConvExpr("umbrella", "우산"),
    ConvExpr("raincoat", "우비"),
    ConvExpr("snowstorm", "눈보라"),
    ConvExpr("drizzle", "이슬비"),
    ConvExpr("air quality", "대기질"),
    ConvExpr("seasonal change", "환절기"),
    ConvExpr("degrees Celsius", "섭씨 온도"),
    ConvExpr("It's raining.", "비가 와요"),
    ConvExpr("It's snowing.", "눈이 와요"),
    ConvExpr("It's cold today.", "오늘 추워요"),
    ConvExpr("It's hot today.", "오늘 더워요"),
    ConvExpr("It's windy today.", "오늘 바람이 불어요"),
    ConvExpr("It's sunny today.", "오늘 화창해요"),
    ConvExpr("It's cloudy today.", "오늘 흐려요"),
    ConvExpr("What's the weather like?", "날씨가 어때요?"),
    ConvExpr("How's the weather today?", "오늘 날씨 어때요?"),
    ConvExpr("It looks like rain.", "비 올 것 같아요"),
    ConvExpr("Bring an umbrella.", "우산 챙기세요"),
    ConvExpr("It might snow later.", "나중에 눈 올 수도 있어요"),
    ConvExpr("I love this weather.", "이 날씨 너무 좋아요"),
    ConvExpr("I hate this weather.", "이 날씨 정말 싫어요"),
    ConvExpr("It's freezing outside.", "밖이 엄청 추워요"),
    ConvExpr("It's boiling hot outside.", "밖이 엄청 더워요"),
    ConvExpr("Is it going to rain?", "비 올까요?"),
    ConvExpr("Will it snow tomorrow?", "내일 눈 올까요?"),
    ConvExpr("What's the temperature today?", "오늘 기온이 몇 도예요?"),
    ConvExpr("It's ten degrees today.", "오늘 10도예요"),
    ConvExpr("It feels warmer than yesterday.", "어제보다 더 따뜻해요"),
    ConvExpr("It feels colder than yesterday.", "어제보다 더 추워요"),
    ConvExpr("The weather changed suddenly.", "날씨가 갑자기 바뀌었어요"),
    ConvExpr("Spring is my favorite season.", "봄이 제일 좋아요"),
    ConvExpr("I love fall weather.", "가을 날씨가 좋아요"),
    ConvExpr("Summer here is very humid.", "여기 여름은 습해요"),
    ConvExpr("Winter here is really cold.", "여기 겨울은 정말 추워요"),
    ConvExpr("Did you check the forecast?", "일기예보 확인했어요?"),
    ConvExpr("The forecast says rain tomorrow.", "내일 비 온대요"),
    ConvExpr("It's supposed to be sunny.", "화창할 거래요"),
    ConvExpr("It rained all day.", "하루 종일 비가 왔어요"),
    ConvExpr("It snowed all night.", "밤새 눈이 왔어요"),
    ConvExpr("The sky is clear today.", "오늘 하늘이 맑아요"),
    ConvExpr("There's a storm coming.", "폭풍이 오고 있어요"),
    ConvExpr("I forgot my umbrella.", "우산을 깜빡했어요"),
    ConvExpr("Don't forget your coat.", "코트 잊지 마세요"),
    ConvExpr("It's really humid today.", "오늘 정말 습해요"),
    ConvExpr("The wind is so strong.", "바람이 정말 강해요"),
    ConvExpr("I can't stand the heat.", "더위를 못 견디겠어요"),
    ConvExpr("I can't stand the cold.", "추위를 못 견디겠어요"),
    ConvExpr("Dress warmly today.", "오늘 따뜻하게 입으세요"),
    ConvExpr("It's a beautiful day.", "정말 좋은 날씨예요"),
    ConvExpr("It's a terrible day.", "정말 나쁜 날씨예요"),
    ConvExpr("The air quality is bad.", "공기가 안 좋아요"),
    ConvExpr("Fine dust is bad today.", "오늘 미세먼지가 심해요"),
    ConvExpr("It's supposed to clear up.", "곧 맑아질 거래요"),
    ConvExpr("The heat wave continues.", "폭염이 계속되고 있어요"),
    ConvExpr("A cold snap is coming.", "한파가 올 거예요"),
    ConvExpr("It's monsoon season now.", "지금 장마철이에요"),
    ConvExpr("I love the first snow.", "첫눈이 정말 좋아요"),
    ConvExpr("Autumn leaves are so pretty.", "단풍이 정말 예뻐요"),
    ConvExpr("It's getting colder outside.", "밖이 점점 추워져요"),
    ConvExpr("It's getting warmer outside.", "밖이 점점 따뜻해져요"),
    ConvExpr("Summer is almost over.", "여름이 거의 끝났어요"),
    ConvExpr("Winter is finally here.", "드디어 겨울이 왔어요"),
    ConvExpr("I can't wait for spring.", "봄이 정말 기다려져요"),
    ConvExpr("This humidity is unbearable.", "이 습도는 못 견디겠어요"),
    ConvExpr("It never snows here.", "여기는 눈이 안 와요"),
    ConvExpr("It rarely rains here.", "여기는 비가 거의 안 와요"),
    ConvExpr("Take a jacket, just in case.", "혹시 모르니 겉옷 챙기세요"),
    ConvExpr("The forecast wasn't accurate.", "일기예보가 틀렸어요"),
    ConvExpr("It's about to storm.", "곧 폭풍이 칠 것 같아요"),
    ConvExpr("This is unusual weather.", "이례적인 날씨네요"),
    ConvExpr("Typhoon season starts soon.", "곧 태풍철이 시작돼요"),
    ConvExpr("There's a typhoon coming.", "태풍이 오고 있어요"),
    ConvExpr("Lightning struck near here.", "근처에 번개가 쳤어요"),
  ],
  // 9번 주제
  [
    ConvExpr("tired", "피곤한"),
    ConvExpr("hungry", "배고픈"),
    ConvExpr("thirsty", "목마른"),
    ConvExpr("happy", "행복한"),
    ConvExpr("sad", "슬픈"),
    ConvExpr("angry", "화난"),
    ConvExpr("busy", "바쁜"),
    ConvExpr("sick", "아픈"),
    ConvExpr("sleepy", "졸린"),
    ConvExpr("bored", "지루한"),
    ConvExpr("nervous", "긴장한"),
    ConvExpr("relaxed", "편안한"),
    ConvExpr("full", "배부른"),
    ConvExpr("stressed", "스트레스 받은"),
    ConvExpr("excited", "신난"),
    ConvExpr("worried", "걱정되는"),
    ConvExpr("scared", "무서운"),
    ConvExpr("embarrassed", "창피한"),
    ConvExpr("confused", "헷갈리는"),
    ConvExpr("lonely", "외로운"),
    ConvExpr("proud", "뿌듯한"),
    ConvExpr("surprised", "놀란"),
    ConvExpr("calm", "차분한"),
    ConvExpr("dizzy", "어지러운"),
    ConvExpr("exhausted", "지친"),
    ConvExpr("energetic", "활기찬"),
    ConvExpr("upset", "속상한"),
    ConvExpr("content", "만족스러운"),
    ConvExpr("anxious", "불안한"),
    ConvExpr("grumpy", "짜증난"),
    ConvExpr("homesick", "향수병"),
    ConvExpr("overwhelmed", "벅찬"),
    ConvExpr("refreshed", "개운한"),
    ConvExpr("wide awake", "완전히 깬"),
    ConvExpr("I'm tired.", "피곤해요"),
    ConvExpr("I'm hungry.", "배고파요"),
    ConvExpr("I'm thirsty.", "목말라요"),
    ConvExpr("I'm happy.", "행복해요"),
    ConvExpr("I'm sad.", "슬퍼요"),
    ConvExpr("I'm busy.", "바빠요"),
    ConvExpr("I'm sick.", "아파요"),
    ConvExpr("I'm sleepy.", "졸려요"),
    ConvExpr("I'm bored.", "지루해요"),
    ConvExpr("Are you okay?", "괜찮아요?"),
    ConvExpr("I'm not feeling well.", "몸이 안 좋아요"),
    ConvExpr("I'm feeling better now.", "이제 좀 나아요"),
    ConvExpr("I feel great today.", "오늘 기분 정말 좋아요"),
    ConvExpr("I feel terrible today.", "오늘 기분 정말 안 좋아요"),
    ConvExpr("What's wrong?", "무슨 일이에요?"),
    ConvExpr("Nothing's wrong.", "아무 일도 아니에요"),
    ConvExpr("I'm so tired today.", "오늘 정말 피곤해요"),
    ConvExpr("I'm really hungry now.", "지금 정말 배고파요"),
    ConvExpr("I'm a little nervous.", "조금 긴장돼요"),
    ConvExpr("I'm really excited.", "정말 신나요"),
    ConvExpr("I'm feeling stressed.", "스트레스 받아요"),
    ConvExpr("I need some rest.", "좀 쉬어야 해요"),
    ConvExpr("I need some sleep.", "잠을 좀 자야 해요"),
    ConvExpr("I have a headache.", "머리가 아파요"),
    ConvExpr("I have a stomachache.", "배가 아파요"),
    ConvExpr("I have a fever.", "열이 나요"),
    ConvExpr("I feel dizzy.", "어지러워요"),
    ConvExpr("I feel a bit sick.", "좀 아픈 것 같아요"),
    ConvExpr("I'm too busy today.", "오늘 너무 바빠요"),
    ConvExpr("I'm very worried.", "정말 걱정돼요"),
    ConvExpr("I'm a bit scared.", "조금 무서워요"),
    ConvExpr("I'm feeling much calmer.", "훨씬 차분해졌어요"),
    ConvExpr("I'm proud of you.", "자랑스러워요"),
    ConvExpr("I'm proud of myself.", "제 자신이 뿌듯해요"),
    ConvExpr("I feel so lonely.", "너무 외로워요"),
    ConvExpr("I'm in a good mood.", "기분이 좋아요"),
    ConvExpr("I'm in a bad mood.", "기분이 안 좋아요"),
    ConvExpr("I'm feeling a bit down.", "좀 기운이 없어요"),
    ConvExpr("Don't be upset.", "속상해하지 마세요"),
    ConvExpr("I got so surprised.", "정말 놀랐어요"),
    ConvExpr("I'm still upset about it.", "아직도 속상해요"),
    ConvExpr("I feel much better.", "훨씬 나아졌어요"),
    ConvExpr("I feel much worse.", "훨씬 나빠졌어요"),
    ConvExpr("I couldn't sleep last night.", "어젯밤 잠을 못 잤어요"),
    ConvExpr("I slept really well.", "정말 잘 잤어요"),
    ConvExpr("I'm exhausted from work.", "일 때문에 지쳤어요"),
    ConvExpr("I'm running on no sleep.", "잠을 하나도 못 잤어요"),
    ConvExpr("I feel refreshed today.", "오늘 개운해요"),
    ConvExpr("I'm wide awake now.", "이제 완전히 깼어요"),
    ConvExpr("I feel a little embarrassed.", "조금 창피해요"),
    ConvExpr("I'm confused right now.", "지금 좀 헷갈려요"),
    ConvExpr("I don't feel like eating.", "먹고 싶지 않아요"),
    ConvExpr("I don't feel like talking.", "말하고 싶지 않아요"),
    ConvExpr("I need some fresh air.", "바람 좀 쐬어야겠어요"),
    ConvExpr("I need a break.", "잠깐 쉬어야 해요"),
    ConvExpr("I've had a long day.", "정말 힘든 하루였어요"),
    ConvExpr("Today was a good day.", "오늘은 좋은 날이었어요"),
    ConvExpr("I'm overwhelmed with work.", "일이 너무 벅차요"),
    ConvExpr("I feel homesick sometimes.", "가끔 향수병이 나요"),
    ConvExpr("I miss my family.", "가족이 그리워요"),
    ConvExpr("I feel much calmer now.", "이제 훨씬 차분해요"),
    ConvExpr("I'm grumpy in the morning.", "아침엔 짜증나요"),
    ConvExpr("I always feel sleepy at noon.", "항상 낮에 졸려요"),
    ConvExpr("I get anxious before tests.", "시험 전엔 불안해요"),
    ConvExpr("I feel content with life.", "삶에 만족해요"),
    ConvExpr("I'm energetic in the morning.", "아침엔 활기차요"),
  ],
  // 10번 주제
  [
    ConvExpr("sure", "그럼요"),
    ConvExpr("of course", "물론이죠"),
    ConvExpr("no problem", "문제없어요"),
    ConvExpr("favor", "부탁"),
    ConvExpr("permission", "허락"),
    ConvExpr("thanks anyway", "그래도 감사해요"),
    ConvExpr("go ahead", "그렇게 하세요"),
    ConvExpr("never mind", "신경 쓰지 마세요"),
    ConvExpr("hold on", "잠시만요"),
    ConvExpr("one second", "잠깐만요"),
    ConvExpr("after you", "먼저 하세요"),
    ConvExpr("no worries", "걱정 마세요"),
    ConvExpr("sounds good", "좋아요"),
    ConvExpr("not at all", "전혀요"),
    ConvExpr("feel free", "편하게 하세요"),
    ConvExpr("if possible", "가능하면"),
    ConvExpr("no rush", "서두르지 마세요"),
    ConvExpr("take your time", "천천히 하세요"),
    ConvExpr("any time", "언제든지요"),
    ConvExpr("my pleasure", "천만에요"),
    ConvExpr("happy to help", "기꺼이 도와줄게요"),
    ConvExpr("small favor", "작은 부탁"),
    ConvExpr("quick favor", "간단한 부탁"),
    ConvExpr("big favor", "큰 부탁"),
    ConvExpr("your call", "당신 결정이에요"),
    ConvExpr("up to you", "당신에게 달렸어요"),
    ConvExpr("just checking", "그냥 확인차예요"),
    ConvExpr("whenever's fine", "언제든 괜찮아요"),
    ConvExpr("one favor", "한 가지 부탁"),
    ConvExpr("last favor", "마지막 부탁"),
    ConvExpr("quick question", "간단한 질문"),
    ConvExpr("Can I help you?", "도와드릴까요?"),
    ConvExpr("Can I ask you something?", "뭐 좀 물어봐도 돼요?"),
    ConvExpr("Can I sit here?", "여기 앉아도 돼요?"),
    ConvExpr("Can I use your phone?", "전화 좀 써도 돼요?"),
    ConvExpr("Can I borrow your pen?", "펜 좀 빌려도 돼요?"),
    ConvExpr("Can I open the window?", "창문 열어도 돼요?"),
    ConvExpr("Can I close the door?", "문 닫아도 돼요?"),
    ConvExpr("Can I get some water?", "물 좀 마셔도 돼요?"),
    ConvExpr("Can I take a picture?", "사진 찍어도 돼요?"),
    ConvExpr("Can I ask a favor?", "부탁 하나 해도 돼요?"),
    ConvExpr("Could you help me?", "좀 도와주시겠어요?"),
    ConvExpr("Could you repeat that?", "다시 말씀해 주시겠어요?"),
    ConvExpr("Could you speak slower?", "천천히 말씀해 주시겠어요?"),
    ConvExpr("Could you wait a moment?", "잠깐 기다려 주시겠어요?"),
    ConvExpr("Could you pass the salt?", "소금 좀 건네주시겠어요?"),
    ConvExpr("Could you turn down the music?", "음악 좀 줄여주시겠어요?"),
    ConvExpr("Could you keep it down?", "좀 조용히 해주시겠어요?"),
    ConvExpr("Could you open the door?", "문 좀 열어주시겠어요?"),
    ConvExpr("Could you hold this for me?", "이거 좀 들어주시겠어요?"),
    ConvExpr("Could you check this for me?", "이거 좀 확인해주시겠어요?"),
    ConvExpr("I'd like some help.", "도움이 좀 필요해요"),
    ConvExpr("I'd like to ask something.", "뭐 좀 물어보고 싶어요"),
    ConvExpr("I'd like a moment, please.", "잠깐 시간 좀 주세요"),
    ConvExpr("I'd like to sit here.", "여기 앉고 싶어요"),
    ConvExpr("I'd like to use this.", "이거 쓰고 싶어요"),
    ConvExpr("I'd like your opinion.", "의견을 듣고 싶어요"),
    ConvExpr("I'd like a favor.", "부탁이 있어요"),
    ConvExpr("Do you mind if I sit?", "앉아도 될까요?"),
    ConvExpr("Do you mind if I smoke?", "담배 피워도 될까요?"),
    ConvExpr("Do you mind waiting outside?", "밖에서 기다려주시겠어요?"),
    ConvExpr("Do you mind closing the door?", "문 좀 닫아주시겠어요?"),
    ConvExpr("Do you mind if I ask?", "물어봐도 될까요?"),
    ConvExpr("Would you mind helping me?", "좀 도와주실 수 있어요?"),
    ConvExpr("Would you mind repeating that?", "다시 말씀해주실 수 있어요?"),
    ConvExpr("Let me help you.", "제가 도와드릴게요"),
    ConvExpr("Let me check that.", "제가 확인해볼게요"),
    ConvExpr("Let me think about it.", "좀 생각해볼게요"),
    ConvExpr("Let me get that for you.", "제가 가져다드릴게요"),
    ConvExpr("Let me know if needed.", "필요하면 알려주세요"),
    ConvExpr("Let me handle this.", "제가 처리할게요"),
    ConvExpr("May I come in?", "들어가도 될까요?"),
    ConvExpr("May I ask a question?", "질문 하나 해도 될까요?"),
    ConvExpr("May I have your name?", "이름 좀 알려주시겠어요?"),
    ConvExpr("Is it okay if I leave?", "가도 괜찮아요?"),
    ConvExpr("Is it okay to call you?", "전화해도 괜찮아요?"),
    ConvExpr("Would it be okay to stay?", "있어도 괜찮을까요?"),
    ConvExpr("Would you do me a favor?", "부탁 하나 들어주시겠어요?"),
    ConvExpr("Can you do me a favor?", "부탁 좀 들어줄래요?"),
    ConvExpr("Mind if I join you?", "같이 앉아도 될까요?"),
    ConvExpr("Would you mind moving over?", "좀 옆으로 가주시겠어요?"),
    ConvExpr("Would it be possible to reschedule?", "일정을 바꿀 수 있을까요?"),
    ConvExpr("Is there any way to help?", "도울 방법이 있을까요?"),
    ConvExpr("I was wondering if you could.", "혹시 가능하실까요?"),
    ConvExpr("Would you be able to help?", "도와주실 수 있어요?"),
    ConvExpr("Would you be able to come?", "오실 수 있어요?"),
    ConvExpr("Sure, no problem at all.", "그럼요, 문제없어요"),
    ConvExpr("Of course, go right ahead.", "물론이죠, 그렇게 하세요"),
    ConvExpr("Sorry, I can't right now.", "죄송해요, 지금은 안 돼요"),
    ConvExpr("Sorry, could you say that again?", "죄송한데 다시 말씀해주시겠어요?"),
    ConvExpr("Thanks, I really appreciate it.", "정말 감사해요"),
    ConvExpr("That would be great, thanks.", "그럼 좋죠, 감사해요"),
    ConvExpr("That's very kind of you.", "정말 친절하시네요"),
    ConvExpr("I really appreciate your help.", "도와주셔서 정말 감사해요"),
    ConvExpr("Please feel free to ask.", "편하게 물어보세요"),
    ConvExpr("Please let me know anytime.", "언제든 알려주세요"),
    ConvExpr("Take your time, no rush.", "천천히 하세요, 서두르지 마세요"),
    ConvExpr("Whenever is fine for you.", "편하실 때 아무 때나요"),
    ConvExpr("It's totally fine with me.", "저는 전혀 괜찮아요"),
    ConvExpr("I don't mind at all.", "저는 전혀 상관없어요"),
  ],
];
