// 자동 생성 데이터 — 성인 영어회화 표현 묶음.
// 실전 회화 2000 — 주제 11~20 (주제당 100개)

import 'conversation_data.dart';

/// 실전 회화 2000 — 주제 11~20
const List<List<ConvExpr>> convTier2 = [
  // 11번 주제
  [
    ConvExpr("boarding pass", "탑승권"),
    ConvExpr("check-in counter", "체크인 카운터"),
    ConvExpr("departure gate", "출발 게이트"),
    ConvExpr("baggage claim", "수하물 찾는 곳"),
    ConvExpr("security checkpoint", "보안 검색대"),
    ConvExpr("carry-on bag", "기내용 가방"),
    ConvExpr("checked baggage", "위탁 수하물"),
    ConvExpr("window seat", "창가 좌석"),
    ConvExpr("aisle seat", "통로 쪽 좌석"),
    ConvExpr("connecting flight", "환승 항공편"),
    ConvExpr("layover", "경유"),
    ConvExpr("customs", "세관"),
    ConvExpr("immigration", "출입국 심사"),
    ConvExpr("overhead bin", "짐칸"),
    ConvExpr("flight attendant", "승무원"),
    ConvExpr("delayed flight", "지연된 항공편"),
    ConvExpr("final boarding call", "마지막 탑승 안내"),
    ConvExpr("duty-free shop", "면세점"),
    ConvExpr("one-way ticket", "편도 항공권"),
    ConvExpr("excess baggage fee", "초과 수하물 요금"),
    ConvExpr("I'd like to check in.", "체크인하고 싶어요"),
    ConvExpr("Here's my passport.", "여권 여기 있어요"),
    ConvExpr("I have one bag to check.", "부칠 짐 하나 있어요"),
    ConvExpr("Is my flight full?", "비행기가 다 찼어요?"),
    ConvExpr("Can I upgrade my seat?", "좌석 업그레이드할 수 있어요?"),
    ConvExpr("I'd prefer an aisle seat.", "통로 자리가 좋아요"),
    ConvExpr("Can we sit together?", "같이 앉을 수 있어요?"),
    ConvExpr("This is my e-ticket.", "이게 제 전자 항공권이에요"),
    ConvExpr("Print my boarding pass, please.", "탑승권 좀 출력해 주세요"),
    ConvExpr("How many bags can I check?", "짐 몇 개까지 부쳐요?"),
    ConvExpr("Is my bag overweight?", "제 짐이 초과됐나요?"),
    ConvExpr("What's the weight limit?", "무게 제한이 얼마예요?"),
    ConvExpr("I only have a carry-on.", "기내용 짐만 있어요"),
    ConvExpr("Where's the baggage claim?", "수하물 찾는 곳이 어디예요?"),
    ConvExpr("My suitcase hasn't arrived yet.", "제 캐리어가 아직 안 왔어요"),
    ConvExpr("My bag is lost.", "제 가방을 잃어버렸어요"),
    ConvExpr("It's a black hard-shell suitcase.", "검은색 하드케이스 캐리어예요"),
    ConvExpr("Do I take off my shoes?", "신발을 벗어야 하나요?"),
    ConvExpr("Please empty your pockets.", "주머니를 비워 주세요"),
    ConvExpr("Take your laptop out, please.", "노트북을 꺼내 주세요"),
    ConvExpr("Is this line for security?", "보안 검색 줄이 여기예요?"),
    ConvExpr("I have liquids in my bag.", "가방에 액체류가 있어요"),
    ConvExpr("Liquids must be in a bag.", "액체는 봉지에 넣어야 해요"),
    ConvExpr("Please walk through the scanner.", "검색대를 통과해 주세요"),
    ConvExpr("Am I clear to go?", "통과해도 되나요?"),
    ConvExpr("Which gate does it leave from?", "몇 번 게이트에서 출발해요?"),
    ConvExpr("What time does boarding start?", "탑승은 몇 시에 시작해요?"),
    ConvExpr("Is this the right gate?", "여기가 맞는 게이트예요?"),
    ConvExpr("The gate has been changed.", "게이트가 바뀌었어요"),
    ConvExpr("Where did the gate change to?", "게이트가 어디로 바뀌었어요?"),
    ConvExpr("Boarding is closing soon.", "탑승이 곧 마감돼요"),
    ConvExpr("I'm running late for my flight.", "비행기 시간에 늦었어요"),
    ConvExpr("Please hurry to the gate.", "게이트로 서둘러 가 주세요"),
    ConvExpr("Can you hold the flight?", "비행기를 잠깐 기다려 줄 수 있어요?"),
    ConvExpr("I'm in the wrong line.", "줄을 잘못 섰어요"),
    ConvExpr("Is my flight on time?", "제 비행기 제시간인가요?"),
    ConvExpr("The flight has been delayed.", "비행기가 지연됐어요"),
    ConvExpr("How long is the delay?", "얼마나 지연되나요?"),
    ConvExpr("Has my flight been canceled?", "제 비행기가 취소됐나요?"),
    ConvExpr("Is there a later flight?", "더 늦은 비행기 있어요?"),
    ConvExpr("Can you put me on standby?", "대기자 명단에 올려 주세요"),
    ConvExpr("I missed my connecting flight.", "환승 비행기를 놓쳤어요"),
    ConvExpr("What's my new departure time?", "새 출발 시간이 언제예요?"),
    ConvExpr("May I see your passport?", "여권 좀 보여 주시겠어요?"),
    ConvExpr("What's the purpose of your visit?", "방문 목적이 뭐예요?"),
    ConvExpr("I'm here on vacation.", "휴가로 왔어요"),
    ConvExpr("I'm here for business.", "출장으로 왔어요"),
    ConvExpr("How long will you stay?", "얼마나 머무실 건가요?"),
    ConvExpr("I'll be staying for a week.", "일주일 머물 거예요"),
    ConvExpr("Where will you be staying?", "어디서 지내실 건가요?"),
    ConvExpr("I'm staying at a hotel downtown.", "시내 호텔에 묵어요"),
    ConvExpr("Do you have anything to declare?", "신고할 물건 있으세요?"),
    ConvExpr("I have nothing to declare.", "신고할 게 없어요"),
    ConvExpr("Could I get some water?", "물 좀 주시겠어요?"),
    ConvExpr("Can I have a blanket?", "담요 하나 주시겠어요?"),
    ConvExpr("My headphones aren't working.", "헤드폰이 작동을 안 해요"),
    ConvExpr("Could you turn up the volume?", "소리 좀 키워 주시겠어요?"),
    ConvExpr("Can I recline my seat?", "의자를 젖혀도 되나요?"),
    ConvExpr("Please fasten your seat belt.", "안전벨트를 매 주세요"),
    ConvExpr("We're about to hit turbulence.", "곧 난기류를 만날 거예요"),
    ConvExpr("Please put your seat upright.", "의자를 세워 주세요"),
    ConvExpr("Could I switch seats with him?", "저 사람이랑 자리 바꿀 수 있어요?"),
    ConvExpr("What's for the in-flight meal?", "기내식은 뭐예요?"),
    ConvExpr("I'd like the chicken, please.", "치킨으로 주세요"),
    ConvExpr("Could I get another drink?", "음료 하나 더 주시겠어요?"),
    ConvExpr("We're beginning our descent.", "곧 착륙을 시작해요"),
    ConvExpr("Please remain seated until we stop.", "완전히 멈출 때까지 앉아 계세요"),
    ConvExpr("Welcome to Seoul.", "서울에 오신 걸 환영해요"),
    ConvExpr("Where's the exit?", "출구가 어디예요?"),
    ConvExpr("Where can I get a taxi?", "택시는 어디서 타요?"),
    ConvExpr("Is there a hotel shuttle?", "호텔 가는 셔틀 있어요?"),
    ConvExpr("Where's the currency exchange?", "환전소가 어디예요?"),
    ConvExpr("I need to exchange some money.", "환전 좀 하고 싶어요"),
    ConvExpr("Where can I rent a car?", "렌터카는 어디서 빌려요?"),
    ConvExpr("Do you have a city map?", "시내 지도 있어요?"),
    ConvExpr("How do I get to downtown?", "시내로 어떻게 가요?"),
    ConvExpr("Is there free Wi-Fi here?", "여기 무료 와이파이 있어요?"),
    ConvExpr("Where can I charge my phone?", "핸드폰 어디서 충전해요?"),
    ConvExpr("Thanks for flying with us.", "이용해 주셔서 감사합니다"),
    ConvExpr("My flight got bumped to standby.", "제 비행기가 대기로 밀렸어요"),
  ],
  // 12번 주제
  [
    ConvExpr("hotel reservation", "호텔 예약"),
    ConvExpr("check-in time", "체크인 시간"),
    ConvExpr("check-out time", "체크아웃 시간"),
    ConvExpr("front desk", "프런트 데스크"),
    ConvExpr("room key", "객실 열쇠"),
    ConvExpr("key card", "키 카드"),
    ConvExpr("single room", "싱글 룸"),
    ConvExpr("double room", "더블 룸"),
    ConvExpr("twin room", "트윈 룸"),
    ConvExpr("suite", "스위트룸"),
    ConvExpr("room service", "룸서비스"),
    ConvExpr("wake-up call", "모닝콜"),
    ConvExpr("late checkout", "레이트 체크아웃"),
    ConvExpr("nonsmoking room", "금연실"),
    ConvExpr("extra bed", "엑스트라 베드"),
    ConvExpr("hotel amenities", "호텔 편의시설"),
    ConvExpr("minibar", "미니바"),
    ConvExpr("housekeeping", "하우스키핑"),
    ConvExpr("hotel lobby", "호텔 로비"),
    ConvExpr("room upgrade", "객실 업그레이드"),
    ConvExpr("I have a reservation.", "예약했어요"),
    ConvExpr("The reservation is under Kim.", "김 씨 이름으로 예약했어요"),
    ConvExpr("Do you have any rooms available?", "빈 방 있어요?"),
    ConvExpr("I'd like a nonsmoking room.", "금연실로 주세요"),
    ConvExpr("I'd like an ocean view.", "바다 전망으로 주세요"),
    ConvExpr("What time is check-in?", "체크인이 몇 시예요?"),
    ConvExpr("What time is checkout?", "체크아웃이 몇 시예요?"),
    ConvExpr("Can I check in early?", "일찍 체크인할 수 있어요?"),
    ConvExpr("Can I get a late checkout?", "레이트 체크아웃 가능해요?"),
    ConvExpr("Here's my ID.", "신분증 여기 있어요"),
    ConvExpr("Could I get two key cards?", "키 카드 두 개 주세요"),
    ConvExpr("What floor is my room on?", "제 방이 몇 층이에요?"),
    ConvExpr("Is breakfast included?", "조식 포함인가요?"),
    ConvExpr("What time is breakfast served?", "조식은 몇 시예요?"),
    ConvExpr("Where is the elevator?", "엘리베이터가 어디예요?"),
    ConvExpr("Can someone help with my bags?", "짐 좀 옮겨 주실 수 있어요?"),
    ConvExpr("Is there parking available?", "주차 가능해요?"),
    ConvExpr("Is there an airport shuttle?", "공항 셔틀 있어요?"),
    ConvExpr("What's the Wi-Fi password?", "와이파이 비밀번호가 뭐예요?"),
    ConvExpr("Can I get a wake-up call?", "모닝콜 해 주시겠어요?"),
    ConvExpr("Please wake me at seven.", "일곱 시에 깨워 주세요"),
    ConvExpr("I'd like room service, please.", "룸서비스 부탁드려요"),
    ConvExpr("Could you send up some towels?", "수건 좀 갖다주시겠어요?"),
    ConvExpr("We need extra pillows.", "베개 더 필요해요"),
    ConvExpr("Can I get an extra blanket?", "담요 하나 더 주시겠어요?"),
    ConvExpr("The room isn't clean.", "방이 깨끗하지 않아요"),
    ConvExpr("Could you clean the room again?", "방을 다시 청소해 주시겠어요?"),
    ConvExpr("The air conditioner isn't working.", "에어컨이 고장 났어요"),
    ConvExpr("The heater isn't working.", "히터가 고장 났어요"),
    ConvExpr("There's no hot water.", "온수가 안 나와요"),
    ConvExpr("The toilet is clogged.", "변기가 막혔어요"),
    ConvExpr("The sink is leaking.", "세면대에서 물이 새요"),
    ConvExpr("The TV won't turn on.", "텔레비전이 안 켜져요"),
    ConvExpr("The remote is missing.", "리모컨이 없어요"),
    ConvExpr("There's a strange smell.", "이상한 냄새가 나요"),
    ConvExpr("It's too noisy next door.", "옆방이 너무 시끄러워요"),
    ConvExpr("Can I switch to another room?", "다른 방으로 옮겨 주시겠어요?"),
    ConvExpr("I'd like to switch rooms.", "방을 바꾸고 싶어요"),
    ConvExpr("The safe won't open.", "금고가 안 열려요"),
    ConvExpr("I forgot the safe code.", "금고 비밀번호를 잊어버렸어요"),
    ConvExpr("Can you unlock the safe?", "금고 좀 열어 주시겠어요?"),
    ConvExpr("My key card isn't working.", "키 카드가 작동을 안 해요"),
    ConvExpr("I'm locked out of my room.", "방에서 잠겼어요"),
    ConvExpr("Could I get a new key?", "새 열쇠 하나 주시겠어요?"),
    ConvExpr("Does the hotel have a gym?", "호텔에 헬스장 있어요?"),
    ConvExpr("Where's the swimming pool?", "수영장이 어디예요?"),
    ConvExpr("What time does the pool close?", "수영장은 몇 시에 닫아요?"),
    ConvExpr("Is there a spa here?", "여기 스파 있어요?"),
    ConvExpr("Can I book a massage?", "마사지 예약할 수 있어요?"),
    ConvExpr("Is there a laundry service?", "세탁 서비스 있어요?"),
    ConvExpr("I need my clothes dry-cleaned.", "드라이클리닝 맡기고 싶어요"),
    ConvExpr("When will my laundry be ready?", "세탁물은 언제 나와요?"),
    ConvExpr("Can you recommend a good restaurant?", "괜찮은 식당 추천해 주시겠어요?"),
    ConvExpr("Is there a restaurant here?", "호텔에 식당 있어요?"),
    ConvExpr("Can I make a dinner reservation?", "저녁 예약할 수 있어요?"),
    ConvExpr("What's the minibar policy?", "미니바는 어떻게 계산돼요?"),
    ConvExpr("I didn't use the minibar.", "미니바 안 썼어요"),
    ConvExpr("There's a charge I don't recognize.", "모르는 요금이 있어요"),
    ConvExpr("Could you check my bill?", "제 청구서 확인해 주시겠어요?"),
    ConvExpr("I'd like an itemized receipt.", "항목별 영수증 주세요"),
    ConvExpr("Can I pay with a card?", "카드로 결제할 수 있어요?"),
    ConvExpr("I'd like to extend my stay.", "하루 더 묵고 싶어요"),
    ConvExpr("Can I check out early?", "하루 일찍 체크아웃할 수 있어요?"),
    ConvExpr("Could you store my luggage?", "짐 좀 맡아 주시겠어요?"),
    ConvExpr("I'll pick it up later.", "나중에 찾으러 올게요"),
    ConvExpr("Is early check-in possible?", "더 일찍 체크인 가능해요?"),
    ConvExpr("I left something in my room.", "방에 물건을 두고 왔어요"),
    ConvExpr("Can someone check my room?", "방 좀 확인해 주시겠어요?"),
    ConvExpr("I lost my key card.", "키 카드를 잃어버렸어요"),
    ConvExpr("Do you have a business center?", "비즈니스 센터 있어요?"),
    ConvExpr("Can I print a document here?", "여기서 문서 출력할 수 있어요?"),
    ConvExpr("Is there a fax machine?", "팩스기 있어요?"),
    ConvExpr("Do you accept walk-ins?", "워크인 손님도 받아요?"),
    ConvExpr("Is there a cancellation fee?", "취소 수수료 있어요?"),
    ConvExpr("What's your cancellation policy?", "취소 규정이 어떻게 되나요?"),
    ConvExpr("I'd like to cancel my reservation.", "예약을 취소하고 싶어요"),
    ConvExpr("I'd like a refund, please.", "환불해 주시겠어요?"),
    ConvExpr("The room doesn't match the photos.", "사진과 방이 달라요"),
    ConvExpr("This isn't the room I booked.", "제가 예약한 방이 아니에요"),
    ConvExpr("Can you upgrade me for free?", "무료로 업그레이드해 주시겠어요?"),
  ],
  // 13번 주제
  [
    ConvExpr("meeting", "회의"),
    ConvExpr("deadline", "마감일"),
    ConvExpr("coworker", "직장 동료"),
    ConvExpr("schedule", "일정"),
    ConvExpr("project", "프로젝트"),
    ConvExpr("report", "보고서"),
    ConvExpr("supervisor", "상사"),
    ConvExpr("client", "고객"),
    ConvExpr("overtime", "야근"),
    ConvExpr("break room", "휴게실"),
    ConvExpr("paperwork", "서류 작업"),
    ConvExpr("day off", "휴가"),
    ConvExpr("team lead", "팀장"),
    ConvExpr("conference room", "회의실"),
    ConvExpr("sick leave", "병가"),
    ConvExpr("workload", "업무량"),
    ConvExpr("performance review", "인사평가"),
    ConvExpr("business trip", "출장"),
    ConvExpr("lunch break", "점심시간"),
    ConvExpr("work shift", "근무 교대"),
    ConvExpr("I'm running late.", "좀 늦어요"),
    ConvExpr("Let's start the meeting.", "회의 시작할게요"),
    ConvExpr("Do you have a minute?", "잠깐 시간 있어요"),
    ConvExpr("I'll send the report.", "보고서 보낼게요"),
    ConvExpr("Can we reschedule?", "일정 다시 잡을까요"),
    ConvExpr("I'm on my lunch break.", "점심시간이에요"),
    ConvExpr("He's out of the office.", "자리 비웠어요"),
    ConvExpr("I need a day off.", "휴가가 필요해요"),
    ConvExpr("The deadline is tomorrow.", "마감일이 내일이에요"),
    ConvExpr("Let's take a break.", "잠깐 쉴까요"),
    ConvExpr("I'm swamped today.", "오늘 너무 바빠요"),
    ConvExpr("Can you cover for me?", "제 대신 해줄 수 있어요"),
    ConvExpr("I'll get back to you.", "다시 연락드릴게요"),
    ConvExpr("Let's touch base later.", "나중에 다시 얘기해요"),
    ConvExpr("I'm behind schedule.", "일정이 늦어졌어요"),
    ConvExpr("He's in a meeting.", "회의 중이에요"),
    ConvExpr("I have way too much work.", "일이 너무 많아요"),
    ConvExpr("Let's circle back tomorrow.", "내일 다시 얘기해요"),
    ConvExpr("I'll loop you in.", "참조로 넣을게요"),
    ConvExpr("Can you cc me on that?", "저도 참조 넣어주세요"),
    ConvExpr("I'm working from home today.", "오늘 재택근무예요"),
    ConvExpr("Let's push the deadline back.", "마감일 미룰게요"),
    ConvExpr("I need to finish by Friday.", "금요일까지 끝내야 해요"),
    ConvExpr("Can we meet first thing tomorrow?", "내일 아침 일찍 만날까요"),
    ConvExpr("I'll have it ready by noon.", "정오까지 준비할게요"),
    ConvExpr("Sorry, I'm slammed right now.", "죄송해요 지금 너무 바빠요"),
    ConvExpr("Let's wrap up the meeting.", "회의 마무리할게요"),
    ConvExpr("I'll follow up with the client.", "고객한테 다시 연락할게요"),
    ConvExpr("He's taking sick leave this week.", "이번 주 병가예요"),
    ConvExpr("We're short-staffed today.", "오늘 인원이 부족해요"),
    ConvExpr("I need my boss's approval.", "상사 승인이 필요해요"),
    ConvExpr("Let's divide up the tasks.", "업무를 나눠요"),
    ConvExpr("I'm still waiting on approval.", "아직 승인 기다리고 있어요"),
    ConvExpr("Can you send that over ASAP?", "그거 최대한 빨리 보내주세요"),
    ConvExpr("I'll draft an email about it.", "그것에 대해 메일 작성할게요"),
    ConvExpr("We're overloaded with work this month.", "이번 달 업무가 넘쳐요"),
    ConvExpr("Let's set up a quick call.", "짧게 통화 잡을까요"),
    ConvExpr("I pulled an all-nighter finishing this.", "이거 끝내려고 밤샜어요"),
    ConvExpr("He got promoted last month.", "지난달에 승진했어요"),
    ConvExpr("I'm up for a raise soon.", "곧 연봉 인상 대상이에요"),
    ConvExpr("Let's book the conference room.", "회의실 예약할게요"),
    ConvExpr("I'll take minutes for the meeting.", "회의록 제가 작성할게요"),
    ConvExpr("She's on maternity leave right now.", "지금 출산 휴가 중이에요"),
    ConvExpr("Let's push this meeting to three.", "이 회의 세시로 미룰게요"),
    ConvExpr("I have back-to-back meetings today.", "오늘 회의가 연달아 있어요"),
    ConvExpr("Let's brainstorm some ideas first.", "먼저 아이디어를 짜볼까요"),
    ConvExpr("I need your sign-off on this.", "이거 승인해주셔야 해요"),
    ConvExpr("We're still ironing out the details.", "아직 세부사항 조율 중이에요"),
    ConvExpr("Let's put this on hold.", "이건 일단 보류할게요"),
    ConvExpr("I'll cc the whole team.", "팀 전체 참조로 넣을게요"),
    ConvExpr("He's handling the client account now.", "이제 그 고객을 맡고 있어요"),
    ConvExpr("Let's revisit this next quarter.", "다음 분기에 다시 논의해요"),
    ConvExpr("I'm off on a business trip.", "출장 떠나요"),
    ConvExpr("Let's hit the ground running.", "바로 시작해요"),
    ConvExpr("Let's touch on the budget next.", "다음은 예산 얘기해요"),
    ConvExpr("I'll flag any issues right away.", "문제 생기면 바로 알릴게요"),
    ConvExpr("She's covering my shift on Friday.", "금요일 제 근무 대신 해줘요"),
    ConvExpr("Let's keep each other posted.", "서로 계속 알려줘요"),
    ConvExpr("I need to clock out early.", "일찍 퇴근해야 해요"),
    ConvExpr("We're understaffed on the night shift.", "야간 근무 인력이 부족해요"),
    ConvExpr("Let's get on the same page.", "모두 생각을 맞춰봐요"),
    ConvExpr("I'll bring it up next time.", "다음에 얘기할게요"),
    ConvExpr("He's out sick again today.", "오늘도 아파서 결근했어요"),
    ConvExpr("Let's touch base before the deadline.", "마감 전에 다시 얘기해요"),
    ConvExpr("I'm juggling three projects right now.", "지금 프로젝트 세 개 맡고 있어요"),
    ConvExpr("We need to streamline this process.", "이 절차를 간소화해야 해요"),
    ConvExpr("Let's table this until next week.", "다음 주까지 보류해요"),
    ConvExpr("I have a one-on-one today.", "오늘 개별 면담 있어요"),
    ConvExpr("She's stepping down from her role.", "그 자리에서 물러나요"),
    ConvExpr("Let's map out the timeline together.", "일정표를 같이 짜봐요"),
    ConvExpr("I'll need overtime approval for this.", "야근 승인이 필요해요"),
    ConvExpr("We're behind on this quarter's targets.", "이번 분기 목표가 늦어지고 있어요"),
    ConvExpr("Let's delegate some of these tasks.", "업무 일부를 위임해요"),
    ConvExpr("I'm cutting it close today.", "오늘 시간이 아슬아슬해요"),
    ConvExpr("He's out of the loop lately.", "요즘 그는 소식을 잘 몰라요"),
    ConvExpr("Let's touch base once we know.", "결과 나오면 다시 얘기해요"),
    ConvExpr("I'll clear this with HR first.", "먼저 인사팀 확인할게요"),
    ConvExpr("We're rolling out a new system.", "새 시스템 도입해요"),
    ConvExpr("Let's iron out the schedule conflicts.", "일정 겹치는 거 조율해요"),
    ConvExpr("I'm swamped with paperwork this week.", "이번 주 서류에 파묻혀 있어요"),
  ],
  // 14번 주제
  [
    ConvExpr("phone call", "전화 통화"),
    ConvExpr("text message", "문자"),
    ConvExpr("email", "이메일"),
    ConvExpr("voicemail", "음성 메시지"),
    ConvExpr("missed call", "부재중 전화"),
    ConvExpr("phone number", "전화번호"),
    ConvExpr("attachment", "첨부파일"),
    ConvExpr("inbox", "받은 편지함"),
    ConvExpr("subject line", "제목"),
    ConvExpr("reply", "답장"),
    ConvExpr("forward", "전달"),
    ConvExpr("contact", "연락처"),
    ConvExpr("speakerphone", "스피커폰"),
    ConvExpr("call back", "다시 전화"),
    ConvExpr("group chat", "단체 채팅"),
    ConvExpr("spam", "스팸"),
    ConvExpr("signature", "서명"),
    ConvExpr("cc", "참조"),
    ConvExpr("bcc", "숨은 참조"),
    ConvExpr("ringtone", "벨소리"),
    ConvExpr("I'll call you back.", "다시 전화할게요"),
    ConvExpr("Can you hear me?", "제 목소리 들려요"),
    ConvExpr("I missed your call.", "전화를 못 받았어요"),
    ConvExpr("Text me later.", "나중에 문자해요"),
    ConvExpr("I'll send you an email.", "이메일 보낼게요"),
    ConvExpr("Hold on a second.", "잠깐만요"),
    ConvExpr("The line is busy.", "통화 중이에요"),
    ConvExpr("I can't hear you well.", "잘 안 들려요"),
    ConvExpr("Let me call you right back.", "바로 다시 전화할게요"),
    ConvExpr("I left you a voicemail.", "음성 메시지 남겼어요"),
    ConvExpr("Can you repeat that?", "다시 말해줄래요"),
    ConvExpr("I'm losing signal.", "신호가 약해요"),
    ConvExpr("Check your inbox.", "편지함 확인해보세요"),
    ConvExpr("I'll text you the address.", "주소 문자로 보낼게요"),
    ConvExpr("Please call me back.", "다시 전화 주세요"),
    ConvExpr("I got your message.", "메시지 받았어요"),
    ConvExpr("The call dropped.", "전화가 끊겼어요"),
    ConvExpr("I'm putting you on speaker.", "스피커폰으로 바꿀게요"),
    ConvExpr("Sorry, I couldn't pick up.", "죄송해요 전화 못 받았어요"),
    ConvExpr("Send me the file.", "파일 보내주세요"),
    ConvExpr("I'll reply to your email.", "이메일 답장할게요"),
    ConvExpr("Can you send that in writing?", "그거 문자로 보내줄래요"),
    ConvExpr("I attached the document.", "문서 첨부했어요"),
    ConvExpr("Let's set up a call.", "통화 잡을까요"),
    ConvExpr("I'll forward you the email.", "이메일 전달할게요"),
    ConvExpr("Leave a message after the beep.", "삐 소리 후 메시지 남겨주세요"),
    ConvExpr("I'm on the other line.", "다른 전화 받고 있어요"),
    ConvExpr("Can you cc my manager?", "제 매니저 참조 넣어줄래요"),
    ConvExpr("I'll shoot you a quick email.", "이메일 짧게 보낼게요"),
    ConvExpr("My phone died earlier.", "아까 폰이 꺼졌어요"),
    ConvExpr("Let me put you through.", "연결해드릴게요"),
    ConvExpr("I'll ping you tomorrow.", "내일 연락할게요"),
    ConvExpr("Sorry for the late reply.", "답장이 늦어서 죄송해요"),
    ConvExpr("Can you send that as PDF?", "PDF로 보내줄래요"),
    ConvExpr("I didn't get your text.", "문자를 못 받았어요"),
    ConvExpr("Let's hop on a quick call.", "짧게 통화할까요"),
    ConvExpr("I'll cc you on that email.", "그 메일에 참조 넣을게요"),
    ConvExpr("Please double-check your spam folder.", "스팸함도 확인해보세요"),
    ConvExpr("I texted the wrong number.", "잘못된 번호로 문자했어요"),
    ConvExpr("Can you resend that attachment?", "첨부파일 다시 보내줄래요"),
    ConvExpr("I'll bcc the whole team.", "팀 전체 숨은 참조 넣을게요"),
    ConvExpr("Let's take this offline and call.", "이건 통화로 얘기해요"),
    ConvExpr("I'm sending a follow-up email now.", "지금 후속 메일 보낼게요"),
    ConvExpr("Your voicemail box is full.", "음성 메시지함이 가득 찼어요"),
    ConvExpr("I'll shoot you a quick text.", "문자 짧게 보낼게요"),
    ConvExpr("Let's do a video call instead.", "대신 영상 통화할까요"),
    ConvExpr("I keep getting your voicemail.", "계속 음성 메시지로 넘어가요"),
    ConvExpr("Let me forward you that thread.", "그 메일 스레드 전달할게요"),
    ConvExpr("I'll flag this email as urgent.", "이 메일 긴급으로 표시할게요"),
    ConvExpr("Can you read that text aloud?", "그 문자 소리 내서 읽어줄래요"),
    ConvExpr("I'm cc'd on that email chain.", "저도 그 메일에 참조돼 있어요"),
    ConvExpr("Sorry, my phone was on silent.", "죄송해요 폰이 무음이었어요"),
    ConvExpr("I'll cc the client by email.", "이메일로 고객 참조 넣을게요"),
    ConvExpr("Let's confirm this over text.", "문자로 확인할까요"),
    ConvExpr("I'll send a calendar invite too.", "캘린더 초대도 보낼게요"),
    ConvExpr("My number changed recently.", "최근에 번호가 바뀌었어요"),
    ConvExpr("Can you save my new number?", "새 번호 저장해줄래요"),
    ConvExpr("I replied all by mistake.", "실수로 전체 답장했어요"),
    ConvExpr("Let's start a group chat.", "단체 채팅방 만들까요"),
    ConvExpr("I'll draft a reply now.", "지금 답장 초안 쓸게요"),
    ConvExpr("Your message went to my spam.", "그 메시지가 스팸함으로 갔어요"),
    ConvExpr("I'll send a text to confirm.", "확인 문자 보낼게요"),
    ConvExpr("Can you unmute your phone?", "음소거 풀어줄래요"),
    ConvExpr("I'm changing my ringtone tonight.", "오늘 밤 벨소리 바꿀 거예요"),
    ConvExpr("Let's schedule a callback for noon.", "정오에 콜백 잡을까요"),
    ConvExpr("I never got a reply back.", "답장을 전혀 못 받았어요"),
    ConvExpr("Can you block that number?", "그 번호 차단해줄래요"),
    ConvExpr("I'll add my signature here.", "여기에 서명 넣을게요"),
    ConvExpr("Let's not leave this on read.", "이거 읽씹하지 말아요"),
    ConvExpr("I think I butt-dialed you earlier.", "아까 실수로 전화 눌렀나 봐요"),
    ConvExpr("Can you mute yourself a sec?", "잠깐 음소거해줄래요"),
    ConvExpr("I'll email the invoice tonight.", "오늘 밤 청구서 이메일 보낼게요"),
    ConvExpr("Let's move this conversation to email.", "이건 이메일로 옮겨서 얘기해요"),
    ConvExpr("I'm still waiting on your reply.", "아직 답장 기다리고 있어요"),
    ConvExpr("Can you screenshot that for me?", "그거 캡처해서 보내줄래요"),
    ConvExpr("I'll bcc myself for the record.", "기록용으로 저도 숨은 참조할게요"),
    ConvExpr("Let's keep this thread short.", "이 메일 스레드 짧게 유지해요"),
    ConvExpr("I accidentally hung up on you.", "실수로 전화를 끊었어요"),
    ConvExpr("Text me once you land.", "도착하면 문자해요"),
    ConvExpr("I'll cc legal on this one.", "이건 법무팀 참조 넣을게요"),
  ],
  // 15번 주제
  [
    ConvExpr("symptom", "증상"),
    ConvExpr("fever", "열"),
    ConvExpr("headache", "두통"),
    ConvExpr("stomachache", "복통"),
    ConvExpr("sore throat", "인후통"),
    ConvExpr("prescription", "처방전"),
    ConvExpr("pharmacy", "약국"),
    ConvExpr("appointment", "예약"),
    ConvExpr("clinic", "병원"),
    ConvExpr("checkup", "검진"),
    ConvExpr("medicine", "약"),
    ConvExpr("dosage", "복용량"),
    ConvExpr("side effect", "부작용"),
    ConvExpr("insurance card", "보험증"),
    ConvExpr("pain reliever", "진통제"),
    ConvExpr("cold medicine", "감기약"),
    ConvExpr("blood pressure", "혈압"),
    ConvExpr("allergy", "알레르기"),
    ConvExpr("injection", "주사"),
    ConvExpr("waiting room", "대기실"),
    ConvExpr("My stomach hurts.", "배가 아파요"),
    ConvExpr("I feel nauseous.", "속이 메스꺼워요"),
    ConvExpr("My throat hurts.", "목이 아파요"),
    ConvExpr("I have a cough.", "기침이 나요"),
    ConvExpr("My nose is running.", "콧물이 나요"),
    ConvExpr("I caught a cold.", "감기에 걸렸어요"),
    ConvExpr("I feel sick.", "몸이 안 좋아요"),
    ConvExpr("I need a doctor.", "병원에 가야 해요"),
    ConvExpr("Can I make an appointment?", "예약할 수 있을까요"),
    ConvExpr("I'd like an appointment.", "예약하고 싶어요"),
    ConvExpr("What time is my appointment?", "예약 시간이 언제예요"),
    ConvExpr("I need to reschedule.", "일정을 바꿔야 해요"),
    ConvExpr("Can I cancel my appointment?", "예약을 취소하고 싶어요"),
    ConvExpr("How long is the wait?", "얼마나 기다려요"),
    ConvExpr("Please fill out this form.", "서류를 작성해 주세요"),
    ConvExpr("Do you have insurance?", "보험 있으세요"),
    ConvExpr("Here's my insurance card.", "여기 보험증이에요"),
    ConvExpr("How much does it cost?", "비용이 얼마예요"),
    ConvExpr("Does insurance cover this?", "보험이 되나요"),
    ConvExpr("I don't have insurance.", "보험이 없어요"),
    ConvExpr("What are your symptoms?", "증상이 어때요"),
    ConvExpr("When did it start?", "언제부터 아팠어요"),
    ConvExpr("Does it hurt here?", "여기가 아파요"),
    ConvExpr("Take a deep breath.", "숨을 깊게 쉬세요"),
    ConvExpr("Let me check your pulse.", "맥박을 재 볼게요"),
    ConvExpr("Your temperature is normal.", "체온이 정상이에요"),
    ConvExpr("You have a mild fever.", "미열이 있어요"),
    ConvExpr("I need an X-ray.", "엑스레이가 필요해요"),
    ConvExpr("We'll run some tests.", "검사를 해볼게요"),
    ConvExpr("It looks like the flu.", "독감 같아요"),
    ConvExpr("It's probably just a cold.", "그냥 감기 같아요"),
    ConvExpr("You need a few stitches.", "몇 바늘 꿰매야 해요"),
    ConvExpr("I'll write a prescription.", "처방전을 써 드릴게요"),
    ConvExpr("Take this twice a day.", "하루 두 번 드세요"),
    ConvExpr("Take one pill after meals.", "식후에 한 알 드세요"),
    ConvExpr("Take it on an empty stomach.", "공복에 드세요"),
    ConvExpr("Don't skip a dose.", "복용을 거르지 마세요"),
    ConvExpr("Are you allergic to anything?", "알레르기 있으세요"),
    ConvExpr("I'm allergic to penicillin.", "페니실린 알레르기 있어요"),
    ConvExpr("This might make you drowsy.", "먹으면 졸릴 수 있어요"),
    ConvExpr("Drink plenty of water.", "물을 많이 드세요"),
    ConvExpr("Get plenty of rest.", "푹 쉬세요"),
    ConvExpr("Stay in bed today.", "오늘은 누워 계세요"),
    ConvExpr("Come back in a week.", "일주일 후에 오세요"),
    ConvExpr("Follow up next week.", "다음 주에 다시 오세요"),
    ConvExpr("I need a refill.", "처방전을 다시 받아야 해요"),
    ConvExpr("Where's the nearest pharmacy?", "가까운 약국이 어디예요"),
    ConvExpr("Is this over the counter?", "처방전 없이 살 수 있어요"),
    ConvExpr("Do you have headache medicine?", "두통약 있으세요"),
    ConvExpr("Do you have cold medicine?", "감기약 있으세요"),
    ConvExpr("Can I get a pain reliever?", "진통제 좀 주세요"),
    ConvExpr("How often do I take this?", "얼마나 자주 먹어요"),
    ConvExpr("What are the side effects?", "부작용이 뭐예요"),
    ConvExpr("Can I take this with food?", "음식이랑 같이 먹어도 돼요"),
    ConvExpr("Is this safe for kids?", "아이가 먹어도 안전해요"),
    ConvExpr("I need to renew this.", "이거 갱신해야 해요"),
    ConvExpr("My insurance won't cover this.", "제 보험은 안 돼요"),
    ConvExpr("Can I use my insurance card?", "보험증으로 결제되나요"),
    ConvExpr("I twisted my ankle.", "발목을 삐었어요"),
    ConvExpr("I sprained my wrist.", "손목을 삐었어요"),
    ConvExpr("I burned my hand.", "손을 데었어요"),
    ConvExpr("I cut my finger.", "손가락을 베었어요"),
    ConvExpr("My back has hurt for days.", "며칠째 허리가 아파요"),
    ConvExpr("I've had this cough all week.", "일주일째 기침해요"),
    ConvExpr("The pain comes and goes.", "통증이 왔다 갔다 해요"),
    ConvExpr("It hurts when I press here.", "여기 누르면 아파요"),
    ConvExpr("I've been tired lately.", "요즘 계속 피곤해요"),
    ConvExpr("I haven't slept well.", "잠을 잘 못 잤어요"),
    ConvExpr("I lost my appetite.", "입맛이 없어요"),
    ConvExpr("I might need a blood test.", "피검사가 필요할 것 같아요"),
    ConvExpr("Can I get a doctor's note?", "진단서 받을 수 있어요"),
    ConvExpr("I need a note for school.", "학교 진단서가 필요해요"),
    ConvExpr("Is this covered by insurance?", "보험으로 처리되나요"),
    ConvExpr("I'd like a second opinion.", "다른 의견도 듣고 싶어요"),
    ConvExpr("Can you recommend a specialist?", "전문의 추천해 주세요"),
    ConvExpr("My doctor referred me here.", "주치의가 소개해 줬어요"),
    ConvExpr("My symptoms got worse.", "증상이 심해졌어요"),
    ConvExpr("The medicine isn't working.", "약이 안 들어요"),
    ConvExpr("I want to switch pharmacies.", "다른 약국으로 바꾸고 싶어요"),
    ConvExpr("Can you deliver my prescription?", "처방약 배달되나요"),
  ],
  // 16번 주제
  [
    ConvExpr("chores", "집안일"),
    ConvExpr("laundry", "빨래"),
    ConvExpr("dishes", "설거지"),
    ConvExpr("vacuum", "청소기"),
    ConvExpr("trash", "쓰레기"),
    ConvExpr("recycling", "재활용"),
    ConvExpr("grocery shopping", "장보기"),
    ConvExpr("errand", "심부름"),
    ConvExpr("repair", "수리"),
    ConvExpr("plumber", "배관공"),
    ConvExpr("leak", "누수"),
    ConvExpr("utility bill", "공과금"),
    ConvExpr("electricity", "전기"),
    ConvExpr("water bill", "수도세"),
    ConvExpr("landlord", "집주인"),
    ConvExpr("tenant", "세입자"),
    ConvExpr("neighbor", "이웃"),
    ConvExpr("moving", "이사"),
    ConvExpr("lease", "임대 계약"),
    ConvExpr("broken", "고장"),
    ConvExpr("I need to do laundry.", "빨래해야 해요"),
    ConvExpr("I have to wash dishes.", "설거지해야 해요"),
    ConvExpr("Can you take out trash?", "쓰레기 좀 버려 줄래요"),
    ConvExpr("I'll vacuum the living room.", "거실 청소기 돌릴게요"),
    ConvExpr("Let's clean the kitchen.", "부엌 청소할까요"),
    ConvExpr("I need to mop the floor.", "바닥을 닦아야 해요"),
    ConvExpr("Can you fold the laundry?", "빨래 좀 개켜 줄래요"),
    ConvExpr("I have errands to run.", "심부름 갈 데가 있어요"),
    ConvExpr("I need to buy groceries.", "장을 봐야 해요"),
    ConvExpr("Can you pick up milk?", "우유 좀 사다 줄래요"),
    ConvExpr("I'm out of dish soap.", "주방세제가 떨어졌어요"),
    ConvExpr("The trash needs to go out.", "쓰레기를 내놔야 해요"),
    ConvExpr("Please separate the recycling.", "재활용 분리해 주세요"),
    ConvExpr("This needs to be dry-cleaned.", "이건 드라이클리닝해야 해요"),
    ConvExpr("The sink is clogged.", "싱크대가 막혔어요"),
    ConvExpr("The faucet is leaking.", "수도꼭지가 새요"),
    ConvExpr("The toilet won't flush.", "변기가 안 내려가요"),
    ConvExpr("We have a water leak.", "물이 새고 있어요"),
    ConvExpr("The AC broke down.", "에어컨이 고장났어요"),
    ConvExpr("Can you fix this?", "이거 고쳐 줄래요"),
    ConvExpr("It needs to be repaired.", "수리가 필요해요"),
    ConvExpr("I called a plumber.", "배관공을 불렀어요"),
    ConvExpr("The plumber is coming today.", "배관공이 오늘 와요"),
    ConvExpr("Can you recommend a repairman?", "수리기사 추천해 줄래요"),
    ConvExpr("How much will repairs cost?", "수리비가 얼마나 나와요"),
    ConvExpr("The light bulb burned out.", "전구가 나갔어요"),
    ConvExpr("Can you change the bulb?", "전구 좀 갈아 줄래요"),
    ConvExpr("The power went out.", "정전됐어요"),
    ConvExpr("We had a blackout last night.", "어젯밤에 정전이 났어요"),
    ConvExpr("I need to pay bills.", "공과금을 내야 해요"),
    ConvExpr("My electricity bill is high.", "전기세가 많이 나왔어요"),
    ConvExpr("When is rent due?", "월세가 언제까지예요"),
    ConvExpr("I need to pay rent.", "월세를 내야 해요"),
    ConvExpr("Can I pay rent online?", "월세를 온라인으로 낼 수 있어요"),
    ConvExpr("The water bill went up.", "수도세가 올랐어요"),
    ConvExpr("I set up autopay.", "자동이체 해놨어요"),
    ConvExpr("I forgot to pay the bill.", "요금 내는 걸 잊었어요"),
    ConvExpr("My internet isn't working.", "인터넷이 안 돼요"),
    ConvExpr("The wifi keeps disconnecting.", "와이파이가 자꾸 끊겨요"),
    ConvExpr("I need to call the landlord.", "집주인한테 전화해야 해요"),
    ConvExpr("My landlord raised the rent.", "집주인이 월세를 올렸어요"),
    ConvExpr("The lease ends next month.", "계약이 다음 달에 끝나요"),
    ConvExpr("I want to renew my lease.", "계약을 갱신하고 싶어요"),
    ConvExpr("I'm moving next week.", "다음 주에 이사해요"),
    ConvExpr("We're moving to a new place.", "새 집으로 이사 가요"),
    ConvExpr("I need moving boxes.", "이삿짐 상자가 필요해요"),
    ConvExpr("Can you help me move?", "이사하는 거 도와줄래요"),
    ConvExpr("The movers arrive tomorrow.", "이삿짐센터가 내일 와요"),
    ConvExpr("I need to change my address.", "주소를 변경해야 해요"),
    ConvExpr("I have to set up utilities.", "공과금을 신청해야 해요"),
    ConvExpr("I need to transfer utilities.", "공과금 명의를 바꿔야 해요"),
    ConvExpr("My neighbor is very noisy.", "이웃이 너무 시끄러워요"),
    ConvExpr("The neighbors had a party.", "이웃이 파티를 했어요"),
    ConvExpr("Can you keep it down?", "조용히 좀 해 줄래요"),
    ConvExpr("I'll talk to the neighbors.", "이웃한테 얘기해 볼게요"),
    ConvExpr("Our neighbor borrowed our ladder.", "이웃이 사다리를 빌려갔어요"),
    ConvExpr("I should meet my neighbors.", "이웃들과 인사해야겠어요"),
    ConvExpr("The elevator is out of order.", "엘리베이터가 고장났어요"),
    ConvExpr("The manager will fix it.", "관리인이 고쳐 줄 거예요"),
    ConvExpr("I need a maintenance request.", "수리 요청을 해야 해요"),
    ConvExpr("Can you submit a work order?", "수리 접수 좀 해 줄래요"),
    ConvExpr("The washer is making noise.", "세탁기에서 소리가 나요"),
    ConvExpr("The dryer isn't drying clothes.", "건조기가 잘 안 말려요"),
    ConvExpr("I need to buy detergent.", "세제를 사야 해요"),
    ConvExpr("We're out of paper towels.", "키친타월이 다 떨어졌어요"),
    ConvExpr("Can you run to the store?", "가게 좀 다녀와 줄래요"),
    ConvExpr("I need to return this package.", "이 택배 반품해야 해요"),
    ConvExpr("I need to get dry cleaning.", "드라이클리닝 맡긴 거 찾아야 해요"),
    ConvExpr("Can you water the plants?", "화분에 물 좀 줄래요"),
    ConvExpr("I need to feed the cat.", "고양이 밥을 줘야 해요"),
    ConvExpr("Can you walk the dog?", "강아지 산책 좀 시켜 줄래요"),
    ConvExpr("The garbage disposal is broken.", "음식물처리기가 고장났어요"),
    ConvExpr("I need to unclog the drain.", "배수구를 뚫어야 해요"),
    ConvExpr("Can you take out recycling?", "재활용 좀 버려 줄래요"),
    ConvExpr("I'm changing the air filter.", "에어필터를 갈고 있어요"),
    ConvExpr("The smoke detector is beeping.", "화재경보기가 울려요"),
    ConvExpr("I need new batteries for it.", "새 건전지가 필요해요"),
    ConvExpr("The doorbell isn't working.", "초인종이 안 울려요"),
    ConvExpr("Someone's at the door.", "누가 문 앞에 왔어요"),
    ConvExpr("I need to fix the fence.", "울타리를 고쳐야 해요"),
  ],
  // 17번 주제
  [
    ConvExpr("free time", "여가 시간"),
    ConvExpr("hobby", "취미"),
    ConvExpr("workout", "운동"),
    ConvExpr("gym", "헬스장"),
    ConvExpr("jogging", "조깅"),
    ConvExpr("hiking", "등산"),
    ConvExpr("swimming", "수영"),
    ConvExpr("yoga", "요가"),
    ConvExpr("painting", "그림 그리기"),
    ConvExpr("drawing", "스케치"),
    ConvExpr("reading", "독서"),
    ConvExpr("novel", "소설"),
    ConvExpr("playlist", "재생목록"),
    ConvExpr("concert", "콘서트"),
    ConvExpr("movie theater", "영화관"),
    ConvExpr("board game", "보드게임"),
    ConvExpr("team sport", "단체 운동"),
    ConvExpr("weekend trip", "주말 여행"),
    ConvExpr("exercise routine", "운동 루틴"),
    ConvExpr("What's your hobby?", "취미가 뭐예요"),
    ConvExpr("I like sports.", "운동 좋아해요"),
    ConvExpr("I love movies.", "영화 좋아해요"),
    ConvExpr("Do you like music?", "음악 좋아해요"),
    ConvExpr("I enjoy reading.", "독서를 즐겨요"),
    ConvExpr("Let's watch a movie.", "영화 보러 가요"),
    ConvExpr("I play soccer.", "축구를 해요"),
    ConvExpr("She likes to swim.", "그녀는 수영을 좋아해요"),
    ConvExpr("He plays basketball.", "그는 농구를 해요"),
    ConvExpr("I go jogging daily.", "매일 조깅해요"),
    ConvExpr("We play tennis together.", "같이 테니스를 쳐요"),
    ConvExpr("I read every night.", "매일 밤 책을 읽어요"),
    ConvExpr("She paints on weekends.", "주말에 그림을 그려요"),
    ConvExpr("Do you play sports?", "운동 하세요"),
    ConvExpr("I love listening to music.", "음악 듣는 걸 좋아해요"),
    ConvExpr("He's into photography.", "사진에 빠져 있어요"),
    ConvExpr("I need a new hobby.", "새 취미가 필요해요"),
    ConvExpr("Let's go for a hike.", "등산하러 가요"),
    ConvExpr("I try to exercise daily.", "매일 운동하려고 해요"),
    ConvExpr("What do you do for fun?", "뭐 하며 놀아요"),
    ConvExpr("I go to the gym.", "헬스장에 다녀요"),
    ConvExpr("We watch movies together.", "같이 영화를 봐요"),
    ConvExpr("I'm learning to play piano.", "피아노를 배우고 있어요"),
    ConvExpr("She's a huge sports fan.", "스포츠광이에요"),
    ConvExpr("I picked up yoga recently.", "요가를 시작했어요"),
    ConvExpr("He's training for a marathon.", "마라톤을 준비해요"),
    ConvExpr("I enjoy cooking on weekends.", "주말엔 요리를 즐겨요"),
    ConvExpr("She collects vintage records.", "옛날 음반을 모아요"),
    ConvExpr("I binge watch shows sometimes.", "가끔 몰아보기해요"),
    ConvExpr("We go camping every summer.", "매년 여름 캠핑 가요"),
    ConvExpr("I like to unwind with music.", "음악으로 스트레스 풀어요"),
    ConvExpr("He's obsessed with video games.", "게임에 푹 빠졌어요"),
    ConvExpr("I want to try surfing.", "서핑을 해보고 싶어요"),
    ConvExpr("She's a huge basketball fan.", "농구 열혈팬이에요"),
    ConvExpr("I go to the gym daily.", "매일 헬스장 가요"),
    ConvExpr("We play cards on weekends.", "주말에 카드놀이해요"),
    ConvExpr("I love a good book.", "좋은 책이 좋아요"),
    ConvExpr("He never misses game night.", "게임하는 날은 꼭 챙겨요"),
    ConvExpr("She runs five miles a day.", "매일 5마일 뛰어요"),
    ConvExpr("I like watching old movies.", "옛날 영화 보는 걸 좋아해요"),
    ConvExpr("We hit the trails often.", "자주 등산로에 가요"),
    ConvExpr("I take dance classes weekly.", "매주 댄스 수업 들어요"),
    ConvExpr("He's into rock climbing now.", "요즘 암벽등반에 빠졌어요"),
    ConvExpr("I like doing puzzles at night.", "밤에 퍼즐 맞추는 걸 좋아해요"),
    ConvExpr("She sings in a choir.", "합창단에서 노래해요"),
    ConvExpr("I follow a few podcasts.", "팟캐스트 몇 개 들어요"),
    ConvExpr("We bike around the park.", "공원에서 자전거 타요"),
    ConvExpr("I love outdoor activities.", "야외 활동을 좋아해요"),
    ConvExpr("He plays chess online daily.", "매일 온라인 체스 둬요"),
    ConvExpr("I'm not much of an athlete.", "운동은 잘 못해요"),
    ConvExpr("She's artsy in her free time.", "여가에 예술 활동해요"),
    ConvExpr("Do you have any hobbies?", "취미 있으세요"),
    ConvExpr("I'm really into hiking lately.", "요즘 등산에 빠졌어요"),
    ConvExpr("Let's join a gym together.", "같이 헬스장 등록해요"),
    ConvExpr("He's a die hard fan.", "열성 팬이에요"),
    ConvExpr("I never miss a game.", "경기는 절대 안 놓쳐요"),
    ConvExpr("She's training for a triathlon.", "철인 3종 준비해요"),
    ConvExpr("I love a good workout.", "운동하고 나면 개운해요"),
    ConvExpr("We're big movie buffs.", "영화광이에요"),
    ConvExpr("I read two books a month.", "한 달에 책 두 권 읽어요"),
    ConvExpr("He's practicing for a recital.", "발표회 연습 중이에요"),
    ConvExpr("I'm trying to get fit.", "몸 만들려고 노력해요"),
    ConvExpr("She loves outdoor adventures.", "야외 모험을 좋아해요"),
    ConvExpr("I want to join a team.", "팀에 들어가고 싶어요"),
    ConvExpr("Let's start a book club.", "독서 모임 만들어요"),
    ConvExpr("I love a good playlist.", "좋은 플레이리스트가 최고예요"),
    ConvExpr("He's really competitive at games.", "게임할 때 승부욕 강해요"),
    ConvExpr("I want to run a marathon.", "마라톤 뛰어보고 싶어요"),
    ConvExpr("We should hit the gym.", "헬스장 가야 해요"),
    ConvExpr("I love catching a good movie.", "좋은 영화 보는 게 좋아요"),
    ConvExpr("She's into extreme sports.", "익스트림 스포츠 좋아해요"),
    ConvExpr("I need time to relax.", "쉴 시간이 필요해요"),
    ConvExpr("He spends weekends fishing.", "주말마다 낚시해요"),
    ConvExpr("I like to stay active.", "활동적으로 지내는 게 좋아요"),
    ConvExpr("We go hiking most weekends.", "거의 매주 등산 가요"),
    ConvExpr("I love a lazy Sunday.", "느긋한 일요일이 좋아요"),
    ConvExpr("She's glued to her novel.", "소설에 푹 빠져 있어요"),
    ConvExpr("I want to pick up golf.", "골프 시작하고 싶어요"),
    ConvExpr("He's into fantasy football.", "판타지 풋볼에 빠졌어요"),
    ConvExpr("I love a good concert.", "좋은 콘서트가 최고예요"),
    ConvExpr("We caught a late show.", "심야 영화 봤어요"),
  ],
  // 18번 주제
  [
    ConvExpr("get together", "모임"),
    ConvExpr("hang out", "놀기"),
    ConvExpr("rain check", "다음 기회로 미루기"),
    ConvExpr("RSVP", "참석 여부 회신"),
    ConvExpr("plan ahead", "미리 계획하기"),
    ConvExpr("day trip", "당일치기 여행"),
    ConvExpr("potluck", "음식 나눔 모임"),
    ConvExpr("housewarming", "집들이"),
    ConvExpr("reservation", "예약"),
    ConvExpr("schedule conflict", "일정 겹침"),
    ConvExpr("last minute", "막판"),
    ConvExpr("save the date", "날짜 비워두기"),
    ConvExpr("guest list", "초대 명단"),
    ConvExpr("host", "주최자"),
    ConvExpr("invite", "초대"),
    ConvExpr("reschedule", "일정 변경"),
    ConvExpr("cancel", "취소"),
    ConvExpr("show up", "나타나기"),
    ConvExpr("no show", "안 나타남"),
    ConvExpr("catch up", "밀린 얘기 나누기"),
    ConvExpr("Are you free this weekend?", "이번 주말에 시간 있어요"),
    ConvExpr("Want to hang out?", "같이 놀래요"),
    ConvExpr("Let's get together soon.", "조만간 모여요"),
    ConvExpr("Can you make it?", "올 수 있어요"),
    ConvExpr("What time works for you?", "몇 시가 좋아요"),
    ConvExpr("I'd love to come.", "꼭 갈게요"),
    ConvExpr("Count me in.", "저도 낄게요"),
    ConvExpr("I can't make it.", "저는 못 가요"),
    ConvExpr("Something came up.", "일이 좀 생겼어요"),
    ConvExpr("Let's do it another time.", "다음에 하는 게 어때요"),
    ConvExpr("I have to cancel.", "취소해야 할 것 같아요"),
    ConvExpr("Sorry, I can't come.", "미안한데 못 가요"),
    ConvExpr("Can I bring a friend?", "친구 데려가도 돼요"),
    ConvExpr("What should I bring?", "뭐 가져갈까요"),
    ConvExpr("Let's plan for Saturday.", "토요일로 계획해요"),
    ConvExpr("Are you coming tonight?", "오늘 밤 와요"),
    ConvExpr("I'll be there.", "갈게요"),
    ConvExpr("Let me check my schedule.", "일정 확인해볼게요"),
    ConvExpr("I'm busy that day.", "그날 바빠요"),
    ConvExpr("How about next week instead?", "다음 주는 어때요"),
    ConvExpr("Let's pick another date.", "다른 날짜로 잡아요"),
    ConvExpr("I need a rain check.", "다음 기회에 갈게요"),
    ConvExpr("Can we push it back?", "조금 미룰 수 있어요"),
    ConvExpr("Let's move it to Friday.", "금요일로 옮겨요"),
    ConvExpr("I'll let you know.", "알려줄게요"),
    ConvExpr("Please RSVP by Friday.", "금요일까지 회신해주세요"),
    ConvExpr("Who else is coming?", "또 누가 와요"),
    ConvExpr("I'll bring some snacks.", "간식 좀 가져갈게요"),
    ConvExpr("Let's meet at seven.", "일곱 시에 만나요"),
    ConvExpr("Where should we meet?", "어디서 만날까요"),
    ConvExpr("I'm hosting a party.", "파티 열 거예요"),
    ConvExpr("You're invited to my party.", "파티에 초대할게요"),
    ConvExpr("Save the date for June.", "6월로 날짜 잡아요"),
    ConvExpr("I sent out the invites.", "초대장 보냈어요"),
    ConvExpr("We're throwing a housewarming party.", "집들이할 거예요"),
    ConvExpr("Let's have a potluck dinner.", "다 같이 음식 나눠요"),
    ConvExpr("I made a reservation for six.", "여섯 명으로 예약했어요"),
    ConvExpr("Can you make it work?", "시간 맞출 수 있어요"),
    ConvExpr("Let's confirm the plan.", "계획을 확정해요"),
    ConvExpr("I'll text you the details.", "문자로 알려줄게요"),
    ConvExpr("Don't forget to RSVP.", "참석 여부 꼭 알려주세요"),
    ConvExpr("I might be running late.", "좀 늦을 수도 있어요"),
    ConvExpr("Something popped up at work.", "회사에 일이 생겼어요"),
    ConvExpr("Can we do it another day?", "다른 날 할까요"),
    ConvExpr("Let's keep in touch.", "계속 연락해요"),
    ConvExpr("I'll catch up with you later.", "나중에 밀린 얘기해요"),
    ConvExpr("Sorry for the short notice.", "갑자기 알려서 미안해요"),
    ConvExpr("Let's plan ahead this time.", "이번엔 미리 계획해요"),
    ConvExpr("I double booked myself.", "일정이 겹쳤어요"),
    ConvExpr("My schedule's a bit tight.", "일정이 좀 빡빡해요"),
    ConvExpr("Let's find a time that works.", "다 되는 시간 찾아봐요"),
    ConvExpr("I have a conflict that day.", "그날 다른 일정 있어요"),
    ConvExpr("Can we squeeze in coffee?", "잠깐 커피 어때요"),
    ConvExpr("Let's set a date soon.", "날짜부터 정해요"),
    ConvExpr("I'll send you an invite.", "초대장 보내줄게요"),
    ConvExpr("Feel free to bring someone.", "아무나 데려와도 돼요"),
    ConvExpr("We need a headcount by Monday.", "월요일까지 인원 알려줘요"),
    ConvExpr("Let's finalize the guest list.", "초대 명단 정해요"),
    ConvExpr("I might have to bail.", "못 갈 수도 있어요"),
    ConvExpr("Can we do a rain check?", "다음으로 미뤄도 돼요"),
    ConvExpr("I'm afraid I have to cancel.", "취소해서 미안해요"),
    ConvExpr("Let's push our plans back.", "계획을 좀 미뤄요"),
    ConvExpr("I totally forgot about it.", "완전히 깜빡했어요"),
    ConvExpr("Can you make it another time?", "다른 때 가능해요"),
    ConvExpr("Let's lock in a date.", "날짜 확정해요"),
    ConvExpr("I'll confirm by tomorrow.", "내일까지 확인해줄게요"),
    ConvExpr("We're still on for Saturday.", "토요일 약속은 그대로예요"),
    ConvExpr("Let's keep the plan as is.", "계획 그대로 가요"),
    ConvExpr("I need to bow out.", "저는 빠질게요"),
    ConvExpr("Can we do it virtually instead?", "화상으로 할까요"),
    ConvExpr("Let's plan something low key.", "가볍게 만나요"),
    ConvExpr("I'm free after five.", "다섯 시 이후 괜찮아요"),
    ConvExpr("Let's grab dinner sometime.", "언제 저녁 같이 먹어요"),
    ConvExpr("I'll swing by around noon.", "정오쯤 들를게요"),
    ConvExpr("Can you pencil me in?", "저 좀 끼워줘요"),
    ConvExpr("Let's keep our options open.", "일단 여지를 남겨둬요"),
    ConvExpr("I hate to cancel last minute.", "막판 취소라 미안해요"),
    ConvExpr("We had a scheduling conflict.", "일정이 겹쳐버렸어요"),
    ConvExpr("Let's touch base next week.", "다음 주에 연락해요"),
    ConvExpr("I'll shoot you a text.", "문자 보낼게요"),
  ],
  // 19번 주제
  [
    ConvExpr("I think", "제 생각엔"),
    ConvExpr("In my opinion", "제 생각으로는"),
    ConvExpr("I guess so", "아마 그럴 거예요"),
    ConvExpr("I agree", "동의해요"),
    ConvExpr("I disagree", "동의 안 해요"),
    ConvExpr("Good point", "좋은 지적이에요"),
    ConvExpr("Fair enough", "그럴 만하네요"),
    ConvExpr("Not really", "딱히 아니에요"),
    ConvExpr("No way", "절대 아니에요"),
    ConvExpr("Kind of", "어느 정도는"),
    ConvExpr("Totally agree", "완전 동의해요"),
    ConvExpr("I doubt it", "글쎄요 아닐 것 같아요"),
    ConvExpr("Makes sense", "말이 되네요"),
    ConvExpr("On the other hand", "반면에요"),
    ConvExpr("To be honest", "솔직히 말하면"),
    ConvExpr("Personally", "개인적으로는"),
    ConvExpr("I'm not sure", "잘 모르겠어요"),
    ConvExpr("Absolutely", "완전 맞아요"),
    ConvExpr("Same here", "저도 그래요"),
    ConvExpr("I think that's fair.", "그게 공정한 것 같아요"),
    ConvExpr("I think you're right.", "네 말이 맞는 것 같아요"),
    ConvExpr("I don't think so.", "저는 그렇게 생각 안 해요"),
    ConvExpr("That's a good point.", "좋은 지적이네요"),
    ConvExpr("I see your point.", "무슨 말인지 알겠어요"),
    ConvExpr("I get what you mean.", "무슨 뜻인지 알겠어요"),
    ConvExpr("I couldn't agree more.", "정말 완전 동의해요"),
    ConvExpr("I feel the same way.", "저도 같은 생각이에요"),
    ConvExpr("Same here, actually.", "사실 저도 그래요"),
    ConvExpr("I'm with you on this.", "이건 저도 같은 편이에요"),
    ConvExpr("That makes sense to me.", "저한테는 말이 되네요"),
    ConvExpr("I see it differently.", "저는 다르게 봐요"),
    ConvExpr("I'm on the fence.", "아직 고민 중이에요"),
    ConvExpr("Let's agree to disagree.", "서로 다르다고 인정해요"),
    ConvExpr("I'm not so sure.", "그건 잘 모르겠어요"),
    ConvExpr("That's true, but still.", "맞긴 한데 그래도요"),
    ConvExpr("I hear you, though.", "무슨 말인지 알겠지만요"),
    ConvExpr("Maybe, but I'm not sure.", "그럴 수도 있지만 글쎄요"),
    ConvExpr("I get that, but no.", "알겠는데 그래도 아니에요"),
    ConvExpr("That's a fair point.", "일리 있는 말이에요"),
    ConvExpr("Let's try it your way.", "네 방식대로 해봐요"),
    ConvExpr("Why don't we vote?", "투표하는 게 어때요"),
    ConvExpr("What if we split it?", "나눠보는 건 어때요"),
    ConvExpr("Let's just flip a coin.", "그냥 동전으로 정해요"),
    ConvExpr("How about a different plan?", "다른 계획은 어때요"),
    ConvExpr("Let's think about it more.", "좀 더 생각해봐요"),
    ConvExpr("Can we talk it over?", "같이 얘기해볼까요"),
    ConvExpr("Let's hear both sides.", "양쪽 얘기 다 들어봐요"),
    ConvExpr("I'll go with your call.", "네 결정 따를게요"),
    ConvExpr("Your idea sounds better.", "네 생각이 더 나아요"),
    ConvExpr("I'm leaning toward yours.", "네 쪽으로 마음이 기울어요"),
    ConvExpr("Let's just go with mine.", "그냥 내 방식대로 해요"),
    ConvExpr("That won't work, I think.", "그건 안 될 것 같아요"),
    ConvExpr("I'm not convinced yet.", "아직 설득이 안 됐어요"),
    ConvExpr("Let's weigh the options.", "선택지들을 따져봐요"),
    ConvExpr("I lean the other way.", "저는 반대쪽이에요"),
    ConvExpr("Let's just split the difference.", "서로 반씩 양보해요"),
    ConvExpr("That's not quite right.", "그건 좀 아닌 것 같아요"),
    ConvExpr("I respectfully disagree.", "죄송하지만 동의 안 해요"),
    ConvExpr("With all due respect, no.", "죄송하지만 아니에요"),
    ConvExpr("I'm afraid I disagree.", "아쉽지만 동의 안 해요"),
    ConvExpr("Let's not go there.", "그 얘긴 하지 말죠"),
    ConvExpr("Let's just move on.", "그냥 넘어가요"),
    ConvExpr("I'd rather not say.", "말 안 하는 게 낫겠어요"),
    ConvExpr("Can we agree on this?", "이 부분은 동의할까요"),
    ConvExpr("I'm fine either way.", "저는 둘 다 괜찮아요"),
    ConvExpr("Whatever works for you.", "편한 대로 하세요"),
    ConvExpr("I'll leave it to you.", "당신한테 맡길게요"),
    ConvExpr("It's your call, really.", "정말 당신 결정이에요"),
    ConvExpr("Let's just try both.", "그냥 둘 다 해봐요"),
    ConvExpr("That's a valid concern.", "타당한 걱정이에요"),
    ConvExpr("You have a point there.", "그 말도 맞아요"),
    ConvExpr("I see where you're coming from.", "네 입장 이해돼요"),
    ConvExpr("Still, I feel differently.", "그래도 저는 다르게 느껴요"),
    ConvExpr("Let's agree on the basics.", "기본적인 건 합의해요"),
    ConvExpr("I'm open to other ideas.", "다른 의견도 열려 있어요"),
    ConvExpr("Let's hear what she thinks.", "그녀 생각도 들어봐요"),
    ConvExpr("Maybe you're right about that.", "그 부분은 네가 맞을 수도 있어요"),
    ConvExpr("I could be wrong, though.", "제가 틀릴 수도 있어요"),
    ConvExpr("Let's just keep an open mind.", "열린 마음으로 생각해요"),
    ConvExpr("Let's not jump to conclusions.", "성급하게 결론내지 말아요"),
    ConvExpr("I want to hear more first.", "먼저 더 들어보고 싶어요"),
    ConvExpr("Let's look at both sides.", "양쪽 다 살펴봐요"),
    ConvExpr("I think we're overthinking this.", "우리가 너무 깊게 생각하나봐요"),
    ConvExpr("Honestly, I don't buy it.", "솔직히 안 믿겨요"),
    ConvExpr("That argument doesn't hold up.", "그 주장은 설득력이 없어요"),
    ConvExpr("I'm totally on board.", "완전 찬성이에요"),
    ConvExpr("Count me in on that.", "저도 낄게요"),
    ConvExpr("I'll pass on that idea.", "그 생각은 사양할게요"),
    ConvExpr("Let's put it to a vote.", "그건 투표에 부쳐요"),
    ConvExpr("I don't buy that excuse.", "그 핑계는 안 믿겨요"),
    ConvExpr("That's debatable, in my view.", "제 생각엔 논란의 여지가 있어요"),
    ConvExpr("Let's not argue about this.", "이걸로 다투지 말아요"),
    ConvExpr("We'll have to agree to disagree.", "그냥 각자 생각대로 해요"),
    ConvExpr("I stand by what I said.", "제가 한 말은 그대로예요"),
    ConvExpr("Let's not sweat the details.", "자잘한 건 신경 쓰지 말아요"),
    ConvExpr("I hadn't thought of that.", "그건 생각 못 했어요"),
    ConvExpr("That changes my mind a bit.", "그 말에 마음이 좀 바뀌네요"),
    ConvExpr("I'm starting to see your point.", "네 말이 좀 이해되기 시작해요"),
    ConvExpr("Let's just go with the flow.", "그냥 흘러가는 대로 해요"),
    ConvExpr("I still think I'm right.", "그래도 제가 맞다고 봐요"),
  ],
  // 20번 주제
  [
    ConvExpr("sit down", "앉다"),
    ConvExpr("stand up", "일어서다"),
    ConvExpr("turn on", "켜다"),
    ConvExpr("turn off", "끄다"),
    ConvExpr("put on", "입다"),
    ConvExpr("take off", "벗다"),
    ConvExpr("come in", "들어오다"),
    ConvExpr("go out", "나가다"),
    ConvExpr("come back", "돌아오다"),
    ConvExpr("pick up", "집다"),
    ConvExpr("put down", "내려놓다"),
    ConvExpr("look up", "찾아보다"),
    ConvExpr("look for", "찾다"),
    ConvExpr("find out", "알아내다"),
    ConvExpr("give up", "포기하다"),
    ConvExpr("hang up", "전화를 끊다"),
    ConvExpr("hang on", "잠깐 기다리다"),
    ConvExpr("Pick me up at seven.", "일곱시에 데리러 와줘요"),
    ConvExpr("Turn off the lights.", "불 좀 꺼줘요"),
    ConvExpr("Turn on the TV.", "티비 좀 켜줘요"),
    ConvExpr("Put on your coat.", "코트 입어요"),
    ConvExpr("Take off your shoes.", "신발 벗어요"),
    ConvExpr("Wake me up early.", "일찍 깨워줘요"),
    ConvExpr("Sit down, please.", "앉으세요"),
    ConvExpr("Hang up the phone.", "전화 끊어요"),
    ConvExpr("Look up the word.", "그 단어 찾아봐요"),
    ConvExpr("Give up already.", "그만 포기해요"),
    ConvExpr("Find out what happened.", "무슨 일인지 알아봐요"),
    ConvExpr("Look for your keys.", "열쇠를 찾아봐요"),
    ConvExpr("Get up now.", "지금 일어나요"),
    ConvExpr("Come in, please.", "들어오세요"),
    ConvExpr("Go out with friends.", "친구들이랑 나가요"),
    ConvExpr("Come back soon.", "곧 돌아와요"),
    ConvExpr("Put away your toys.", "장난감 좀 치워요"),
    ConvExpr("Put down the phone.", "전화기 내려놔요"),
    ConvExpr("Turn up the volume.", "볼륨을 높여요"),
    ConvExpr("turn down", "거절하다"),
    ConvExpr("drop off", "내려주다"),
    ConvExpr("We ran out of milk.", "우유가 다 떨어졌어요"),
    ConvExpr("I can't figure it out.", "도저히 이해가 안 돼요"),
    ConvExpr("Look after your sister.", "동생 좀 돌봐요"),
    ConvExpr("We'll look into it.", "그 문제를 조사해볼게요"),
    ConvExpr("Look out for cars!", "차 조심해요"),
    ConvExpr("We get along well.", "우리는 사이가 좋아요"),
    ConvExpr("Get over it already.", "이제 그만 극복해요"),
    ConvExpr("We'll get through this.", "우리 함께 이겨낼 거예요"),
    ConvExpr("Let's get away this weekend.", "이번 주말에 떠나요"),
    ConvExpr("I came across your bag.", "네 가방을 우연히 봤어요"),
    ConvExpr("Come up with a plan.", "계획을 생각해내요"),
    ConvExpr("We went through a lot.", "우리 많이 겪었어요"),
    ConvExpr("My alarm went off.", "알람이 울렸어요"),
    ConvExpr("Let's hang out tonight.", "오늘 밤 같이 놀아요"),
    ConvExpr("I ran into her today.", "오늘 그녀를 우연히 만났어요"),
    ConvExpr("Don't run away from this.", "이거 피하지 말아요"),
    ConvExpr("My car broke down.", "차가 고장 났어요"),
    ConvExpr("They broke up last week.", "걔네 지난주에 헤어졌어요"),
    ConvExpr("They called off the trip.", "여행을 취소했어요"),
    ConvExpr("Let's check in at noon.", "정오에 체크인해요"),
    ConvExpr("check out", "체크아웃하다"),
    ConvExpr("Clean up your room.", "방 좀 치워요"),
    ConvExpr("Cheer up, it's okay.", "힘내요 괜찮아요"),
    ConvExpr("Calm down, take a breath.", "진정하고 숨 좀 쉬어요"),
    ConvExpr("I'll deal with it.", "제가 처리할게요"),
    ConvExpr("Everything fell apart fast.", "모든 게 빨리 무너졌어요"),
    ConvExpr("Fill out this form.", "이 양식을 작성해요"),
    ConvExpr("Get rid of that junk.", "그 잡동사니 없애요"),
    ConvExpr("I can't keep up with you.", "도저히 못 따라가겠어요"),
    ConvExpr("Don't let me down.", "저 실망시키지 말아요"),
    ConvExpr("I look forward to it.", "그거 정말 기대돼요"),
    ConvExpr("Let's just make up.", "그냥 화해해요"),
    ConvExpr("pass out", "기절하다"),
    ConvExpr("I can't put up with this.", "이건 도저히 못 참겠어요"),
    ConvExpr("Throw that away, please.", "그거 좀 버려줘요"),
    ConvExpr("Point out the mistake.", "실수를 지적해요"),
    ConvExpr("Let's sort out this mess.", "이 문제를 정리해요"),
    ConvExpr("Guess who showed up.", "누가 나타났는지 맞혀봐요"),
    ConvExpr("Sign up for the class.", "그 수업에 등록해요"),
    ConvExpr("She really stands out.", "그녀는 정말 눈에 띄어요"),
    ConvExpr("He takes after his dad.", "아빠를 닮았어요"),
    ConvExpr("I take back what I said.", "제가 한 말 취소할게요"),
    ConvExpr("Let me think it over.", "그거 곰곰이 생각해볼게요"),
    ConvExpr("Try on this jacket.", "이 재킷 입어봐요"),
    ConvExpr("It turned into a mess.", "완전 엉망이 됐어요"),
    ConvExpr("Let's warm up first.", "먼저 몸 좀 풀어요"),
    ConvExpr("Watch out for that step.", "그 계단 조심해요"),
    ConvExpr("It'll all work out.", "다 잘 될 거예요"),
    ConvExpr("Write down the address.", "주소를 적어놔요"),
    ConvExpr("We used up all the paper.", "종이를 다 써버렸어요"),
    ConvExpr("Back up your files.", "파일을 백업해요"),
    ConvExpr("I came down with a cold.", "감기에 걸렸어요"),
    ConvExpr("Try to cut down on sugar.", "설탕을 좀 줄여봐요"),
    ConvExpr("It ended up okay.", "결국 잘 됐어요"),
    ConvExpr("I really messed up.", "제가 완전 망쳤어요"),
    ConvExpr("It's time to move on.", "이제 넘어갈 때예요"),
    ConvExpr("Her grandpa passed away.", "할아버지가 돌아가셨어요"),
    ConvExpr("I'll pay you back.", "돈 갚을게요"),
    ConvExpr("Pick out a color.", "색깔 하나 골라봐요"),
    ConvExpr("Let's stick with the plan.", "이 계획대로 밀고 가요"),
    ConvExpr("Get in the car.", "차에 타요"),
    ConvExpr("Get out of the car.", "차에서 내려요"),
  ],
];
