// 자동 생성 데이터 — 성인 영어회화 표현 묶음.
// 유창한 회화 3000 — 주제 21~30 (주제당 100개)

import 'conversation_data.dart';

/// 유창한 회화 3000 — 주제 21~30
const List<List<ConvExpr>> convTier3 = [
  // 21번 주제
  [
    ConvExpr("Really?", "정말요?"),
    ConvExpr("No way!", "말도 안 돼요!"),
    ConvExpr("Wow.", "우와"),
    ConvExpr("Really.", "그렇군요"),
    ConvExpr("I see.", "알겠어요"),
    ConvExpr("Right.", "맞아요"),
    ConvExpr("Exactly.", "바로 그거예요"),
    ConvExpr("Good for you.", "잘됐네요"),
    ConvExpr("That's too bad.", "안타깝네요"),
    ConvExpr("Sounds good.", "좋아요"),
    ConvExpr("Sounds great.", "좋네요"),
    ConvExpr("No kidding.", "진짜예요?"),
    ConvExpr("You're kidding!", "설마요!"),
    ConvExpr("Are you serious?", "진심이에요?"),
    ConvExpr("I bet.", "그럴 줄 알았어요"),
    ConvExpr("I doubt it.", "글쎄요"),
    ConvExpr("Tell me about it.", "내 말이 그 말이에요"),
    ConvExpr("That makes sense.", "그럴 만하네요"),
    ConvExpr("Me too.", "저도요"),
    ConvExpr("Me neither.", "저도 아니에요"),
    ConvExpr("Not really.", "딱히 아니에요"),
    ConvExpr("I guess so.", "그런 것 같아요"),
    ConvExpr("I hope so.", "그랬으면 좋겠어요"),
    ConvExpr("I hope not.", "안 그랬으면 좋겠어요"),
    ConvExpr("Absolutely.", "당연하죠"),
    ConvExpr("Definitely.", "물론이죠"),
    ConvExpr("For sure.", "확실해요"),
    ConvExpr("No doubt.", "의심할 여지 없어요"),
    ConvExpr("That's a relief.", "다행이네요"),
    ConvExpr("Thank goodness.", "다행이에요"),
    ConvExpr("Oh no.", "이런"),
    ConvExpr("Oh dear.", "어머나"),
    ConvExpr("What a shame.", "아쉽네요"),
    ConvExpr("How awful.", "끔찍하네요"),
    ConvExpr("How sweet.", "다정하네요"),
    ConvExpr("That's rough.", "힘들었겠네요"),
    ConvExpr("That's harsh.", "너무하네요"),
    ConvExpr("That's wild.", "대박이네요"),
    ConvExpr("That's crazy.", "말도 안 돼요"),
    ConvExpr("That's insane.", "미쳤네요"),
    ConvExpr("Get out of here!", "설마 그럴 리가요!"),
    ConvExpr("You've got to be kidding.", "농담이죠?"),
    ConvExpr("I can't believe it.", "믿을 수가 없어요"),
    ConvExpr("I can't believe that.", "그게 믿기지 않아요"),
    ConvExpr("Unbelievable.", "믿기지 않아요"),
    ConvExpr("Seriously?", "진심으로요?"),
    ConvExpr("Is that right?", "그게 맞아요?"),
    ConvExpr("Is that so?", "그런가요?"),
    ConvExpr("If you say so.", "그렇다면야"),
    ConvExpr("Whatever you think.", "네 생각이 그렇다면요"),
    ConvExpr("I hear you.", "무슨 말인지 알아요"),
    ConvExpr("I feel you.", "공감해요"),
    ConvExpr("I know the feeling.", "그 기분 알아요"),
    ConvExpr("I can relate.", "공감돼요"),
    ConvExpr("That rings a bell.", "어디서 들어본 것 같아요"),
    ConvExpr("It rings true.", "맞는 말 같아요"),
    ConvExpr("Good to know.", "알아두면 좋겠네요"),
    ConvExpr("Duly noted.", "명심할게요"),
    ConvExpr("Point taken.", "무슨 말인지 알겠어요"),
    ConvExpr("Touche.", "인정할게요"),
    ConvExpr("Well said.", "말 잘했어요"),
    ConvExpr("Couldn't agree more.", "완전 동감이에요"),
    ConvExpr("You can say that again.", "정말 맞는 말이에요"),
    ConvExpr("You said it.", "맞는 말이에요"),
    ConvExpr("Now you're talking.", "이제야 말이 통하네요"),
    ConvExpr("That's more like it.", "그게 낫네요"),
    ConvExpr("There you go.", "그거예요"),
    ConvExpr("That's the spirit.", "바로 그 자세예요"),
    ConvExpr("Way to go!", "잘했어요!"),
    ConvExpr("Good job on that.", "그거 잘했어요"),
    ConvExpr("Nice one.", "잘했어요"),
    ConvExpr("Well done, then.", "그럼 잘했네요"),
    ConvExpr("Big deal.", "별거 아니네요"),
    ConvExpr("So what?", "그래서 뭐요?"),
    ConvExpr("Who cares?", "누가 신경 써요?"),
    ConvExpr("Whatever.", "아무래도 상관없어요"),
    ConvExpr("Small world.", "세상 참 좁네요"),
    ConvExpr("What are the odds?", "이런 우연이 다 있나요?"),
    ConvExpr("Talk about timing.", "타이밍 한번 절묘하네요"),
    ConvExpr("Speak of the devil.", "호랑이도 제 말 하면 오네요"),
    ConvExpr("Easier said than done.", "말이야 쉽죠"),
    ConvExpr("That's one way to put it.", "그렇게 말할 수도 있겠네요"),
    ConvExpr("I'll take your word for it.", "그 말 믿을게요"),
    ConvExpr("I'll say.", "정말 그래요"),
    ConvExpr("If you insist.", "정 그러시다면요"),
    ConvExpr("Suit yourself.", "마음대로 하세요"),
    ConvExpr("Your call.", "당신 선택이에요"),
    ConvExpr("Fine by me.", "저는 괜찮아요"),
    ConvExpr("Can't argue with that.", "반박할 수 없네요"),
    ConvExpr("No arguments here.", "이의 없어요"),
    ConvExpr("That checks out.", "앞뒤가 맞네요"),
    ConvExpr("Makes two of us.", "저도 마찬가지예요"),
    ConvExpr("Preaching to the choir.", "이미 동의하는 사람한테 그러네요"),
    ConvExpr("I'm speechless.", "할 말이 없어요"),
    ConvExpr("Words fail me.", "말이 안 나오네요"),
    ConvExpr("I don't know what to say.", "뭐라 해야 할지 모르겠어요"),
    ConvExpr("That's a first.", "이런 건 처음이에요"),
    ConvExpr("Never would have guessed.", "전혀 몰랐을 거예요"),
    ConvExpr("You don't say.", "설마 그럴까요"),
    ConvExpr("Says who?", "누가 그래요?"),
  ],
  // 22번 주제
  [
    ConvExpr("Frustrated.", "답답해요"),
    ConvExpr("Relieved.", "안심돼요"),
    ConvExpr("I'm so relieved.", "정말 안심돼요"),
    ConvExpr("Overwhelmed.", "벅차요"),
    ConvExpr("I feel overwhelmed.", "벅찬 기분이에요"),
    ConvExpr("Embarrassed.", "창피해요"),
    ConvExpr("Proud.", "뿌듯해요"),
    ConvExpr("I'm so proud of you.", "정말 자랑스러워요"),
    ConvExpr("Nervous.", "긴장돼요"),
    ConvExpr("I'm a bit nervous.", "조금 긴장돼요"),
    ConvExpr("Anxious.", "불안해요"),
    ConvExpr("I feel anxious.", "불안한 기분이에요"),
    ConvExpr("Stressed out.", "스트레스 받아요"),
    ConvExpr("Exhausted.", "지쳤어요"),
    ConvExpr("I'm completely exhausted.", "완전히 지쳤어요"),
    ConvExpr("Drained.", "기운이 없어요"),
    ConvExpr("I feel drained.", "기운이 다 빠졌어요"),
    ConvExpr("Burned out.", "번아웃 왔어요"),
    ConvExpr("I'm burned out.", "번아웃이 왔어요"),
    ConvExpr("Guilty.", "죄책감 들어요"),
    ConvExpr("I feel guilty about it.", "그게 죄책감이 들어요"),
    ConvExpr("Ashamed.", "부끄러워요"),
    ConvExpr("I'm ashamed of myself.", "제 자신이 부끄러워요"),
    ConvExpr("Humiliated.", "굴욕적이에요"),
    ConvExpr("I felt humiliated.", "굴욕감을 느꼈어요"),
    ConvExpr("Jealous.", "질투 나요"),
    ConvExpr("I'm a little jealous.", "조금 질투 나요"),
    ConvExpr("Envious.", "부러워요"),
    ConvExpr("I'm envious of her.", "그녀가 부러워요"),
    ConvExpr("Homesick.", "향수병이 있어요"),
    ConvExpr("I'm feeling homesick.", "향수병이 나요"),
    ConvExpr("Nostalgic.", "향수를 느껴요"),
    ConvExpr("It makes me nostalgic.", "그게 향수를 불러일으켜요"),
    ConvExpr("Restless.", "안절부절못해요"),
    ConvExpr("I feel restless.", "안절부절못하겠어요"),
    ConvExpr("On edge.", "예민해요"),
    ConvExpr("I've been on edge lately.", "요즘 예민해요"),
    ConvExpr("Uneasy.", "불편해요"),
    ConvExpr("Something feels uneasy.", "뭔가 불편한 느낌이에요"),
    ConvExpr("Torn.", "갈등돼요"),
    ConvExpr("I'm torn between them.", "둘 사이에서 갈등돼요"),
    ConvExpr("Conflicted.", "마음이 복잡해요"),
    ConvExpr("I feel conflicted about it.", "그것에 대해 마음이 복잡해요"),
    ConvExpr("Indifferent.", "무덤덤해요"),
    ConvExpr("I feel indifferent about it.", "그것에 대해 무덤덤해요"),
    ConvExpr("Numb.", "멍해요"),
    ConvExpr("I felt numb inside.", "속이 멍했어요"),
    ConvExpr("Heartbroken.", "마음이 찢어져요"),
    ConvExpr("I'm heartbroken over this.", "이 일로 마음이 찢어져요"),
    ConvExpr("Devastated.", "큰 충격을 받았어요"),
    ConvExpr("I was devastated by the news.", "그 소식에 큰 충격을 받았어요"),
    ConvExpr("Disheartened.", "낙담했어요"),
    ConvExpr("I feel disheartened.", "낙담이 돼요"),
    ConvExpr("Discouraged.", "의욕이 꺾여요"),
    ConvExpr("Don't get discouraged.", "의욕 꺾이지 마세요"),
    ConvExpr("Insecure.", "자신이 없어요"),
    ConvExpr("I feel insecure about my looks.", "외모에 자신이 없어요"),
    ConvExpr("Vulnerable.", "마음이 약해져요"),
    ConvExpr("I feel vulnerable right now.", "지금 마음이 약해요"),
    ConvExpr("Overjoyed.", "너무 기뻐요"),
    ConvExpr("I was overjoyed to hear that.", "그 말을 듣고 너무 기뻤어요"),
    ConvExpr("Ecstatic.", "황홀해요"),
    ConvExpr("She was ecstatic about the news.", "그녀는 그 소식에 황홀해했어요"),
    ConvExpr("Content.", "만족스러워요"),
    ConvExpr("I feel content with my life.", "제 삶에 만족해요"),
    ConvExpr("Fulfilled.", "성취감을 느껴요"),
    ConvExpr("I feel fulfilled at work.", "일에서 성취감을 느껴요"),
    ConvExpr("Grateful.", "감사해요"),
    ConvExpr("I'm truly grateful for this.", "이것에 정말 감사해요"),
    ConvExpr("Touched.", "감동받았어요"),
    ConvExpr("I was really touched by that.", "그것에 정말 감동받았어요"),
    ConvExpr("Moved.", "마음이 움직였어요"),
    ConvExpr("That story moved me deeply.", "그 이야기가 깊이 감동시켰어요"),
    ConvExpr("Startled.", "깜짝 놀랐어요"),
    ConvExpr("I was startled by the noise.", "그 소리에 깜짝 놀랐어요"),
    ConvExpr("Shocked.", "충격받았어요"),
    ConvExpr("I'm still shocked about it.", "아직도 그것에 충격받았어요"),
    ConvExpr("Bitter.", "씁쓸해요"),
    ConvExpr("I feel bitter about the outcome.", "결과에 씁쓸함을 느껴요"),
    ConvExpr("Resentful.", "억울해요"),
    ConvExpr("I feel resentful toward him.", "그에게 억울함을 느껴요"),
    ConvExpr("Regretful.", "후회돼요"),
    ConvExpr("I feel regretful about my choice.", "제 선택이 후회돼요"),
    ConvExpr("Remorseful.", "뉘우치고 있어요"),
    ConvExpr("He seemed remorseful afterward.", "그는 나중에 뉘우치는 듯했어요"),
    ConvExpr("Apprehensive.", "걱정스러워요"),
    ConvExpr("I'm apprehensive about the exam.", "시험이 걱정스러워요"),
    ConvExpr("Skeptical.", "회의적이에요"),
    ConvExpr("I'm a bit skeptical about it.", "그것에 조금 회의적이에요"),
    ConvExpr("Suspicious.", "의심스러워요"),
    ConvExpr("Something feels suspicious to me.", "뭔가 의심스러워요"),
    ConvExpr("Paranoid.", "지나치게 불안해요"),
    ConvExpr("I feel paranoid sometimes.", "가끔 지나치게 불안해요"),
    ConvExpr("Melancholy.", "우울한 느낌이에요"),
    ConvExpr("There's a melancholy in her voice.", "그녀 목소리에 우울함이 있어요"),
    ConvExpr("Wistful.", "아쉬운 그리움이에요"),
    ConvExpr("He gave a wistful smile.", "그는 아쉬운 미소를 지었어요"),
    ConvExpr("Underappreciated.", "인정받지 못한 느낌이에요"),
    ConvExpr("I feel underappreciated at work.", "직장에서 인정받지 못한 느낌이에요"),
    ConvExpr("Overlooked.", "소외된 느낌이에요"),
  ],
  // 23번 주제
  [
    ConvExpr("piece of cake", "식은 죽 먹기"),
    ConvExpr("break the ice", "어색함을 깨다"),
    ConvExpr("hit the road", "길을 나서다"),
    ConvExpr("under the weather", "몸이 안 좋다"),
    ConvExpr("hang in there", "힘내, 버텨"),
    ConvExpr("so far so good", "지금까지는 순조롭다"),
    ConvExpr("time flies", "시간 참 빠르다"),
    ConvExpr("no big deal", "별일 아니다"),
    ConvExpr("give it a shot", "한번 해보다"),
    ConvExpr("once in a blue moon", "아주 가끔"),
    ConvExpr("spill the beans", "비밀을 말하다"),
    ConvExpr("hit the sack", "잠자리에 들다"),
    ConvExpr("costs an arm and a leg", "엄청 비싸다"),
    ConvExpr("kill two birds with one stone", "일석이조"),
    ConvExpr("the writing is on the wall", "결과가 뻔히 보이다"),
    ConvExpr("the ball is in your court", "이제 네 차례다"),
    ConvExpr("bite the bullet", "이를 악물고 견디다"),
    ConvExpr("back to square one", "원점으로 돌아가다"),
    ConvExpr("when pigs fly", "절대 일어나지 않을 일"),
    ConvExpr("out of the blue", "갑자기, 느닷없이"),
    ConvExpr("on the ball", "일 처리가 빠르다"),
    ConvExpr("miss the boat", "기회를 놓치다"),
    ConvExpr("call it a day", "오늘은 여기까지 하다"),
    ConvExpr("keep an eye on it", "잘 지켜보다"),
    ConvExpr("keep your fingers crossed", "행운을 빌다"),
    ConvExpr("get your act together", "정신 차리고 제대로 하다"),
    ConvExpr("burn the midnight oil", "밤늦게까지 일하다"),
    ConvExpr("hit the nail on the head", "정곡을 찌르다"),
    ConvExpr("add fuel to the fire", "불난 집에 부채질하다"),
    ConvExpr("beat around the bush", "말을 빙빙 돌리다"),
    ConvExpr("bend over backwards", "최선을 다하다"),
    ConvExpr("break a leg", "행운을 빌어요"),
    ConvExpr("by the skin of your teeth", "아슬아슬하게"),
    ConvExpr("cut to the chase", "본론만 말하다"),
    ConvExpr("drop the ball", "실수로 망치다"),
    ConvExpr("get out of hand", "손쓸 수 없게 되다"),
    ConvExpr("keep your eyes peeled", "눈을 크게 뜨고 살피다"),
    ConvExpr("go the extra mile", "한 발 더 노력하다"),
    ConvExpr("jump on the bandwagon", "유행에 편승하다"),
    ConvExpr("keep it under wraps", "비밀로 하다"),
    ConvExpr("let sleeping dogs lie", "긁어 부스럼 만들지 말다"),
    ConvExpr("make a long story short", "요약하자면"),
    ConvExpr("on cloud nine", "너무 행복하다"),
    ConvExpr("see eye to eye", "의견이 일치하다"),
    ConvExpr("speak of the devil", "호랑이도 제 말 하면 온다"),
    ConvExpr("read the fine print", "세부 사항을 꼼꼼히 보다"),
    ConvExpr("the tip of the iceberg", "빙산의 일각"),
    ConvExpr("throw in the towel", "포기하다"),
    ConvExpr("up in the air", "아직 미정이다"),
    ConvExpr("actions speak louder than words", "말보다 행동"),
    ConvExpr("don't cry over spilled milk", "이미 엎질러진 물이다"),
    ConvExpr("every cloud has a silver lining", "고생 끝에 낙이 온다"),
    ConvExpr("get cold feet", "겁을 먹고 망설이다"),
    ConvExpr("go back to the drawing board", "처음부터 다시 하다"),
    ConvExpr("have a lot on your plate", "할 일이 산더미다"),
    ConvExpr("in the same boat", "같은 처지다"),
    ConvExpr("it's not rocket science", "그렇게 어려운 일이 아니다"),
    ConvExpr("jump the gun", "너무 성급하게 굴다"),
    ConvExpr("keep your chin up", "기죽지 말다"),
    ConvExpr("leave no stone unturned", "백방으로 노력하다"),
    ConvExpr("lose track of time", "시간 가는 줄 모르다"),
    ConvExpr("make ends meet", "겨우 먹고 살다"),
    ConvExpr("off the hook", "곤란에서 벗어나다"),
    ConvExpr("on thin ice", "위태로운 상황이다"),
    ConvExpr("pull yourself together", "정신 차리다"),
    ConvExpr("go out on a limb", "위험을 무릅쓰다"),
    ConvExpr("rain on someone's parade", "흥을 깨다"),
    ConvExpr("read between the lines", "숨은 뜻을 읽다"),
    ConvExpr("save it for a rainy day", "나중을 위해 아껴두다"),
    ConvExpr("a blessing in disguise", "전화위복"),
    ConvExpr("steal someone's thunder", "공을 가로채다"),
    ConvExpr("the best of both worlds", "두 마리 토끼를 다 잡다"),
    ConvExpr("the elephant in the room", "다들 아는 불편한 문제"),
    ConvExpr("through thick and thin", "좋을 때나 나쁠 때나"),
    ConvExpr("turn a blind eye", "못 본 척하다"),
    ConvExpr("under one's belt", "이미 경험한, 이룬"),
    ConvExpr("wrap your head around it", "이해하려 애쓰다"),
    ConvExpr("hold your horses", "성급하게 굴지 마세요"),
    ConvExpr("get the ball rolling", "일을 시작하다"),
    ConvExpr("blow off steam", "스트레스를 풀다"),
    ConvExpr("cut someone some slack", "좀 봐주다"),
    ConvExpr("face the music", "결과를 받아들이다"),
    ConvExpr("a taste of your own medicine", "자업자득을 당하다"),
    ConvExpr("go with the flow", "흐름에 맡기다"),
    ConvExpr("hit the ground running", "시작부터 전력을 다하다"),
    ConvExpr("in the heat of the moment", "순간의 감정에 휩쓸려"),
    ConvExpr("keep your options open", "선택지를 열어두다"),
    ConvExpr("know the ropes", "요령을 알다"),
    ConvExpr("make a scene", "소란을 피우다"),
    ConvExpr("pull strings", "뒤에서 손을 쓰다"),
    ConvExpr("put your foot down", "단호하게 나가다"),
    ConvExpr("read the room", "분위기를 파악하다"),
    ConvExpr("run out of steam", "기운이 다 빠지다"),
    ConvExpr("take the plunge", "과감히 결단하다"),
    ConvExpr("think outside the box", "틀에서 벗어나 생각하다"),
    ConvExpr("turn over a new leaf", "새사람이 되다"),
    ConvExpr("up to speed", "최신 상황을 알다"),
    ConvExpr("weather the storm", "위기를 견뎌내다"),
    ConvExpr("burn bridges", "관계를 완전히 끊다"),
    ConvExpr("clear the air", "오해를 풀다"),
  ],
  // 24번 주제
  [
    ConvExpr("touch base", "잠깐 연락하다"),
    ConvExpr("sit tight", "가만히 기다리다"),
    ConvExpr("long shot", "가능성이 희박한 일"),
    ConvExpr("talk shop", "일 얘기만 하다"),
    ConvExpr("make waves", "파장을 일으키다"),
    ConvExpr("cut corners", "대충 하다"),
    ConvExpr("on the fence", "결정을 못 내리다"),
    ConvExpr("on a roll", "잘 풀리고 있다"),
    ConvExpr("tie the knot", "결혼하다"),
    ConvExpr("get a grip", "정신 차리다"),
    ConvExpr("raise eyebrows", "놀라움을 일으키다"),
    ConvExpr("kick yourself", "자책하다"),
    ConvExpr("knock on wood", "부정 타지 않기를"),
    ConvExpr("sleep on it", "하룻밤 자며 생각하다"),
    ConvExpr("foot the bill", "비용을 대다"),
    ConvExpr("chew the fat", "수다를 떨다"),
    ConvExpr("miss the point", "요점을 놓치다"),
    ConvExpr("go cold turkey", "단번에 끊다"),
    ConvExpr("take the heat", "비난을 감수하다"),
    ConvExpr("no strings attached", "아무 조건 없이"),
    ConvExpr("hit close to home", "남 일 같지 않다"),
    ConvExpr("rock the boat", "평지풍파를 일으키다"),
    ConvExpr("pass the buck", "책임을 떠넘기다"),
    ConvExpr("play it by ear", "상황 봐가며 하다"),
    ConvExpr("pull the plug", "중단시키다"),
    ConvExpr("push the envelope", "한계를 넘어서다"),
    ConvExpr("over the moon", "너무 기쁘다"),
    ConvExpr("up for grabs", "누구나 차지할 수 있다"),
    ConvExpr("under the gun", "압박을 받는 중이다"),
    ConvExpr("new lease on life", "새로운 삶을 얻다"),
    ConvExpr("no pain no gain", "고생 없이 얻는 것 없다"),
    ConvExpr("in a nutshell", "한마디로 말하면"),
    ConvExpr("in the ballpark", "대략 비슷하다"),
    ConvExpr("in the long run", "장기적으로 보면"),
    ConvExpr("drag your feet", "꾸물거리다"),
    ConvExpr("get in the way", "방해가 되다"),
    ConvExpr("get the picture", "상황을 이해하다"),
    ConvExpr("fish out of water", "낯설고 불편한 상황"),
    ConvExpr("dead in the water", "완전히 실패한 상태"),
    ConvExpr("cut and dried", "이미 정해진, 뻔한"),
    ConvExpr("tighten your belt", "허리띠를 졸라매다"),
    ConvExpr("down to the wire", "마지막 순간까지 가다"),
    ConvExpr("par for the course", "흔히 있는 일"),
    ConvExpr("a dime a dozen", "흔해 빠진"),
    ConvExpr("jump through hoops", "온갖 절차를 거치다"),
    ConvExpr("kick the bucket", "죽다"),
    ConvExpr("off the beaten path", "사람들이 잘 안 가는 곳"),
    ConvExpr("once bitten twice shy", "한 번 데면 조심하게 되다"),
    ConvExpr("out of left field", "전혀 예상 밖의"),
    ConvExpr("lay it on thick", "과장해서 말하다"),
    ConvExpr("keep something at bay", "멀리하다, 막아내다"),
    ConvExpr("jump the shark", "매력을 잃기 시작하다"),
    ConvExpr("in the doghouse", "미움을 사다"),
    ConvExpr("miss the mark", "목표를 빗나가다"),
    ConvExpr("water under the bridge", "이미 지나간 일"),
    ConvExpr("walk on eggshells", "조심조심 눈치를 보다"),
    ConvExpr("take a rain check", "다음 기회로 미루다"),
    ConvExpr("cut to the quick", "마음에 깊이 상처 주다"),
    ConvExpr("fit to be tied", "화가 머리끝까지 나다"),
    ConvExpr("go the distance", "끝까지 해내다"),
    ConvExpr("go belly up", "완전히 망하다"),
    ConvExpr("give it your all", "최선을 다하다"),
    ConvExpr("get down to business", "본격적으로 시작하다"),
    ConvExpr("hang by a thread", "아슬아슬한 상황이다"),
    ConvExpr("hard pill to swallow", "받아들이기 힘든 사실"),
    ConvExpr("have a heart", "인정을 좀 베풀다"),
    ConvExpr("hit home", "절실히 와닿다"),
    ConvExpr("hold water", "앞뒤가 맞다, 타당하다"),
    ConvExpr("leave someone hanging", "애타게 기다리게 하다"),
    ConvExpr("lose your touch", "감을 잃다"),
    ConvExpr("keep tabs on", "계속 주시하다"),
    ConvExpr("keep your nose clean", "문제 안 일으키다"),
    ConvExpr("more than meets the eye", "겉보기보다 더 있다"),
    ConvExpr("not my cup of tea", "내 취향이 아니다"),
    ConvExpr("on the same page", "같은 생각을 하고 있다"),
    ConvExpr("on your toes", "긴장하고 대비하다"),
    ConvExpr("out of the woods", "위기를 벗어나다"),
    ConvExpr("over and done with", "완전히 끝난 일"),
    ConvExpr("off the record", "비공식적으로"),
    ConvExpr("off the top of my head", "즉흥적으로 생각나는 대로"),
    ConvExpr("the last straw", "인내의 한계를 넘게 한 것"),
    ConvExpr("bark up the wrong tree", "잘못 짚다"),
    ConvExpr("beat a dead horse", "이미 끝난 얘기를 되풀이하다"),
    ConvExpr("burn the candle at both ends", "무리해서 일하다"),
    ConvExpr("throw someone under the bus", "남에게 책임을 떠넘기다"),
    ConvExpr("throw a wrench in it", "일을 망쳐놓다"),
    ConvExpr("put the cart before the horse", "순서를 뒤바꾸다"),
    ConvExpr("pull the rug out", "갑자기 지원을 끊다"),
    ConvExpr("put your best foot forward", "최선의 모습을 보이다"),
    ConvExpr("quick on the draw", "반응이 빠르다"),
    ConvExpr("raise the roof", "크게 소란을 피우다"),
    ConvExpr("read someone like a book", "속마음을 훤히 꿰뚫다"),
    ConvExpr("rub someone the wrong way", "신경을 거스르다"),
    ConvExpr("run circles around someone", "훨씬 더 뛰어나다"),
    ConvExpr("scrape the bottom of the barrel", "마지막 남은 걸 쥐어짜다"),
    ConvExpr("sell like hotcakes", "불티나게 팔리다"),
    ConvExpr("shape up or ship out", "잘하든가 그만두든가"),
    ConvExpr("short end of the stick", "손해 보는 쪽"),
    ConvExpr("a run for your money", "강력한 경쟁 상대"),
    ConvExpr("spill your guts", "속마음을 다 털어놓다"),
  ],
  // 25번 주제
  [
    ConvExpr("put up with", "참고 견디다"),
    ConvExpr("come across", "우연히 발견하다"),
    ConvExpr("run into", "우연히 마주치다"),
    ConvExpr("get away with", "처벌 없이 넘어가다"),
    ConvExpr("look into", "자세히 조사하다"),
    ConvExpr("look forward to", "기대하다"),
    ConvExpr("come up with", "아이디어를 생각해내다"),
    ConvExpr("end up", "결국 그렇게 되다"),
    ConvExpr("catch up on", "밀린 것을 따라잡다"),
    ConvExpr("catch up with", "따라잡다, 근황을 나누다"),
    ConvExpr("fall behind", "뒤처지다"),
    ConvExpr("fall through", "계획이 무산되다"),
    ConvExpr("follow up on", "후속 조치를 하다"),
    ConvExpr("get around to", "마침내 시간을 내다"),
    ConvExpr("get by", "그럭저럭 살아가다"),
    ConvExpr("get over", "극복하다"),
    ConvExpr("hold off on", "미루다, 보류하다"),
    ConvExpr("hold on to", "꽉 붙잡다, 지키다"),
    ConvExpr("keep up with", "뒤처지지 않게 따라가다"),
    ConvExpr("live up to", "기대에 부응하다"),
    ConvExpr("look down on", "얕보다"),
    ConvExpr("look up to", "존경하다"),
    ConvExpr("make up for", "만회하다, 보상하다"),
    ConvExpr("miss out on", "기회를 놓치다"),
    ConvExpr("pull off", "성공적으로 해내다"),
    ConvExpr("put off", "미루다, 연기하다"),
    ConvExpr("settle down", "정착하다, 안정되다"),
    ConvExpr("stand out", "눈에 띄다"),
    ConvExpr("take after", "닮다"),
    ConvExpr("take over", "인수하다, 넘겨받다"),
    ConvExpr("talk into", "설득해서 시키다"),
    ConvExpr("talk out of", "설득해서 그만두게 하다"),
    ConvExpr("tone down", "누그러뜨리다"),
    ConvExpr("wear off", "효과가 서서히 사라지다"),
    ConvExpr("wear out", "지치게 하다, 닳게 하다"),
    ConvExpr("account for", "설명하다, 차지하다"),
    ConvExpr("act up", "말썽을 부리다"),
    ConvExpr("back down", "물러서다, 포기하다"),
    ConvExpr("back out", "발을 빼다, 취소하다"),
    ConvExpr("bail out", "곤경에서 구해주다"),
    ConvExpr("bank on", "믿고 의지하다"),
    ConvExpr("black out", "정전되다, 기절하다"),
    ConvExpr("boil down to", "결국 그것으로 귀결되다"),
    ConvExpr("bounce back", "다시 회복하다"),
    ConvExpr("branch out", "새로운 분야로 넓히다"),
    ConvExpr("break even", "본전치기하다"),
    ConvExpr("break into", "침입하다"),
    ConvExpr("break off", "갑자기 끊다, 관계를 끊다"),
    ConvExpr("brush up on", "실력을 다시 다듬다"),
    ConvExpr("burn out", "지쳐 나가떨어지다"),
    ConvExpr("call for", "필요로 하다"),
    ConvExpr("call off", "취소하다"),
    ConvExpr("carry on", "계속하다"),
    ConvExpr("cash in on", "이용해 이익을 얻다"),
    ConvExpr("check in on", "안부를 살피다"),
    ConvExpr("chip in", "조금씩 보태다"),
    ConvExpr("clam up", "입을 다물다"),
    ConvExpr("clear out", "다 치우다, 떠나다"),
    ConvExpr("come down with", "병에 걸리다"),
    ConvExpr("come through", "해내다, 도와주다"),
    ConvExpr("count on", "의지하다"),
    ConvExpr("cross off", "목록에서 지우다"),
    ConvExpr("cut back on", "줄이다"),
    ConvExpr("cut off", "끊다, 차단하다"),
    ConvExpr("cut out", "그만두다, 잘라내다"),
    ConvExpr("dawn on", "문득 깨닫다"),
    ConvExpr("deal with", "처리하다, 다루다"),
    ConvExpr("dig into", "깊이 파고들다"),
    ConvExpr("dish out", "나눠주다, 퍼주다"),
    ConvExpr("dive into", "뛰어들다, 몰두하다"),
    ConvExpr("dwell on", "계속 곱씹다"),
    ConvExpr("ease up", "완화하다, 느슨해지다"),
    ConvExpr("even out", "고르게 되다"),
    ConvExpr("fall apart", "무너지다, 망가지다"),
    ConvExpr("fall for", "속아 넘어가다, 반하다"),
    ConvExpr("fall out", "사이가 틀어지다"),
    ConvExpr("fend off", "막아내다"),
    ConvExpr("fill in for", "대신하다"),
    ConvExpr("filter out", "걸러내다"),
    ConvExpr("flip through", "대충 훑어보다"),
    ConvExpr("buckle down", "각오하고 집중하다"),
    ConvExpr("get through", "헤쳐나가다"),
    ConvExpr("give in to", "굴복하다"),
    ConvExpr("gloss over", "대충 얼버무리다"),
    ConvExpr("hang around", "어슬렁거리다"),
    ConvExpr("hang out with", "어울려 놀다"),
    ConvExpr("hash out", "상의해서 해결하다"),
    ConvExpr("hold back", "자제하다, 억누르다"),
    ConvExpr("hold up", "지연시키다, 견디다"),
    ConvExpr("iron out", "문제를 해결하다"),
    ConvExpr("kick off", "시작하다"),
    ConvExpr("knock out", "나가떨어지게 하다"),
    ConvExpr("lash out", "화를 터뜨리다"),
    ConvExpr("lay off", "해고하다"),
    ConvExpr("leave out", "빼다, 제외하다"),
    ConvExpr("level with", "솔직히 말하다"),
    ConvExpr("lighten up", "가볍게 생각하다"),
    ConvExpr("live off", "~에 의존해 살다"),
    ConvExpr("lock in", "확정 짓다"),
    ConvExpr("look out for", "조심하다, 살피다"),
  ],
  // 26번 주제
  [
    ConvExpr("Thanks for joining us.", "참석해 주셔서 감사해요"),
    ConvExpr("Let's dive right in.", "바로 시작할게요"),
    ConvExpr("I'll keep this brief.", "간단히 말씀드릴게요"),
    ConvExpr("Can everyone hear me?", "잘 들리세요"),
    ConvExpr("Let's go over the agenda.", "안건을 살펴봐요"),
    ConvExpr("Let's take it from the top.", "처음부터 다시 해요"),
    ConvExpr("I'll send the slides later.", "슬라이드는 나중에 보낼게요"),
    ConvExpr("Nice to finally meet you.", "드디어 뵙게 되네요"),
    ConvExpr("Let's circle back to that.", "그 얘기는 나중에 다시요"),
    ConvExpr("I'd like to introduce myself.", "제 소개를 드릴게요"),
    ConvExpr("Let's touch base next week.", "다음 주에 연락드려요"),
    ConvExpr("I'll follow up by email.", "이메일로 후속 연락드려요"),
    ConvExpr("Let's put that on hold.", "그건 보류할게요"),
    ConvExpr("Can we push the deadline?", "마감 미룰 수 있나요"),
    ConvExpr("Let's table this for now.", "이건 잠시 미뤄둬요"),
    ConvExpr("I'll loop in the team.", "팀에 공유할게요"),
    ConvExpr("Let's get on the same page.", "서로 이해를 맞춰요"),
    ConvExpr("I appreciate your time today.", "오늘 시간 내주셔서 감사해요"),
    ConvExpr("Let's move to the next item.", "다음 안건으로 넘어가요"),
    ConvExpr("I want to confirm we're aligned.", "의견이 맞는지 확인할게요"),
    ConvExpr("Let me walk you through this.", "이 부분 설명드릴게요"),
    ConvExpr("That's a fair point.", "타당한 지적이에요"),
    ConvExpr("Let's take a step back.", "한 발 물러서 봐요"),
    ConvExpr("I hear where you're coming from.", "그 입장 이해해요"),
    ConvExpr("Let's break this down further.", "더 세분화해 봐요"),
    ConvExpr("We need to nail down details.", "세부사항을 확정해요"),
    ConvExpr("Let's set some clear expectations.", "기대치를 명확히 정해요"),
    ConvExpr("Let's put our heads together.", "함께 머리를 맞대요"),
    ConvExpr("We should leverage our strengths here.", "우리 강점을 활용해요"),
    ConvExpr("Let's align on the next steps.", "다음 단계를 맞춰요"),
    ConvExpr("I want to flag a concern.", "우려사항을 말씀드릴게요"),
    ConvExpr("Let's revisit this after lunch.", "점심 후 다시 논의해요"),
    ConvExpr("We're on a tight timeline.", "일정이 빠듯해요"),
    ConvExpr("Let's prioritize the key deliverables.", "핵심 산출물을 우선해요"),
    ConvExpr("I'll take that action item.", "그 실행 항목 맡을게요"),
    ConvExpr("Let's keep the momentum going.", "이 흐름을 이어가요"),
    ConvExpr("We need buy-in from stakeholders.", "이해관계자 동의가 필요해요"),
    ConvExpr("Let's frame this as an opportunity.", "기회로 보고 접근해요"),
    ConvExpr("I'd like to propose an alternative.", "대안을 제안하고 싶어요"),
    ConvExpr("Let's weigh the pros and cons.", "장단점을 따져봐요"),
    ConvExpr("We should manage expectations early.", "기대치를 미리 조율해요"),
    ConvExpr("Let's finalize the terms today.", "오늘 조건을 확정해요"),
    ConvExpr("I need legal to review this.", "법무 검토가 필요해요"),
    ConvExpr("Let's iron out the details later.", "세부사항은 나중에 조율해요"),
    ConvExpr("We're operating under a tight budget.", "예산이 빠듯한 상태예요"),
    ConvExpr("Let's benchmark against our competitors.", "경쟁사와 비교해 봐요"),
    ConvExpr("I want to close this gap.", "이 격차를 줄이고 싶어요"),
    ConvExpr("Let's negotiate in good faith.", "진심으로 협상에 임해요"),
    ConvExpr("We need a win-win outcome.", "서로 이익인 결과가 필요해요"),
    ConvExpr("Let's keep sight of the goal.", "목표를 계속 염두에 둬요"),
    ConvExpr("I'm willing to meet you halfway.", "절충안에 응할게요"),
    ConvExpr("Let's put it in writing.", "문서로 남겨둬요"),
    ConvExpr("We should escalate this to management.", "경영진에 보고해야 해요"),
    ConvExpr("Let's revisit the scope of work.", "작업 범위를 재검토해요"),
    ConvExpr("I want to lock this price.", "이 가격에 확정하고 싶어요"),
    ConvExpr("Let's draft a formal proposal.", "정식 제안서를 작성해요"),
    ConvExpr("We're not fully aligned yet.", "아직 의견이 안 맞아요"),
    ConvExpr("Let's clarify the contract terms.", "계약 조건을 명확히 해요"),
    ConvExpr("I'd like to network with you.", "그쪽과 교류하고 싶어요"),
    ConvExpr("Let's exchange business cards.", "명함을 교환해요"),
    ConvExpr("We should build on this partnership.", "이 협력관계를 발전시켜요"),
    ConvExpr("Let's outline the next quarter's goals.", "다음 분기 목표를 정리해요"),
    ConvExpr("Let's address the main concern.", "핵심 우려를 다뤄봐요"),
    ConvExpr("Let's streamline this process.", "이 과정을 간소화해요"),
    ConvExpr("We need to mitigate the risks.", "관련 위험을 줄여야 해요"),
    ConvExpr("Let's secure the client's commitment.", "고객의 확답을 받아요"),
    ConvExpr("I'd like to formalize our agreement.", "합의를 공식화하고 싶어요"),
    ConvExpr("Let's revisit our pricing structure.", "가격 구조를 재검토해요"),
    ConvExpr("We should capitalize on this momentum.", "이 흐름을 잘 활용해요"),
    ConvExpr("Let's draw up a timeline.", "일정표를 작성해요"),
    ConvExpr("I want to reiterate our position.", "우리 입장을 다시 밝힐게요"),
    ConvExpr("Let's clarify roles and responsibilities.", "역할과 책임을 명확히 해요"),
    ConvExpr("We need executive sign-off.", "경영진 승인이 필요해요"),
    ConvExpr("Let's expedite the approval process.", "승인 절차를 서둘러요"),
    ConvExpr("I'd like to table a counteroffer.", "역제안을 내고 싶어요"),
    ConvExpr("Let's finalize the deliverables schedule.", "산출물 일정을 확정해요"),
    ConvExpr("We should consolidate our resources.", "자원을 통합해야 해요"),
    ConvExpr("Let's negotiate the terms further.", "조건을 더 협상해요"),
    ConvExpr("I want to hedge against risk.", "위험에 대비하고 싶어요"),
    ConvExpr("Let's assess the feasibility first.", "먼저 실현 가능성을 따져봐요"),
    ConvExpr("We should quantify the impact.", "영향을 수치화해야 해요"),
    ConvExpr("Let's revisit the value proposition.", "가치 제안을 재검토해요"),
    ConvExpr("I'd like to renegotiate the deadline.", "마감일을 재협상하고 싶어요"),
    ConvExpr("Let's align our messaging externally.", "대외 메시지를 통일해요"),
    ConvExpr("We need a contingency plan.", "대비책이 필요해요"),
    ConvExpr("Let's disclose the terms upfront.", "조건을 미리 공개해요"),
    ConvExpr("I want to preempt any objections.", "반대 의견을 미리 대비해요"),
    ConvExpr("Let's formalize this into a contract.", "이걸 계약서로 공식화해요"),
    ConvExpr("We should defer to the client.", "고객 판단을 존중해야 해요"),
    ConvExpr("Let's substantiate our claims with data.", "주장을 데이터로 뒷받침해요"),
    ConvExpr("I'd like to broker a compromise.", "타협을 중재하고 싶어요"),
    ConvExpr("Let's earmark funds for this project.", "이 프로젝트에 예산을 배정해요"),
    ConvExpr("We need to reassess our approach.", "접근법을 재평가해야 해요"),
    ConvExpr("Let's expedite the onboarding process.", "온보딩 과정을 서둘러요"),
    ConvExpr("I want to leverage our network.", "인맥을 활용하고 싶어요"),
    ConvExpr("Let's formalize the partnership agreement.", "파트너십 계약을 공식화해요"),
    ConvExpr("We should reconvene after due diligence.", "실사 후 다시 모여요"),
    ConvExpr("Let's stipulate the payment terms clearly.", "결제 조건을 명확히 명시해요"),
    ConvExpr("I'd like to solicit stakeholder feedback.", "이해관계자 의견을 구하고 싶어요"),
    ConvExpr("Let's ratify the final agreement.", "최종 합의를 승인해요"),
  ],
  // 27번 주제
  [
    ConvExpr("I see your point.", "무슨 말인지 알겠어요"),
    ConvExpr("I agree with that.", "그 말에 동의해요"),
    ConvExpr("Here's my reasoning.", "제 논리는 이래요"),
    ConvExpr("I have a different view.", "저는 생각이 달라요"),
    ConvExpr("Let's look at the facts.", "사실을 살펴봐요"),
    ConvExpr("I see your point, but still.", "이해하지만 여전히 그래요"),
    ConvExpr("That's true, but consider this.", "맞지만 이것도 생각해봐요"),
    ConvExpr("I hear you, however.", "이해는 하지만요"),
    ConvExpr("On the other hand.", "반면에요"),
    ConvExpr("I partly agree with you.", "일부는 동의해요"),
    ConvExpr("Let me push back a bit.", "조금 반박해볼게요"),
    ConvExpr("I'd argue otherwise.", "저는 다르게 봐요"),
    ConvExpr("That's debatable.", "그건 논란의 여지가 있어요"),
    ConvExpr("Not necessarily.", "꼭 그런 건 아니에요"),
    ConvExpr("I take your point, though.", "그 말은 이해하지만요"),
    ConvExpr("I concede that point.", "그 부분은 인정할게요"),
    ConvExpr("You have a fair point there.", "거기엔 일리가 있어요"),
    ConvExpr("Let me counter that.", "반박해볼게요"),
    ConvExpr("That's not entirely accurate.", "그건 정확하지 않아요"),
    ConvExpr("I disagree, respectfully.", "정중히 반대할게요"),
    ConvExpr("Let's break down the argument.", "논거를 나눠서 봐요"),
    ConvExpr("I'll concede that much.", "거기까진 인정할게요"),
    ConvExpr("That's a stretch.", "그건 좀 무리예요"),
    ConvExpr("Let me argue the other side.", "반대 입장에서 말해볼게요"),
    ConvExpr("That argument doesn't hold up.", "그 논리는 성립 안 해요"),
    ConvExpr("I stand corrected.", "제가 틀렸다고 인정해요"),
    ConvExpr("That's a solid counterpoint.", "탄탄한 반론이에요"),
    ConvExpr("Let me qualify that statement.", "그 말은 제한해서 볼게요"),
    ConvExpr("I'll grant you that.", "그 부분은 인정해요"),
    ConvExpr("That's a reasonable compromise.", "합리적인 절충안이에요"),
    ConvExpr("Let's not pursue that angle.", "그 방향은 피해요"),
    ConvExpr("I see merit in that.", "그 점은 타당해요"),
    ConvExpr("That reasoning seems flawed.", "그 논리는 허점 있어요"),
    ConvExpr("To be fair, you're right.", "사실 당신 말이 맞아요"),
    ConvExpr("I'll concede that point too.", "그 점도 인정할게요"),
    ConvExpr("That's a fair rebuttal.", "타당한 반박이에요"),
    ConvExpr("Let's examine the evidence closely.", "증거를 자세히 살펴봐요"),
    ConvExpr("I'm inclined to agree.", "동의하는 쪽이에요"),
    ConvExpr("That's a valid counterargument.", "타당한 반론이에요"),
    ConvExpr("Let me clarify my stance.", "제 입장을 밝힐게요"),
    ConvExpr("I don't buy that argument.", "그 주장은 안 믿어요"),
    ConvExpr("That's a compelling case.", "설득력 있는 주장이에요"),
    ConvExpr("I'll take that under advisement.", "참고해서 생각해볼게요"),
    ConvExpr("Let's not oversimplify this.", "너무 단순화하지 말아요"),
    ConvExpr("That's a matter of perspective.", "관점의 차이예요"),
    ConvExpr("I'm cautious about that claim.", "그 주장은 조심스러워요"),
    ConvExpr("That's an unfounded assumption.", "근거 없는 가정이에요"),
    ConvExpr("Let me qualify my position.", "제 입장을 보완할게요"),
    ConvExpr("I'll concede the broader point.", "큰 틀은 인정할게요"),
    ConvExpr("That's a compelling counterpoint.", "설득력 있는 반론이에요"),
    ConvExpr("Let's not conclude too quickly.", "성급히 결론 내지 말아요"),
    ConvExpr("I stand by my argument.", "제 주장은 변함없어요"),
    ConvExpr("That's a reasonable objection.", "타당한 반대 의견이에요"),
    ConvExpr("Let me address that directly.", "바로 답변할게요"),
    ConvExpr("I'll grant that exception.", "그 예외는 인정할게요"),
    ConvExpr("That's an oversimplification.", "지나친 단순화예요"),
    ConvExpr("Let's consider the counterevidence.", "반대 증거도 살펴봐요"),
    ConvExpr("I disagree with that premise.", "그 전제엔 동의 안 해요"),
    ConvExpr("That's a fair assessment.", "타당한 평가예요"),
    ConvExpr("Let me refine my argument.", "제 주장을 다듬을게요"),
    ConvExpr("I'll acknowledge that weakness.", "그 약점은 인정할게요"),
    ConvExpr("That's a persuasive point.", "설득력 있는 지적이에요"),
    ConvExpr("Let's scrutinize that claim further.", "그 주장을 더 따져봐요"),
    ConvExpr("I'm skeptical of that conclusion.", "그 결론은 의심스러워요"),
    ConvExpr("That's a nuanced issue.", "미묘한 사안이에요"),
    ConvExpr("Let me reframe the question.", "질문을 다시 던질게요"),
    ConvExpr("I'll concede under certain conditions.", "조건부로 인정할게요"),
    ConvExpr("That's a logical fallacy.", "논리적 오류예요"),
    ConvExpr("Let's test that hypothesis.", "그 가설을 검증해봐요"),
    ConvExpr("I remain unconvinced.", "여전히 확신 안 들어요"),
    ConvExpr("That's a compelling rebuttal.", "설득력 있는 반박이에요"),
    ConvExpr("Let me substantiate my claim.", "제 주장을 뒷받침할게요"),
    ConvExpr("I'll qualify that with caution.", "조심스럽게 덧붙일게요"),
    ConvExpr("That's an overstatement.", "과장된 말이에요"),
    ConvExpr("Let's dissect that argument.", "그 주장을 분석해봐요"),
    ConvExpr("I concede the point partially.", "부분적으로 인정해요"),
    ConvExpr("That's a valid critique.", "타당한 비판이에요"),
    ConvExpr("Let me temper my claim.", "주장을 완화할게요"),
    ConvExpr("I'll allow for exceptions.", "예외는 인정할게요"),
    ConvExpr("That's a reasonable caveat.", "합리적인 단서예요"),
    ConvExpr("Let's not overstate the risk.", "위험을 과장하지 말아요"),
    ConvExpr("I stand firm on this.", "이 점은 확고해요"),
    ConvExpr("That's a compelling premise.", "설득력 있는 전제예요"),
    ConvExpr("Let me qualify this further.", "좀 더 보완해서 말할게요"),
    ConvExpr("I'll grant the exception here.", "여기선 예외를 인정할게요"),
    ConvExpr("That's a shaky argument.", "근거가 약한 주장이에요"),
    ConvExpr("Let's revisit the underlying assumption.", "근본 가정을 재검토해요"),
    ConvExpr("I concede that under scrutiny.", "따져보니 인정하게 되네요"),
    ConvExpr("That's a valid nuance.", "타당한 뉘앙스예요"),
    ConvExpr("Let me hedge on that point.", "그 부분은 조심스럽게 말할게요"),
    ConvExpr("I'll allow that possibility.", "그 가능성은 인정해요"),
    ConvExpr("That's an inconclusive argument.", "결론이 안 나는 주장이에요"),
    ConvExpr("Let's not conflate the two issues.", "두 사안을 혼동하지 말아요"),
    ConvExpr("I remain skeptical, admittedly.", "솔직히 여전히 의심돼요"),
    ConvExpr("That's a defensible position.", "방어할 수 있는 입장이에요"),
    ConvExpr("Let me qualify my hedge here.", "여기서 조건을 달게요"),
    ConvExpr("I'll concede that caveat.", "그 단서는 인정할게요"),
    ConvExpr("That's an untenable position.", "지지받기 힘든 입장이에요"),
    ConvExpr("Let's not lose the nuance.", "미묘한 차이를 놓치지 말아요"),
    ConvExpr("I stand corrected, admittedly.", "솔직히 제가 틀렸네요"),
  ],
  // 28번 주제
  [
    ConvExpr("Anything fun planned?", "재밌는 계획 있어요"),
    ConvExpr("It's been a while.", "오랜만이네요"),
    ConvExpr("It's been ages, honestly.", "정말 오랜만이에요"),
    ConvExpr("What have you been up to?", "요즘 어떻게 지냈어요"),
    ConvExpr("Nothing much, same routine.", "그냥 똑같이 지내요"),
    ConvExpr("Did you catch the game?", "그 경기 봤어요"),
    ConvExpr("I love your haircut.", "머리 스타일 멋져요"),
    ConvExpr("That color suits you.", "그 색 잘 어울려요"),
    ConvExpr("You look great today.", "오늘 멋져 보여요"),
    ConvExpr("How's the family doing?", "가족들은 잘 지내세요"),
    ConvExpr("Work's been keeping me busy.", "요즘 일 때문에 바빠요"),
    ConvExpr("I needed that weekend.", "그 주말이 필요했어요"),
    ConvExpr("This year is going by fast.", "올해 정말 빨리 가네요"),
    ConvExpr("Have you tried the new cafe?", "새로 생긴 카페 가봤어요"),
    ConvExpr("I've been meaning to call you.", "전화한다고 하고 못 했어요"),
    ConvExpr("Life's been pretty hectic lately.", "요즘 정신없이 바빠요"),
    ConvExpr("We should grab coffee sometime.", "언제 커피 한잔해요"),
    ConvExpr("Any plans for the holidays?", "연휴 계획 있어요"),
    ConvExpr("I heard you got a promotion.", "승진했다고 들었어요"),
    ConvExpr("That's exciting news!", "정말 좋은 소식이네요"),
    ConvExpr("Congrats on the new job.", "새 직장 축하해요"),
    ConvExpr("How's the new place working out?", "새 집은 어때요"),
    ConvExpr("I saw your post online.", "온라인에서 글 봤어요"),
    ConvExpr("What a coincidence, running into you.", "이런 데서 만나다니 신기해요"),
    ConvExpr("We should do this more often.", "이런 자리 더 가져요"),
    ConvExpr("This weather's been something else.", "요즘 날씨 정말 특이해요"),
    ConvExpr("I can't believe it's already fall.", "벌써 가을이라니 믿기지 않아요"),
    ConvExpr("Did you catch the news today?", "오늘 뉴스 봤어요"),
    ConvExpr("That's a nice change of pace.", "좋은 기분 전환이네요"),
    ConvExpr("How's the new gig treating you?", "새 일은 잘 맞아요"),
    ConvExpr("You seem to be doing well.", "요즘 잘 지내는 것 같아요"),
    ConvExpr("Life's treating you nicely, huh?", "요즘 인생이 참 편해 보여요"),
    ConvExpr("I've missed catching up with you.", "그동안 얘기 못 나눠서 아쉬웠어요"),
    ConvExpr("We really should stay connected more.", "자주 연락하고 지내요"),
    ConvExpr("It's good to see you again.", "다시 만나서 반가워요"),
    ConvExpr("What's new with you these days?", "요즘 뭐 새로운 거 있어요"),
    ConvExpr("I heard the weather's turning colder.", "날씨가 더 추워진대요"),
    ConvExpr("You've barely changed at all.", "예전이랑 하나도 안 변했어요"),
    ConvExpr("This place has changed so much.", "이곳 참 많이 변했네요"),
    ConvExpr("I ran into an old friend.", "오늘 옛 친구 만났어요"),
    ConvExpr("How's everyone back home doing?", "고향 사람들은 잘 지내요"),
    ConvExpr("We should plan a get-together soon.", "조만간 모임 한번 가져요"),
    ConvExpr("Life's been busier than usual.", "요즘 정신없이 바빴어요"),
    ConvExpr("I love what you did here.", "여기 꾸민 게 참 마음에 들어요"),
    ConvExpr("That's quite the story!", "그거 정말 재밌는 얘기네요"),
    ConvExpr("You always make me smile.", "항상 절 웃게 만드네요"),
    ConvExpr("It's nice catching up like this.", "이렇게 얘기하니 좋네요"),
    ConvExpr("We don't do this enough.", "이런 자리 자주 못 가지네요"),
    ConvExpr("I'll let you get going then.", "이제 그만 가볼게요"),
    ConvExpr("It was great seeing you.", "만나서 정말 반가웠어요"),
    ConvExpr("Let's not wait so long again.", "다음엔 너무 오래 있다 만나지 말아요"),
    ConvExpr("Take care until next time.", "다음에 또 봐요"),
    ConvExpr("Give my best to your family.", "가족분들께 안부 전해주세요"),
    ConvExpr("I'll text you to plan something.", "약속 잡으려고 문자할게요"),
    ConvExpr("Enjoy the rest of your day.", "남은 하루 잘 보내요"),
    ConvExpr("This was a nice little chat.", "짧지만 좋은 대화였어요"),
    ConvExpr("Let's do this again sometime soon.", "조만간 또 이렇게 만나요"),
    ConvExpr("I should get back to it.", "이제 다시 일해야겠어요"),
    ConvExpr("Anyway, I won't keep you.", "이만 붙잡지 않을게요"),
    ConvExpr("Tell your folks I said hi.", "부모님께도 안부 전해줘요"),
    ConvExpr("I'm glad we crossed paths today.", "이렇게 만나서 반가워요"),
    ConvExpr("It's always nice to see you.", "항상 만나면 좋아요"),
    ConvExpr("Let's stay in better contact.", "이제 자주 연락해요"),
    ConvExpr("I'll catch you next time around.", "다음번에 또 만나요"),
    ConvExpr("Have a relaxing weekend ahead.", "이번 주말 푹 쉬어요"),
    ConvExpr("Good talking to you as always.", "늘 그렇듯 즐거운 얘기였어요"),
    ConvExpr("I really enjoyed this conversation.", "정말 즐거운 대화였어요"),
    ConvExpr("Let's pick this up again soon.", "다음에 또 이어서 얘기해요"),
    ConvExpr("This chat really brightened my day.", "이 대화 덕에 기분 좋아졌어요"),
    ConvExpr("You've got a lot going on.", "요즘 할 일이 많나 봐요"),
    ConvExpr("Things have been hectic here too.", "여기도 요즘 정신없이 바빠요"),
    ConvExpr("I could talk for hours.", "몇 시간이고 얘기할 수 있어요"),
    ConvExpr("We talked longer than we planned.", "생각보다 오래 얘기했네요"),
    ConvExpr("It's rare we get to talk.", "이렇게 얘기할 기회가 드물어요"),
    ConvExpr("This was a lovely catch-up.", "오랜만에 정말 좋은 수다였어요"),
    ConvExpr("I'll let you run along now.", "이제 가던 길 가세요"),
    ConvExpr("We should really do this weekly.", "매주 이렇게 만나요"),
    ConvExpr("Thanks for making time for me.", "시간 내줘서 고마워요"),
    ConvExpr("This weekend went by too fast.", "이번 주말 너무 빨리 갔어요"),
    ConvExpr("I heard you're moving next month.", "다음 달에 이사 간다면서요"),
    ConvExpr("That must keep you quite busy.", "그것 때문에 많이 바쁘겠어요"),
    ConvExpr("How's the renovation going so far?", "리모델링은 잘 되고 있어요"),
    ConvExpr("You mentioned starting a new hobby.", "새 취미 시작했다면서요"),
    ConvExpr("I've been curious about that lately.", "그거 궁금했었어요"),
    ConvExpr("That sounds like quite an adventure.", "정말 흥미로운 얘기네요"),
    ConvExpr("You always have the best stories.", "항상 얘기가 참 재밌어요"),
    ConvExpr("I never tire of your stories.", "그 얘기들 언제 들어도 좋아요"),
    ConvExpr("Let's swap stories over coffee sometime.", "다음에 커피 마시며 얘기해요"),
    ConvExpr("I've been meaning to reach out.", "연락한다고 하고 못 했어요"),
    ConvExpr("Sounds like a lot's been happening.", "요즘 이런저런 일이 많은가 봐요"),
    ConvExpr("I'm curious how that turned out.", "그 일이 어떻게 됐는지 궁금해요"),
    ConvExpr("Things seem to be looking up.", "요즘 좋은 일이 많은가 봐요"),
    ConvExpr("I'd love to hear more sometime.", "다음에 더 자세히 듣고 싶어요"),
    ConvExpr("We always find plenty to discuss.", "우리는 항상 할 얘기가 많아요"),
    ConvExpr("This conversation went by so fast.", "이 대화 정말 금방 지나갔어요"),
    ConvExpr("I hope your week goes smoothly.", "한 주 잘 보내길 바라요"),
    ConvExpr("Let's grab lunch and catch up.", "점심 먹으며 얘기 좀 해요"),
    ConvExpr("I'll let you go for now.", "이제 가보셔도 돼요"),
    ConvExpr("It was wonderful seeing you today.", "오늘 만나서 정말 좋았어요"),
    ConvExpr("Let's not let so long pass.", "다음엔 너무 오래 걸리지 않게 해요"),
  ],
  // 29번 주제
  [
    ConvExpr("I'm down.", "참여할래요"),
    ConvExpr("No worries.", "괜찮아요"),
    ConvExpr("My bad.", "제 잘못이에요"),
    ConvExpr("I'm in.", "낄게요"),
    ConvExpr("I'm game.", "저도 참여요"),
    ConvExpr("Works for me.", "저는 좋아요"),
    ConvExpr("That tracks.", "그럴 만하네요"),
    ConvExpr("I'm beat.", "완전 지쳤어요"),
    ConvExpr("I'm starving.", "배고파 죽겠어요"),
    ConvExpr("I could eat.", "뭐든 먹을 수 있어요"),
    ConvExpr("I'm exhausted.", "진이 다 빠졌어요"),
    ConvExpr("I'm totally drained.", "완전 녹초예요"),
    ConvExpr("I'm not feeling it.", "오늘은 내키지 않아요"),
    ConvExpr("I'll pass, thanks.", "저는 빠질게요"),
    ConvExpr("Maybe next time.", "다음에 할게요"),
    ConvExpr("I'm easy either way.", "뭐든 상관없어요"),
    ConvExpr("It is what it is.", "어쩔 수 없죠"),
    ConvExpr("That's on me.", "제가 살게요"),
    ConvExpr("My mistake, sorry.", "제 실수예요, 미안해요"),
    ConvExpr("I got you covered.", "제가 처리할게요"),
    ConvExpr("I'm all set.", "준비 다 됐어요"),
    ConvExpr("I'm good for now.", "지금은 괜찮아요"),
    ConvExpr("I'm cool with that.", "저는 괜찮아요"),
    ConvExpr("Whatever works.", "아무거나 좋아요"),
    ConvExpr("Up to you.", "당신한테 달렸어요"),
    ConvExpr("I don't mind either way.", "어느 쪽이든 상관없어요"),
    ConvExpr("I'm not fussed.", "크게 신경 안 써요"),
    ConvExpr("No biggie.", "별거 아니에요"),
    ConvExpr("It's all good.", "다 괜찮아요"),
    ConvExpr("Take your time.", "천천히 하세요"),
    ConvExpr("I'm easy.", "저는 아무래도 좋아요"),
    ConvExpr("Let's just wing it.", "그냥 즉흥적으로 해요"),
    ConvExpr("I'll wing it.", "즉흥적으로 할게요"),
    ConvExpr("Let's just play it cool.", "그냥 태연하게 있어요"),
    ConvExpr("I'm not mad about it.", "화 안 났어요"),
    ConvExpr("Could be worse.", "이 정도면 다행이에요"),
    ConvExpr("Could've been worse.", "더 나쁠 수도 있었어요"),
    ConvExpr("Not the end of the world.", "큰일 아니에요"),
    ConvExpr("It's whatever.", "뭐 아무래도요"),
    ConvExpr("I'm over it.", "이제 신경 안 써요"),
    ConvExpr("I'm so done.", "진짜 지쳤어요"),
    ConvExpr("I'm calling it a day.", "오늘은 여기까지 할게요"),
    ConvExpr("Let's call it a night.", "오늘 밤은 여기까지 해요"),
    ConvExpr("I'm out for tonight.", "오늘 밤은 빠질게요"),
    ConvExpr("I'm heading out.", "저 이만 나갈게요"),
    ConvExpr("Catch you later.", "나중에 봐요"),
    ConvExpr("Hit me up later.", "나중에 연락해요"),
    ConvExpr("Text me when you're free.", "시간 되면 문자해요"),
    ConvExpr("I'll get there later.", "나중에 갈게요"),
    ConvExpr("I'll text you the details.", "자세한 내용 문자할게요"),
    ConvExpr("Let's plan something soon.", "조만간 계획 잡아요"),
    ConvExpr("I'm around if you need me.", "필요하면 저 있어요"),
    ConvExpr("Hit me up anytime.", "언제든 연락해요"),
    ConvExpr("I got your back.", "제가 도와줄게요"),
    ConvExpr("I'm here for you.", "제가 곁에 있을게요"),
    ConvExpr("I'm on your side.", "저는 당신 편이에요"),
    ConvExpr("I'm not buying it.", "그 말은 안 믿어요"),
    ConvExpr("That's a bit much.", "그건 좀 심해요"),
    ConvExpr("I'm not about that.", "저랑은 안 맞아요"),
    ConvExpr("Not my thing.", "제 취향 아니에요"),
    ConvExpr("Never really been my scene.", "제 취향은 아니었어요"),
    ConvExpr("That's so not me.", "저답지 않아요"),
    ConvExpr("I'm not that type.", "저는 그런 타입 아니에요"),
    ConvExpr("I'm more of a homebody.", "저는 집순이 스타일이에요"),
    ConvExpr("I do better at night.", "밤에 더 잘 돼요"),
    ConvExpr("I'm a bit of a perfectionist.", "저는 좀 완벽주의예요"),
    ConvExpr("I tend to overthink things.", "생각이 많은 편이에요"),
    ConvExpr("I'm pretty laid-back, honestly.", "사실 꽤 느긋해요"),
    ConvExpr("I just take things easy.", "그냥 편하게 살아요"),
    ConvExpr("I don't stress over little things.", "작은 일엔 스트레스 안 받아요"),
    ConvExpr("I'm chill about most things.", "대부분 대수롭지 않게 여겨요"),
    ConvExpr("I adapt pretty easily.", "적응을 잘하는 편이에요"),
    ConvExpr("I'm pretty easygoing.", "저는 성격이 무난해요"),
    ConvExpr("I take things as they come.", "그때그때 대처하는 편이에요"),
    ConvExpr("I don't overthink it much.", "크게 고민하지 않아요"),
    ConvExpr("That's just my style.", "그게 제 스타일이에요"),
    ConvExpr("I'm all about efficiency.", "효율을 중요하게 여겨요"),
    ConvExpr("I'm big on honesty.", "솔직함을 중요하게 여겨요"),
    ConvExpr("I'm not big on drama.", "소란스러운 건 안 좋아해요"),
    ConvExpr("I keep things simple.", "단순하게 사는 편이에요"),
    ConvExpr("I like to keep it real.", "솔직하게 지내는 걸 좋아해요"),
    ConvExpr("I try to keep it low-key.", "조용히 지내려고 해요"),
    ConvExpr("Nothing too exciting happened.", "특별한 일은 없었어요"),
    ConvExpr("It was a whole thing.", "꽤 복잡한 일이었어요"),
    ConvExpr("Long story short, it worked out.", "결국 잘 풀렸어요"),
    ConvExpr("I'm kind of a homebody, honestly.", "사실 집순이 편이에요"),
    ConvExpr("I don't do mornings well.", "아침엔 잘 못 일어나요"),
    ConvExpr("I'm more of a listener.", "저는 듣는 편이에요"),
    ConvExpr("I need my alone time sometimes.", "가끔 혼자만의 시간 필요해요"),
    ConvExpr("I'm an open book, honestly.", "사실 숨기는 거 없어요"),
    ConvExpr("I tend to overshare sometimes.", "가끔 너무 다 말해요"),
    ConvExpr("I just speak my mind.", "그냥 솔직히 말해요"),
    ConvExpr("I'm pretty blunt, not gonna lie.", "솔직히 좀 직설적이에요"),
    ConvExpr("Not gonna lie, I'm nervous.", "솔직히 좀 긴장돼요"),
    ConvExpr("I'm kind of a perfectionist, honestly.", "사실 좀 완벽주의예요"),
    ConvExpr("I'm not much of a planner.", "계획 세우는 편은 아니에요"),
    ConvExpr("I tend to wing important decisions.", "중요한 결정도 즉흥적으로 해요"),
    ConvExpr("I'm kind of an introvert, honestly.", "사실 좀 내향적이에요"),
    ConvExpr("I recharge by staying in.", "집에서 에너지를 채워요"),
    ConvExpr("I'd rather stay in tonight.", "오늘 밤은 집에 있을래요"),
  ],
  // 30번 주제
  [
    ConvExpr("It depends.", "상황 따라 달라요"),
    ConvExpr("That depends on the situation.", "상황에 따라 다르죠"),
    ConvExpr("Let's see how it goes.", "되어가는 거 봐요"),
    ConvExpr("I'll figure something out.", "방법을 찾아볼게요"),
    ConvExpr("Let's play it by ear.", "상황 봐서 정해요"),
    ConvExpr("We'll cross that bridge later.", "그건 나중에 생각해요"),
    ConvExpr("Let's wait and see.", "기다려 보죠"),
    ConvExpr("I'll let you know.", "알려드릴게요"),
    ConvExpr("It could go either way.", "어느 쪽이든 될 수 있어요"),
    ConvExpr("I'll deal with it later.", "나중에 처리할게요"),
    ConvExpr("Let's see what happens.", "어떻게 되는지 봐요"),
    ConvExpr("I haven't decided yet.", "아직 결정 안 했어요"),
    ConvExpr("I'll handle it somehow.", "어떻게든 해결할게요"),
    ConvExpr("It's hard to say.", "뭐라 말하기 어려워요"),
    ConvExpr("That remains to be seen.", "두고 봐야 알아요"),
    ConvExpr("I'll manage somehow.", "어떻게든 될 거예요"),
    ConvExpr("We'll figure it out together.", "같이 방법을 찾아봐요"),
    ConvExpr("I'll take it as it comes.", "되는 대로 받아들일게요"),
    ConvExpr("Let's not worry about that now.", "지금은 걱정하지 말아요"),
    ConvExpr("I'll cross my fingers.", "행운을 빌어볼게요"),
    ConvExpr("Let's keep our options open.", "선택지는 열어둬요"),
    ConvExpr("I'll leave it up to you.", "당신에게 맡길게요"),
    ConvExpr("That's up in the air.", "아직 미정이에요"),
    ConvExpr("It varies from case to case.", "경우마다 달라요"),
    ConvExpr("I'll take it slow.", "천천히 할게요"),
    ConvExpr("Let's not rush into anything.", "서두르지 말아요"),
    ConvExpr("I'll sort it out eventually.", "결국 정리될 거예요"),
    ConvExpr("We'll see what comes up.", "어떤 일이 생기는지 봐요"),
    ConvExpr("I'll adjust as we go.", "진행하면서 조정할게요"),
    ConvExpr("Let's keep things flexible.", "유연하게 가져가요"),
    ConvExpr("I'll make it work somehow.", "어떻게든 되게 할게요"),
    ConvExpr("That's still up for debate.", "아직 논의 중이에요"),
    ConvExpr("I'll decide when the time comes.", "때가 되면 결정할게요"),
    ConvExpr("Let's leave it for later.", "나중으로 미뤄둬요"),
    ConvExpr("I'll take whatever comes my way.", "오는 대로 받아들일게요"),
    ConvExpr("It's anyone's guess at this point.", "지금은 아무도 몰라요"),
    ConvExpr("I'll go with whatever works.", "되는 대로 할게요"),
    ConvExpr("Let's not overthink this.", "너무 깊게 생각 말아요"),
    ConvExpr("I'll manage one way or another.", "어떻게든 해낼게요"),
    ConvExpr("That's not really the point.", "그게 핵심은 아니에요"),
    ConvExpr("Let's stay open to options.", "다른 가능성도 열어둬요"),
    ConvExpr("I'll adapt as things change.", "상황 따라 맞춰갈게요"),
    ConvExpr("It changes depending on the day.", "날마다 달라져요"),
    ConvExpr("I'll take that into account.", "그 점 고려할게요"),
    ConvExpr("Let's revisit that another time.", "다음에 다시 얘기해요"),
    ConvExpr("I'll see how I feel.", "기분 봐서 할게요"),
    ConvExpr("That's a case-by-case thing.", "경우에 따라 달라요"),
    ConvExpr("I'll play it safe for now.", "일단 안전하게 갈게요"),
    ConvExpr("Let's not commit to anything yet.", "아직 확정하지 말아요"),
    ConvExpr("I'll keep my options open.", "선택지를 열어둘게요"),
    ConvExpr("It's too early to tell.", "아직 판단하긴 일러요"),
    ConvExpr("I'll wait for more information.", "정보를 좀 더 기다릴게요"),
    ConvExpr("Let's hold off for now.", "지금은 미뤄둬요"),
    ConvExpr("I'll take it under consideration.", "고려해 볼게요"),
    ConvExpr("That's still up for grabs.", "아직 누구든 될 수 있어요"),
    ConvExpr("I'll see what I can do.", "할 수 있는지 볼게요"),
    ConvExpr("Let's leave room for change.", "변경 여지는 남겨둬요"),
    ConvExpr("I'll adjust the plan if needed.", "필요하면 계획 조정할게요"),
    ConvExpr("That's beyond my control.", "제가 어쩔 수 없어요"),
    ConvExpr("I'll do what I can.", "할 수 있는 만큼 할게요"),
    ConvExpr("Let's take it day by day.", "하루하루 지내봐요"),
    ConvExpr("I'll roll with whatever happens.", "상황대로 따를게요"),
    ConvExpr("It's out of my hands.", "제 손을 떠났어요"),
    ConvExpr("I'll make the best of it.", "최선을 다해볼게요"),
    ConvExpr("Let's not plan too far ahead.", "너무 멀리 계획하지 말아요"),
    ConvExpr("I'll decide that later on.", "그건 나중에 정할게요"),
    ConvExpr("That's a judgment call.", "판단이 필요한 문제예요"),
    ConvExpr("I'll leave that undecided for now.", "그건 아직 미정으로 둘게요"),
    ConvExpr("Let's not lock anything in yet.", "아직 확정 짓지 말아요"),
    ConvExpr("I'll keep an open mind.", "열린 마음으로 있을게요"),
    ConvExpr("It could really go any way.", "어느 쪽이든 갈 수 있어요"),
    ConvExpr("I'll take things as they happen.", "일어나는 대로 받아들일게요"),
    ConvExpr("Let's not box ourselves in.", "틀에 갇히지 말아요"),
    ConvExpr("I'll see where things lead.", "흘러가는 대로 볼게요"),
    ConvExpr("That's really anyone's call.", "누구든 결정할 수 있어요"),
    ConvExpr("I'll leave the details for later.", "세부사항은 나중으로 미룰게요"),
    ConvExpr("Let's not get ahead of ourselves.", "너무 앞서가지 말아요"),
    ConvExpr("I'll deal with that later on.", "그건 나중에 처리할게요"),
    ConvExpr("That's still very much undecided.", "아직 완전히 미정이에요"),
    ConvExpr("I'll go from there.", "그때 가서 정할게요"),
    ConvExpr("Let's see where this leads us.", "이게 어디로 갈지 봐요"),
    ConvExpr("I'll take it from there.", "그다음은 제가 이어갈게요"),
    ConvExpr("That's a moving target.", "계속 바뀌는 상황이에요"),
    ConvExpr("I'll keep that in mind.", "명심할게요"),
    ConvExpr("Let's revisit once we know more.", "더 알게 되면 다시 봐요"),
    ConvExpr("I'll figure out the details later.", "세부사항은 나중에 정할게요"),
    ConvExpr("That's really hard to predict.", "정말 예측하기 어려워요"),
    ConvExpr("I'll take a wait-and-see approach.", "일단 지켜보는 쪽으로 할게요"),
    ConvExpr("Let's not set anything in stone.", "아직 확정 짓진 말아요"),
    ConvExpr("I'll leave it open-ended for now.", "지금은 열어둘게요"),
    ConvExpr("That's still very much in flux.", "아직 계속 변하는 중이에요"),
    ConvExpr("I'll navigate it as it unfolds.", "상황 봐가며 대처할게요"),
    ConvExpr("Let's keep our plans loose.", "계획은 느슨하게 둬요"),
    ConvExpr("I'll adjust on the fly.", "그때그때 조정할게요"),
    ConvExpr("That's really context-dependent.", "상황에 따라 다른 문제예요"),
    ConvExpr("I'll take it moment by moment.", "순간순간 대처할게요"),
    ConvExpr("Let's not overcommit just yet.", "아직 너무 확답하지 말아요"),
    ConvExpr("I'll play things by instinct.", "감으로 대처할게요"),
    ConvExpr("That's subject to change.", "변경될 수 있어요"),
    ConvExpr("I'll leave the door open.", "가능성은 열어둘게요"),
  ],
];
